// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="transformer_top_transformer_top,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.278000,HLS_SYN_LAT=17,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=16424,HLS_SYN_LUT=51768,HLS_VERSION=2025_1}" *)

module transformer_top (
        ap_clk,
        ap_rst_n,
        axis_in_valid,
        axis_in_last,
        axis_in_ready,
        axis_in_ready_ap_vld,
        stream_ready,
        stream_start,
        stream_start_ap_vld,
        stream_done,
        irq_ps,
        dma_done,
        wl_ready,
        wl_instruction,
        wl_instruction_ap_vld,
        wl_start_i,
        wl_start_o,
        wl_start_o_ap_vld,
        mem_transfer_done,
        mem_read_request,
        mem_read_request_ap_vld,
        mem_write_request,
        mem_write_request_ap_vld,
        mem_op,
        mem_op_ap_vld,
        in_buf_address0,
        in_buf_ce0,
        in_buf_q0,
        in_buf_address1,
        in_buf_ce1,
        in_buf_q1,
        out_buf_address0,
        out_buf_ce0,
        out_buf_we0,
        out_buf_d0,
        out_buf_address1,
        out_buf_ce1,
        out_buf_we1,
        out_buf_d1,
        head_ctx_ref_0_i,
        head_ctx_ref_0_o,
        head_ctx_ref_0_o_ap_vld,
        head_ctx_ref_1_i,
        head_ctx_ref_1_o,
        head_ctx_ref_1_o_ap_vld,
        head_ctx_ref_2_i,
        head_ctx_ref_2_o,
        head_ctx_ref_2_o_ap_vld,
        head_ctx_ref_3_i,
        head_ctx_ref_3_o,
        head_ctx_ref_3_o_ap_vld,
        STATE,
        STATE_ap_vld,
        dbg_ctrl_mem,
        dbg_ctrl_mem_ap_vld,
        control_reg,
        control_reg_ap_vld,
        irq_status_reg,
        irq_status_reg_ap_vld,
        irq_mask_reg,
        irq_mask_reg_ap_vld,
        irq_clear_reg,
        irq_clear_reg_ap_vld,
        wq_base_addr,
        wq_base_addr_ap_vld,
        wk_base_addr,
        wk_base_addr_ap_vld,
        wv_base_addr,
        wv_base_addr_ap_vld,
        wo_base_addr,
        wo_base_addr_ap_vld,
        w1_base_addr,
        w1_base_addr_ap_vld,
        w2_base_addr,
        w2_base_addr_ap_vld,
        wq_head_stride,
        wq_head_stride_ap_vld,
        wk_head_stride,
        wk_head_stride_ap_vld,
        wv_head_stride,
        wv_head_stride_ap_vld,
        wo_tile_stride,
        wo_tile_stride_ap_vld,
        w1_tile_stride,
        w1_tile_stride_ap_vld,
        w2_tile_stride,
        w2_tile_stride_ap_vld,
        dbg_compute_start,
        dbg_compute_start_ap_vld,
        dbg_compute_instruction,
        dbg_compute_instruction_ap_vld,
        dbg_compute_ready,
        dbg_compute_ready_ap_vld,
        dbg_compute_done,
        dbg_compute_done_ap_vld,
        dbg_compute_state,
        dbg_compute_state_ap_vld,
        dbg_req_instruction,
        dbg_req_instruction_ap_vld,
        dbg_req_op,
        dbg_req_op_ap_vld,
        dbg_req_layer,
        dbg_req_layer_ap_vld,
        dbg_req_head,
        dbg_req_head_ap_vld,
        dbg_req_tile,
        dbg_req_tile_ap_vld,
        dbg_mac_start,
        dbg_mac_start_ap_vld,
        dbg_mac_ready,
        dbg_mac_ready_ap_vld,
        dbg_mac_complete,
        dbg_mac_complete_ap_vld,
        dbg_ctrl_reset_asserted,
        dbg_ctrl_reset_asserted_ap_vld,
        dbg_done,
        dbg_done_ap_vld,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 8;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [0:0] axis_in_valid;
input  [0:0] axis_in_last;
output  [0:0] axis_in_ready;
output   axis_in_ready_ap_vld;
input  [0:0] stream_ready;
output  [0:0] stream_start;
output   stream_start_ap_vld;
input  [0:0] stream_done;
output  [0:0] irq_ps;
input  [0:0] dma_done;
input  [0:0] wl_ready;
output  [31:0] wl_instruction;
output   wl_instruction_ap_vld;
input  [0:0] wl_start_i;
output  [0:0] wl_start_o;
output   wl_start_o_ap_vld;
input  [0:0] mem_transfer_done;
output  [0:0] mem_read_request;
output   mem_read_request_ap_vld;
output  [0:0] mem_write_request;
output   mem_write_request_ap_vld;
output  [31:0] mem_op;
output   mem_op_ap_vld;
output  [7:0] in_buf_address0;
output   in_buf_ce0;
input  [7:0] in_buf_q0;
output  [7:0] in_buf_address1;
output   in_buf_ce1;
input  [7:0] in_buf_q1;
output  [5:0] out_buf_address0;
output   out_buf_ce0;
output   out_buf_we0;
output  [7:0] out_buf_d0;
output  [5:0] out_buf_address1;
output   out_buf_ce1;
output   out_buf_we1;
output  [7:0] out_buf_d1;
input  [213:0] head_ctx_ref_0_i;
output  [213:0] head_ctx_ref_0_o;
output   head_ctx_ref_0_o_ap_vld;
input  [213:0] head_ctx_ref_1_i;
output  [213:0] head_ctx_ref_1_o;
output   head_ctx_ref_1_o_ap_vld;
input  [213:0] head_ctx_ref_2_i;
output  [213:0] head_ctx_ref_2_o;
output   head_ctx_ref_2_o_ap_vld;
input  [213:0] head_ctx_ref_3_i;
output  [213:0] head_ctx_ref_3_o;
output   head_ctx_ref_3_o_ap_vld;
output  [31:0] STATE;
output   STATE_ap_vld;
output  [1215:0] dbg_ctrl_mem;
output   dbg_ctrl_mem_ap_vld;
output  [31:0] control_reg;
output   control_reg_ap_vld;
output  [31:0] irq_status_reg;
output   irq_status_reg_ap_vld;
output  [31:0] irq_mask_reg;
output   irq_mask_reg_ap_vld;
output  [31:0] irq_clear_reg;
output   irq_clear_reg_ap_vld;
output  [31:0] wq_base_addr;
output   wq_base_addr_ap_vld;
output  [31:0] wk_base_addr;
output   wk_base_addr_ap_vld;
output  [31:0] wv_base_addr;
output   wv_base_addr_ap_vld;
output  [31:0] wo_base_addr;
output   wo_base_addr_ap_vld;
output  [31:0] w1_base_addr;
output   w1_base_addr_ap_vld;
output  [31:0] w2_base_addr;
output   w2_base_addr_ap_vld;
output  [31:0] wq_head_stride;
output   wq_head_stride_ap_vld;
output  [31:0] wk_head_stride;
output   wk_head_stride_ap_vld;
output  [31:0] wv_head_stride;
output   wv_head_stride_ap_vld;
output  [31:0] wo_tile_stride;
output   wo_tile_stride_ap_vld;
output  [31:0] w1_tile_stride;
output   w1_tile_stride_ap_vld;
output  [31:0] w2_tile_stride;
output   w2_tile_stride_ap_vld;
output  [0:0] dbg_compute_start;
output   dbg_compute_start_ap_vld;
output  [31:0] dbg_compute_instruction;
output   dbg_compute_instruction_ap_vld;
output  [0:0] dbg_compute_ready;
output   dbg_compute_ready_ap_vld;
output  [0:0] dbg_compute_done;
output   dbg_compute_done_ap_vld;
output  [7:0] dbg_compute_state;
output   dbg_compute_state_ap_vld;
output  [31:0] dbg_req_instruction;
output   dbg_req_instruction_ap_vld;
output  [7:0] dbg_req_op;
output   dbg_req_op_ap_vld;
output  [7:0] dbg_req_layer;
output   dbg_req_layer_ap_vld;
output  [7:0] dbg_req_head;
output   dbg_req_head_ap_vld;
output  [7:0] dbg_req_tile;
output   dbg_req_tile_ap_vld;
output  [0:0] dbg_mac_start;
output   dbg_mac_start_ap_vld;
output  [0:0] dbg_mac_ready;
output   dbg_mac_ready_ap_vld;
output  [0:0] dbg_mac_complete;
output   dbg_mac_complete_ap_vld;
output  [0:0] dbg_ctrl_reset_asserted;
output   dbg_ctrl_reset_asserted_ap_vld;
output  [0:0] dbg_done;
output   dbg_done_ap_vld;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

reg axis_in_ready_ap_vld;
reg stream_start_ap_vld;
reg[0:0] irq_ps;
reg[31:0] wl_instruction;
reg wl_start_o_ap_vld;
reg[0:0] mem_read_request;
reg[0:0] mem_write_request;
reg[31:0] mem_op;
reg head_ctx_ref_0_o_ap_vld;
reg head_ctx_ref_1_o_ap_vld;
reg head_ctx_ref_2_o_ap_vld;
reg head_ctx_ref_3_o_ap_vld;
reg STATE_ap_vld;
reg dbg_ctrl_mem_ap_vld;
reg control_reg_ap_vld;
reg irq_status_reg_ap_vld;
reg irq_mask_reg_ap_vld;
reg irq_clear_reg_ap_vld;
reg wq_base_addr_ap_vld;
reg wk_base_addr_ap_vld;
reg wv_base_addr_ap_vld;
reg wo_base_addr_ap_vld;
reg w1_base_addr_ap_vld;
reg w2_base_addr_ap_vld;
reg wq_head_stride_ap_vld;
reg wk_head_stride_ap_vld;
reg wv_head_stride_ap_vld;
reg wo_tile_stride_ap_vld;
reg w1_tile_stride_ap_vld;
reg w2_tile_stride_ap_vld;
reg dbg_compute_start_ap_vld;
reg dbg_compute_instruction_ap_vld;
reg dbg_compute_ready_ap_vld;
reg dbg_compute_done_ap_vld;
reg dbg_compute_state_ap_vld;
reg dbg_req_instruction_ap_vld;
reg dbg_req_op_ap_vld;
reg dbg_req_layer_ap_vld;
reg dbg_req_head_ap_vld;
reg dbg_req_tile_ap_vld;
reg[0:0] dbg_mac_start;
reg[0:0] dbg_mac_ready;
reg[0:0] dbg_mac_complete;
reg dbg_ctrl_reset_asserted_ap_vld;
reg dbg_done_ap_vld;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [1279:0] ctrl_mem;
wire   [127:0] status_mem;
reg    status_mem_ap_vld;
reg   [0:0] compute_ready;
reg   [0:0] compute_done;
reg   [0:0] compute_start;
reg   [31:0] compute_instruction;
reg   [31:0] ctrl_mem_interface_status;
reg   [31:0] ctrl_mem_interface_irq_status;
reg   [31:0] ctrl_mem_interface_error_code;
reg   [31:0] ctrl_mem_interface_layer_index;
reg   [0:0] mem_transfer_done_read_reg_2796;
reg   [0:0] wl_ready_read_reg_2801;
reg   [0:0] dma_done_read_reg_2806;
reg   [1279:0] ctrl_mem_read_reg_2811;
reg   [0:0] stream_done_read_reg_2825;
reg   [0:0] stream_ready_read_reg_2830;
reg   [0:0] axis_in_last_read_reg_2835;
reg   [0:0] axis_in_valid_read_reg_2840;
wire   [31:0] ctrl_mem_control_fu_1764_p1;
reg   [31:0] ctrl_mem_control_reg_2845;
wire   [1:0] trunc_ln21_fu_1768_p1;
reg   [1:0] trunc_ln21_reg_2850;
wire   [0:0] trunc_ln21_1_fu_1772_p1;
reg   [0:0] trunc_ln21_1_reg_2855;
reg   [31:0] ctrl_mem_irq_mask_reg_2860;
reg   [31:0] ctrl_mem_irq_clear_reg_2865;
reg   [31:0] ctrl_mem_dma_head_len_reg_2871;
reg   [31:0] ctrl_mem_dma_tile_len_reg_2876;
reg   [31:0] ctrl_mem_layer_stride_reg_2881;
reg   [31:0] ctrl_mem_wq_head_stride_reg_2886;
reg   [31:0] ctrl_mem_wk_head_stride_reg_2892;
reg   [31:0] ctrl_mem_wv_head_stride_reg_2898;
reg   [31:0] ctrl_mem_k_cache_stride_reg_2904;
reg   [31:0] ctrl_mem_v_cache_stride_reg_2909;
reg   [31:0] ctrl_mem_wo_tile_stride_reg_2914;
reg   [31:0] ctrl_mem_w1_tile_stride_reg_2920;
reg   [31:0] ctrl_mem_w2_tile_stride_reg_2926;
reg   [5:0] ctrl_mem_wq_base_addr_cast2_reg_2932;
reg   [5:0] ctrl_mem_wk_base_addr_cast3_reg_2937;
reg   [5:0] ctrl_mem_wv_base_addr_cast4_reg_2942;
reg   [5:0] ctrl_mem_wo_base_addr_cast5_reg_2947;
reg   [5:0] ctrl_mem_w1_base_addr_cast6_reg_2952;
reg   [5:0] ctrl_mem_w2_base_addr_cast7_reg_2957;
reg   [5:0] ctrl_mem_k_cache_addr_cast8_reg_2962;
reg   [5:0] ctrl_mem_v_cache_addr_cast9_reg_2967;
wire   [0:0] xor_ln116_fu_1968_p2;
reg   [0:0] xor_ln116_reg_2972;
wire   [0:0] icmp_ln22_fu_1998_p2;
reg   [0:0] icmp_ln22_reg_2977;
reg   [0:0] compute_ready_load_reg_2981;
wire    ap_CS_fsm_state2;
reg   [0:0] compute_done_load_reg_2986;
reg   [0:0] wl_start_read_reg_2991;
reg   [213:0] head_ctx_ref_0_read_reg_2996;
reg   [213:0] head_ctx_ref_1_read_reg_3001;
reg   [213:0] head_ctx_ref_2_read_reg_3006;
reg   [213:0] head_ctx_ref_3_read_reg_3011;
reg   [0:0] done_reg_3016;
wire    ap_CS_fsm_state3;
reg   [0:0] scheduler_error_reg_3021;
reg   [0:0] compute_start_load_reg_3025;
wire    ap_CS_fsm_state4;
reg   [31:0] compute_instruction_load_reg_3030;
wire    grp_scheduler_hls_fu_1173_ap_start;
wire    grp_scheduler_hls_fu_1173_ap_done;
wire    grp_scheduler_hls_fu_1173_ap_idle;
wire    grp_scheduler_hls_fu_1173_ap_ready;
wire   [31:0] grp_scheduler_hls_fu_1173_wl_instruction;
wire    grp_scheduler_hls_fu_1173_wl_instruction_ap_vld;
wire   [31:0] grp_scheduler_hls_fu_1173_ctrl_mem_interface_status_o;
wire    grp_scheduler_hls_fu_1173_ctrl_mem_interface_status_o_ap_vld;
wire   [0:0] grp_scheduler_hls_fu_1173_compute_start_o;
wire    grp_scheduler_hls_fu_1173_compute_start_o_ap_vld;
wire   [31:0] grp_scheduler_hls_fu_1173_ctrl_mem_interface_layer_index;
wire    grp_scheduler_hls_fu_1173_ctrl_mem_interface_layer_index_ap_vld;
wire   [31:0] grp_scheduler_hls_fu_1173_compute_instruction;
wire    grp_scheduler_hls_fu_1173_compute_instruction_ap_vld;
wire   [0:0] grp_scheduler_hls_fu_1173_ap_return_0;
wire   [0:0] grp_scheduler_hls_fu_1173_ap_return_1;
wire   [0:0] grp_scheduler_hls_fu_1173_ap_return_2;
wire   [0:0] grp_scheduler_hls_fu_1173_ap_return_3;
wire   [0:0] grp_scheduler_hls_fu_1173_ap_return_4;
wire   [31:0] grp_scheduler_hls_fu_1173_ap_return_5;
wire   [213:0] grp_scheduler_hls_fu_1173_ap_return_6;
wire   [213:0] grp_scheduler_hls_fu_1173_ap_return_7;
wire   [213:0] grp_scheduler_hls_fu_1173_ap_return_8;
wire   [213:0] grp_scheduler_hls_fu_1173_ap_return_9;
wire    grp_compute_controller_fu_1306_ap_start;
wire    grp_compute_controller_fu_1306_ap_done;
wire    grp_compute_controller_fu_1306_ap_idle;
wire    grp_compute_controller_fu_1306_ap_ready;
wire   [0:0] grp_compute_controller_fu_1306_mem_read_request;
wire    grp_compute_controller_fu_1306_mem_read_request_ap_vld;
wire   [0:0] grp_compute_controller_fu_1306_mem_write_request;
wire    grp_compute_controller_fu_1306_mem_write_request_ap_vld;
wire   [31:0] grp_compute_controller_fu_1306_mem_op;
wire    grp_compute_controller_fu_1306_mem_op_ap_vld;
wire   [7:0] grp_compute_controller_fu_1306_in_buf_address0;
wire    grp_compute_controller_fu_1306_in_buf_ce0;
wire   [7:0] grp_compute_controller_fu_1306_in_buf_address1;
wire    grp_compute_controller_fu_1306_in_buf_ce1;
wire   [5:0] grp_compute_controller_fu_1306_out_buf_address0;
wire    grp_compute_controller_fu_1306_out_buf_ce0;
wire    grp_compute_controller_fu_1306_out_buf_we0;
wire   [7:0] grp_compute_controller_fu_1306_out_buf_d0;
wire   [5:0] grp_compute_controller_fu_1306_out_buf_address1;
wire    grp_compute_controller_fu_1306_out_buf_ce1;
wire    grp_compute_controller_fu_1306_out_buf_we1;
wire   [7:0] grp_compute_controller_fu_1306_out_buf_d1;
wire   [0:0] grp_compute_controller_fu_1306_dbg_mac_start;
wire    grp_compute_controller_fu_1306_dbg_mac_start_ap_vld;
wire   [0:0] grp_compute_controller_fu_1306_dbg_mac_ready;
wire    grp_compute_controller_fu_1306_dbg_mac_ready_ap_vld;
wire   [0:0] grp_compute_controller_fu_1306_dbg_mac_complete;
wire    grp_compute_controller_fu_1306_dbg_mac_complete_ap_vld;
wire   [0:0] grp_compute_controller_fu_1306_compute_done;
wire    grp_compute_controller_fu_1306_compute_done_ap_vld;
wire   [0:0] grp_compute_controller_fu_1306_compute_ready;
wire    grp_compute_controller_fu_1306_compute_ready_ap_vld;
wire   [7:0] grp_compute_controller_fu_1306_ap_return_0;
wire   [31:0] grp_compute_controller_fu_1306_ap_return_1;
wire   [7:0] grp_compute_controller_fu_1306_ap_return_2;
wire   [7:0] grp_compute_controller_fu_1306_ap_return_3;
wire   [7:0] grp_compute_controller_fu_1306_ap_return_4;
wire   [7:0] grp_compute_controller_fu_1306_ap_return_5;
wire   [0:0] grp_compute_controller_fu_1306_ap_return_6;
reg    grp_scheduler_hls_fu_1173_ap_start_reg;
reg   [31:0] wl_instruction_reg;
reg    grp_compute_controller_fu_1306_ap_start_reg;
wire    ap_CS_fsm_state5;
reg   [0:0] mem_read_request_reg;
reg   [0:0] mem_write_request_reg;
reg   [31:0] mem_op_reg;
reg   [0:0] dbg_mac_start_reg;
reg   [0:0] dbg_mac_ready_reg;
reg   [0:0] dbg_mac_complete_reg;
wire    ap_CS_fsm_state6;
wire   [0:0] or_ln22_fu_2103_p2;
wire   [0:0] irq_error_en_fu_2086_p3;
reg   [31:0] ap_sig_allocacmp_ctrl_mem_interface_status_load;
wire   [0:0] or_ln34_1_fu_2252_p2;
wire   [0:0] or_ln33_fu_2225_p2;
wire   [0:0] or_ln32_fu_2209_p2;
wire   [0:0] or_ln31_fu_2193_p2;
wire   [0:0] icmp_ln43_fu_2366_p2;
wire   [0:0] compute_error_fu_2082_p1;
wire   [31:0] or_ln_fu_2127_p4;
wire   [31:0] or_ln2_fu_2276_p4;
wire   [31:0] or_ln4_fu_2390_p4;
wire   [31:0] or_ln6_fu_2458_p4;
wire   [31:0] or_ln8_fu_2532_p4;
wire   [31:0] or_ln10_fu_2617_p4;
reg   [31:0] ap_sig_allocacmp_ctrl_mem_interface_irq_status_load_1;
reg   [31:0] ap_sig_allocacmp_ctrl_mem_interface_irq_status_load_2;
reg   [31:0] ap_sig_allocacmp_ctrl_mem_interface_irq_status_load_3;
reg   [31:0] ap_sig_allocacmp_ctrl_mem_interface_irq_status_load_4;
reg   [31:0] ap_sig_allocacmp_ctrl_mem_interface_irq_status_load_5;
reg   [31:0] ap_sig_allocacmp_ctrl_mem_interface_irq_status_load_6;
wire   [0:0] icmp_ln74_fu_2588_p2;
wire   [31:0] or_ln1_fu_2167_p4;
wire   [31:0] or_ln3_fu_2316_p4;
wire   [31:0] or_ln5_fu_2426_p3;
wire   [31:0] or_ln7_fu_2498_p4;
wire   [31:0] or_ln9_fu_2572_p4;
reg   [31:0] ap_sig_allocacmp_ctrl_mem_interface_error_code_load_1;
reg   [31:0] ap_sig_allocacmp_ctrl_mem_interface_error_code_load_2;
reg   [31:0] ap_sig_allocacmp_ctrl_mem_interface_error_code_load_3;
reg   [31:0] ap_sig_allocacmp_ctrl_mem_interface_error_code_load_4;
reg   [31:0] ap_sig_allocacmp_ctrl_mem_interface_error_code_load_5;
wire   [0:0] icmp_ln93_fu_2683_p2;
reg   [0:0] irq_ps_preg;
wire   [31:0] ctrl_mem_dma_layer_len_fu_1792_p3;
wire   [0:0] icmp_ln22_1_fu_2093_p2;
wire   [0:0] icmp_ln22_2_fu_2098_p2;
wire   [29:0] tmp_1_fu_2113_p4;
wire   [0:0] trunc_ln24_fu_2123_p1;
wire   [29:0] tmp_3_fu_2153_p4;
wire   [0:0] trunc_ln26_fu_2163_p1;
wire   [0:0] icmp_ln31_fu_2183_p2;
wire   [0:0] icmp_ln32_fu_2188_p2;
wire   [0:0] icmp_ln32_1_fu_2199_p2;
wire   [0:0] icmp_ln32_2_fu_2204_p2;
wire   [0:0] icmp_ln33_fu_2215_p2;
wire   [0:0] icmp_ln33_1_fu_2220_p2;
wire   [0:0] icmp_ln34_1_fu_2236_p2;
wire   [0:0] icmp_ln34_2_fu_2241_p2;
wire   [0:0] or_ln34_fu_2246_p2;
wire   [0:0] icmp_ln34_fu_2231_p2;
wire   [29:0] tmp_5_fu_2262_p4;
wire   [0:0] trunc_ln36_fu_2272_p1;
wire   [28:0] tmp_7_fu_2302_p4;
wire   [1:0] trunc_ln38_fu_2312_p1;
wire   [5:0] or_ln43_1_fu_2336_p2;
wire   [5:0] or_ln43_fu_2332_p2;
wire   [5:0] or_ln43_4_fu_2350_p2;
wire   [5:0] or_ln43_3_fu_2346_p2;
wire   [5:0] or_ln43_5_fu_2354_p2;
wire   [5:0] or_ln43_2_fu_2340_p2;
wire   [5:0] or_ln43_6_fu_2360_p2;
wire   [29:0] tmp_9_fu_2376_p4;
wire   [0:0] trunc_ln48_fu_2386_p1;
wire   [30:0] tmp_s_fu_2416_p4;
wire   [29:0] tmp_2_fu_2444_p4;
wire   [0:0] trunc_ln56_fu_2454_p1;
wire   [27:0] tmp_4_fu_2484_p4;
wire   [2:0] trunc_ln58_fu_2494_p1;
wire   [29:0] tmp_6_fu_2518_p4;
wire   [0:0] trunc_ln63_fu_2528_p1;
wire   [26:0] tmp_8_fu_2558_p4;
wire   [3:0] trunc_ln65_fu_2568_p1;
wire   [28:0] tmp_10_fu_2603_p4;
wire   [1:0] trunc_ln77_fu_2613_p1;
wire   [1:0] tmp_11_fu_2660_p4;
wire   [2:0] and_ln_fu_2669_p3;
wire   [2:0] trunc_ln93_fu_2656_p1;
wire   [2:0] and_ln93_fu_2677_p2;
wire   [735:0] tmp_fu_2715_p4;
wire   [479:0] trunc_ln195_fu_2724_p1;
reg   [5:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_condition_1045;
reg    ap_condition_1063;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
#0 compute_ready = 1'd0;
#0 compute_done = 1'd0;
#0 compute_start = 1'd0;
#0 compute_instruction = 32'd0;
#0 ctrl_mem_interface_status = 32'd1;
#0 ctrl_mem_interface_irq_status = 32'd0;
#0 ctrl_mem_interface_error_code = 32'd0;
#0 ctrl_mem_interface_layer_index = 32'd0;
#0 grp_scheduler_hls_fu_1173_ap_start_reg = 1'b0;
#0 grp_compute_controller_fu_1306_ap_start_reg = 1'b0;
#0 irq_ps_preg = 1'd0;
end

transformer_top_scheduler_hls grp_scheduler_hls_fu_1173(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_scheduler_hls_fu_1173_ap_start),
    .ap_done(grp_scheduler_hls_fu_1173_ap_done),
    .ap_idle(grp_scheduler_hls_fu_1173_ap_idle),
    .ap_ready(grp_scheduler_hls_fu_1173_ap_ready),
    .ctrl_mem_control(trunc_ln21_reg_2850),
    .axis_in_valid(axis_in_valid_read_reg_2840),
    .axis_in_last(axis_in_last_read_reg_2835),
    .dma_done(dma_done_read_reg_2806),
    .wl_ready(wl_ready_read_reg_2801),
    .wl_instruction(grp_scheduler_hls_fu_1173_wl_instruction),
    .wl_instruction_ap_vld(grp_scheduler_hls_fu_1173_wl_instruction_ap_vld),
    .wl_start_read(wl_start_read_reg_2991),
    .compute_ready(compute_ready_load_reg_2981),
    .compute_done(compute_done_load_reg_2986),
    .p_read1(head_ctx_ref_0_read_reg_2996),
    .p_read2(head_ctx_ref_1_read_reg_3001),
    .p_read3(head_ctx_ref_2_read_reg_3006),
    .p_read4(head_ctx_ref_3_read_reg_3011),
    .stream_ready(stream_ready_read_reg_2830),
    .stream_done(stream_done_read_reg_2825),
    .ctrl_mem_interface_status_i(ctrl_mem_interface_status),
    .ctrl_mem_interface_status_o(grp_scheduler_hls_fu_1173_ctrl_mem_interface_status_o),
    .ctrl_mem_interface_status_o_ap_vld(grp_scheduler_hls_fu_1173_ctrl_mem_interface_status_o_ap_vld),
    .ctrl_mem_interface_irq_status(ctrl_mem_interface_irq_status),
    .ctrl_mem_interface_error_code(ctrl_mem_interface_error_code),
    .compute_start_i(compute_start),
    .compute_start_o(grp_scheduler_hls_fu_1173_compute_start_o),
    .compute_start_o_ap_vld(grp_scheduler_hls_fu_1173_compute_start_o_ap_vld),
    .ctrl_mem_interface_layer_index(grp_scheduler_hls_fu_1173_ctrl_mem_interface_layer_index),
    .ctrl_mem_interface_layer_index_ap_vld(grp_scheduler_hls_fu_1173_ctrl_mem_interface_layer_index_ap_vld),
    .compute_instruction(grp_scheduler_hls_fu_1173_compute_instruction),
    .compute_instruction_ap_vld(grp_scheduler_hls_fu_1173_compute_instruction_ap_vld),
    .ap_return_0(grp_scheduler_hls_fu_1173_ap_return_0),
    .ap_return_1(grp_scheduler_hls_fu_1173_ap_return_1),
    .ap_return_2(grp_scheduler_hls_fu_1173_ap_return_2),
    .ap_return_3(grp_scheduler_hls_fu_1173_ap_return_3),
    .ap_return_4(grp_scheduler_hls_fu_1173_ap_return_4),
    .ap_return_5(grp_scheduler_hls_fu_1173_ap_return_5),
    .ap_return_6(grp_scheduler_hls_fu_1173_ap_return_6),
    .ap_return_7(grp_scheduler_hls_fu_1173_ap_return_7),
    .ap_return_8(grp_scheduler_hls_fu_1173_ap_return_8),
    .ap_return_9(grp_scheduler_hls_fu_1173_ap_return_9)
);

transformer_top_compute_controller grp_compute_controller_fu_1306(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_compute_controller_fu_1306_ap_start),
    .ap_done(grp_compute_controller_fu_1306_ap_done),
    .ap_idle(grp_compute_controller_fu_1306_ap_idle),
    .ap_ready(grp_compute_controller_fu_1306_ap_ready),
    .ctrl_mem_control(trunc_ln21_1_reg_2855),
    .compute_start(compute_start_load_reg_3025),
    .compute_instruction(compute_instruction_load_reg_3030),
    .mem_transfer_done(mem_transfer_done_read_reg_2796),
    .mem_read_request(grp_compute_controller_fu_1306_mem_read_request),
    .mem_read_request_ap_vld(grp_compute_controller_fu_1306_mem_read_request_ap_vld),
    .mem_write_request(grp_compute_controller_fu_1306_mem_write_request),
    .mem_write_request_ap_vld(grp_compute_controller_fu_1306_mem_write_request_ap_vld),
    .mem_op(grp_compute_controller_fu_1306_mem_op),
    .mem_op_ap_vld(grp_compute_controller_fu_1306_mem_op_ap_vld),
    .in_buf_address0(grp_compute_controller_fu_1306_in_buf_address0),
    .in_buf_ce0(grp_compute_controller_fu_1306_in_buf_ce0),
    .in_buf_q0(in_buf_q0),
    .in_buf_address1(grp_compute_controller_fu_1306_in_buf_address1),
    .in_buf_ce1(grp_compute_controller_fu_1306_in_buf_ce1),
    .in_buf_q1(in_buf_q1),
    .out_buf_address0(grp_compute_controller_fu_1306_out_buf_address0),
    .out_buf_ce0(grp_compute_controller_fu_1306_out_buf_ce0),
    .out_buf_we0(grp_compute_controller_fu_1306_out_buf_we0),
    .out_buf_d0(grp_compute_controller_fu_1306_out_buf_d0),
    .out_buf_address1(grp_compute_controller_fu_1306_out_buf_address1),
    .out_buf_ce1(grp_compute_controller_fu_1306_out_buf_ce1),
    .out_buf_we1(grp_compute_controller_fu_1306_out_buf_we1),
    .out_buf_d1(grp_compute_controller_fu_1306_out_buf_d1),
    .dbg_mac_start(grp_compute_controller_fu_1306_dbg_mac_start),
    .dbg_mac_start_ap_vld(grp_compute_controller_fu_1306_dbg_mac_start_ap_vld),
    .dbg_mac_ready(grp_compute_controller_fu_1306_dbg_mac_ready),
    .dbg_mac_ready_ap_vld(grp_compute_controller_fu_1306_dbg_mac_ready_ap_vld),
    .dbg_mac_complete(grp_compute_controller_fu_1306_dbg_mac_complete),
    .dbg_mac_complete_ap_vld(grp_compute_controller_fu_1306_dbg_mac_complete_ap_vld),
    .compute_done(grp_compute_controller_fu_1306_compute_done),
    .compute_done_ap_vld(grp_compute_controller_fu_1306_compute_done_ap_vld),
    .compute_ready(grp_compute_controller_fu_1306_compute_ready),
    .compute_ready_ap_vld(grp_compute_controller_fu_1306_compute_ready_ap_vld),
    .ap_return_0(grp_compute_controller_fu_1306_ap_return_0),
    .ap_return_1(grp_compute_controller_fu_1306_ap_return_1),
    .ap_return_2(grp_compute_controller_fu_1306_ap_return_2),
    .ap_return_3(grp_compute_controller_fu_1306_ap_return_3),
    .ap_return_4(grp_compute_controller_fu_1306_ap_return_4),
    .ap_return_5(grp_compute_controller_fu_1306_ap_return_5),
    .ap_return_6(grp_compute_controller_fu_1306_ap_return_6)
);

transformer_top_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ctrl_mem(ctrl_mem),
    .status_mem(status_mem),
    .status_mem_ap_vld(status_mem_ap_vld),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_compute_controller_fu_1306_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_compute_controller_fu_1306_ap_start_reg <= 1'b1;
        end else if ((grp_compute_controller_fu_1306_ap_ready == 1'b1)) begin
            grp_compute_controller_fu_1306_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_scheduler_hls_fu_1173_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_scheduler_hls_fu_1173_ap_start_reg <= 1'b1;
        end else if ((grp_scheduler_hls_fu_1173_ap_ready == 1'b1)) begin
            grp_scheduler_hls_fu_1173_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        irq_ps_preg <= 1'd0;
    end else begin
        if (((grp_compute_controller_fu_1306_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
            irq_ps_preg <= icmp_ln93_fu_2683_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (trunc_ln21_1_fu_1772_p1 == 1'd0) & (ap_start == 1'b1))) begin
        compute_done <= 1'd0;
    end else if (((grp_compute_controller_fu_1306_compute_done_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        compute_done <= grp_compute_controller_fu_1306_compute_done;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (trunc_ln21_1_fu_1772_p1 == 1'd0) & (ap_start == 1'b1))) begin
        compute_instruction <= 32'd0;
    end else if (((grp_scheduler_hls_fu_1173_compute_instruction_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        compute_instruction <= grp_scheduler_hls_fu_1173_compute_instruction;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (trunc_ln21_1_fu_1772_p1 == 1'd0) & (ap_start == 1'b1))) begin
        compute_ready <= 1'd1;
    end else if (((grp_compute_controller_fu_1306_compute_ready_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        compute_ready <= grp_compute_controller_fu_1306_compute_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (trunc_ln21_1_fu_1772_p1 == 1'd0) & (ap_start == 1'b1))) begin
        compute_start <= 1'd0;
    end else if (((grp_scheduler_hls_fu_1173_compute_start_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        compute_start <= grp_scheduler_hls_fu_1173_compute_start_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_compute_controller_fu_1306_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        if ((trunc_ln21_1_reg_2855 == 1'd0)) begin
            ctrl_mem_interface_error_code <= 32'd0;
        end else if (((compute_error_fu_2082_p1 == 1'd1) & (irq_error_en_fu_2086_p3 == 1'd1))) begin
            ctrl_mem_interface_error_code <= or_ln9_fu_2572_p4;
        end else if (((scheduler_error_reg_3021 == 1'd1) & (irq_error_en_fu_2086_p3 == 1'd1))) begin
            ctrl_mem_interface_error_code <= or_ln7_fu_2498_p4;
        end else if (((icmp_ln43_fu_2366_p2 == 1'd0) & (irq_error_en_fu_2086_p3 == 1'd1))) begin
            ctrl_mem_interface_error_code <= or_ln5_fu_2426_p3;
        end else if ((1'b1 == ap_condition_1063)) begin
            ctrl_mem_interface_error_code <= or_ln3_fu_2316_p4;
        end else if ((1'b1 == ap_condition_1045)) begin
            ctrl_mem_interface_error_code <= or_ln1_fu_2167_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((grp_compute_controller_fu_1306_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        if ((trunc_ln21_1_reg_2855 == 1'd0)) begin
            ctrl_mem_interface_irq_status <= 32'd0;
        end else if (((done_reg_3016 == 1'd1) & (icmp_ln74_fu_2588_p2 == 1'd1))) begin
            ctrl_mem_interface_irq_status <= or_ln10_fu_2617_p4;
        end else if ((icmp_ln74_fu_2588_p2 == 1'd0)) begin
            ctrl_mem_interface_irq_status <= 32'd0;
        end else if (((compute_error_fu_2082_p1 == 1'd1) & (irq_error_en_fu_2086_p3 == 1'd1))) begin
            ctrl_mem_interface_irq_status <= or_ln8_fu_2532_p4;
        end else if (((scheduler_error_reg_3021 == 1'd1) & (irq_error_en_fu_2086_p3 == 1'd1))) begin
            ctrl_mem_interface_irq_status <= or_ln6_fu_2458_p4;
        end else if (((icmp_ln43_fu_2366_p2 == 1'd0) & (irq_error_en_fu_2086_p3 == 1'd1))) begin
            ctrl_mem_interface_irq_status <= or_ln4_fu_2390_p4;
        end else if ((1'b1 == ap_condition_1063)) begin
            ctrl_mem_interface_irq_status <= or_ln2_fu_2276_p4;
        end else if ((1'b1 == ap_condition_1045)) begin
            ctrl_mem_interface_irq_status <= or_ln_fu_2127_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((grp_compute_controller_fu_1306_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5) & (trunc_ln21_1_reg_2855 == 1'd0))) begin
        ctrl_mem_interface_status <= 32'd1;
    end else if ((((grp_compute_controller_fu_1306_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5) & (compute_error_fu_2082_p1 == 1'd1) & (irq_error_en_fu_2086_p3 == 1'd1)) | ((grp_compute_controller_fu_1306_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5) & (icmp_ln43_fu_2366_p2 == 1'd0) & (irq_error_en_fu_2086_p3 == 1'd1)) | ((grp_compute_controller_fu_1306_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5) & (((((or_ln33_fu_2225_p2 == 1'd1) & (irq_error_en_fu_2086_p3 == 1'd1)) | ((or_ln34_1_fu_2252_p2 == 1'd1) & (irq_error_en_fu_2086_p3 == 1'd1))) | ((or_ln32_fu_2209_p2 == 1'd1) & (irq_error_en_fu_2086_p3 == 1'd1))) | ((or_ln31_fu_2193_p2 == 1'd1) & (irq_error_en_fu_2086_p3 == 1'd1)))) | ((grp_compute_controller_fu_1306_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5) & (((icmp_ln22_reg_2977 == 1'd1) & (irq_error_en_fu_2086_p3 == 1'd1)) | ((irq_error_en_fu_2086_p3 == 1'd1) & (or_ln22_fu_2103_p2 == 1'd1)))) | ((grp_compute_controller_fu_1306_ap_done == 1'b1) & (scheduler_error_reg_3021 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (irq_error_en_fu_2086_p3 
    == 1'd1)))) begin
        ctrl_mem_interface_status <= 32'd2;
    end else if (((grp_scheduler_hls_fu_1173_ctrl_mem_interface_status_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        ctrl_mem_interface_status <= grp_scheduler_hls_fu_1173_ctrl_mem_interface_status_o;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        axis_in_last_read_reg_2835 <= axis_in_last;
        axis_in_valid_read_reg_2840 <= axis_in_valid;
        ctrl_mem_control_reg_2845 <= ctrl_mem_control_fu_1764_p1;
        ctrl_mem_dma_head_len_reg_2871 <= {{ctrl_mem[159:128]}};
        ctrl_mem_dma_tile_len_reg_2876 <= {{ctrl_mem[191:160]}};
        ctrl_mem_irq_clear_reg_2865 <= {{ctrl_mem[95:64]}};
        ctrl_mem_irq_mask_reg_2860 <= {{ctrl_mem[63:32]}};
        ctrl_mem_k_cache_addr_cast8_reg_2962 <= {{ctrl_mem[901:896]}};
        ctrl_mem_k_cache_stride_reg_2904 <= {{ctrl_mem[351:320]}};
        ctrl_mem_layer_stride_reg_2881 <= {{ctrl_mem[223:192]}};
        ctrl_mem_read_reg_2811 <= ctrl_mem;
        ctrl_mem_v_cache_addr_cast9_reg_2967 <= {{ctrl_mem[965:960]}};
        ctrl_mem_v_cache_stride_reg_2909 <= {{ctrl_mem[383:352]}};
        ctrl_mem_w1_base_addr_cast6_reg_2952 <= {{ctrl_mem[773:768]}};
        ctrl_mem_w1_tile_stride_reg_2920 <= {{ctrl_mem[447:416]}};
        ctrl_mem_w2_base_addr_cast7_reg_2957 <= {{ctrl_mem[837:832]}};
        ctrl_mem_w2_tile_stride_reg_2926 <= {{ctrl_mem[479:448]}};
        ctrl_mem_wk_base_addr_cast3_reg_2937 <= {{ctrl_mem[581:576]}};
        ctrl_mem_wk_head_stride_reg_2892 <= {{ctrl_mem[287:256]}};
        ctrl_mem_wo_base_addr_cast5_reg_2947 <= {{ctrl_mem[709:704]}};
        ctrl_mem_wo_tile_stride_reg_2914 <= {{ctrl_mem[415:384]}};
        ctrl_mem_wq_base_addr_cast2_reg_2932 <= {{ctrl_mem[517:512]}};
        ctrl_mem_wq_head_stride_reg_2886 <= {{ctrl_mem[255:224]}};
        ctrl_mem_wv_base_addr_cast4_reg_2942 <= {{ctrl_mem[645:640]}};
        ctrl_mem_wv_head_stride_reg_2898 <= {{ctrl_mem[319:288]}};
        dma_done_read_reg_2806 <= dma_done;
        icmp_ln22_reg_2977 <= icmp_ln22_fu_1998_p2;
        mem_transfer_done_read_reg_2796 <= mem_transfer_done;
        stream_done_read_reg_2825 <= stream_done;
        stream_ready_read_reg_2830 <= stream_ready;
        trunc_ln21_1_reg_2855 <= trunc_ln21_1_fu_1772_p1;
        trunc_ln21_reg_2850 <= trunc_ln21_fu_1768_p1;
        wl_ready_read_reg_2801 <= wl_ready;
        xor_ln116_reg_2972 <= xor_ln116_fu_1968_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        compute_done_load_reg_2986 <= compute_done;
        compute_ready_load_reg_2981 <= compute_ready;
        head_ctx_ref_0_read_reg_2996 <= head_ctx_ref_0_i;
        head_ctx_ref_1_read_reg_3001 <= head_ctx_ref_1_i;
        head_ctx_ref_2_read_reg_3006 <= head_ctx_ref_2_i;
        head_ctx_ref_3_read_reg_3011 <= head_ctx_ref_3_i;
        wl_start_read_reg_2991 <= wl_start_i;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        compute_instruction_load_reg_3030 <= compute_instruction;
        compute_start_load_reg_3025 <= compute_start;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_scheduler_hls_fu_1173_ctrl_mem_interface_layer_index_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        ctrl_mem_interface_layer_index <= grp_scheduler_hls_fu_1173_ctrl_mem_interface_layer_index;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_compute_controller_fu_1306_dbg_mac_complete_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        dbg_mac_complete_reg <= grp_compute_controller_fu_1306_dbg_mac_complete;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_compute_controller_fu_1306_dbg_mac_ready_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        dbg_mac_ready_reg <= grp_compute_controller_fu_1306_dbg_mac_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_compute_controller_fu_1306_dbg_mac_start_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        dbg_mac_start_reg <= grp_compute_controller_fu_1306_dbg_mac_start;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        done_reg_3016 <= grp_scheduler_hls_fu_1173_ap_return_3;
        scheduler_error_reg_3021 <= grp_scheduler_hls_fu_1173_ap_return_4;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_compute_controller_fu_1306_mem_op_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        mem_op_reg <= grp_compute_controller_fu_1306_mem_op;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_compute_controller_fu_1306_mem_read_request_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        mem_read_request_reg <= grp_compute_controller_fu_1306_mem_read_request;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_compute_controller_fu_1306_mem_write_request_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        mem_write_request_reg <= grp_compute_controller_fu_1306_mem_write_request;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_scheduler_hls_fu_1173_wl_instruction_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        wl_instruction_reg <= grp_scheduler_hls_fu_1173_wl_instruction;
    end
end

always @ (*) begin
    if (((grp_scheduler_hls_fu_1173_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        STATE_ap_vld = 1'b1;
    end else begin
        STATE_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_scheduler_hls_fu_1173_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_compute_controller_fu_1306_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (((icmp_ln22_reg_2977 == 1'd1) & (irq_error_en_fu_2086_p3 == 1'd1)) | ((irq_error_en_fu_2086_p3 == 1'd1) & (or_ln22_fu_2103_p2 == 1'd1))))) begin
        ap_sig_allocacmp_ctrl_mem_interface_error_code_load_1 = or_ln1_fu_2167_p4;
    end else begin
        ap_sig_allocacmp_ctrl_mem_interface_error_code_load_1 = ctrl_mem_interface_error_code;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        if ((1'b1 == ap_condition_1063)) begin
            ap_sig_allocacmp_ctrl_mem_interface_error_code_load_2 = or_ln3_fu_2316_p4;
        end else if ((1'b1 == ap_condition_1045)) begin
            ap_sig_allocacmp_ctrl_mem_interface_error_code_load_2 = or_ln1_fu_2167_p4;
        end else begin
            ap_sig_allocacmp_ctrl_mem_interface_error_code_load_2 = ctrl_mem_interface_error_code;
        end
    end else begin
        ap_sig_allocacmp_ctrl_mem_interface_error_code_load_2 = ctrl_mem_interface_error_code;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        if (((icmp_ln43_fu_2366_p2 == 1'd0) & (irq_error_en_fu_2086_p3 == 1'd1))) begin
            ap_sig_allocacmp_ctrl_mem_interface_error_code_load_3 = or_ln5_fu_2426_p3;
        end else if ((1'b1 == ap_condition_1063)) begin
            ap_sig_allocacmp_ctrl_mem_interface_error_code_load_3 = or_ln3_fu_2316_p4;
        end else if ((1'b1 == ap_condition_1045)) begin
            ap_sig_allocacmp_ctrl_mem_interface_error_code_load_3 = or_ln1_fu_2167_p4;
        end else begin
            ap_sig_allocacmp_ctrl_mem_interface_error_code_load_3 = ctrl_mem_interface_error_code;
        end
    end else begin
        ap_sig_allocacmp_ctrl_mem_interface_error_code_load_3 = ctrl_mem_interface_error_code;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        if (((scheduler_error_reg_3021 == 1'd1) & (irq_error_en_fu_2086_p3 == 1'd1))) begin
            ap_sig_allocacmp_ctrl_mem_interface_error_code_load_4 = or_ln7_fu_2498_p4;
        end else if (((icmp_ln43_fu_2366_p2 == 1'd0) & (irq_error_en_fu_2086_p3 == 1'd1))) begin
            ap_sig_allocacmp_ctrl_mem_interface_error_code_load_4 = or_ln5_fu_2426_p3;
        end else if ((1'b1 == ap_condition_1063)) begin
            ap_sig_allocacmp_ctrl_mem_interface_error_code_load_4 = or_ln3_fu_2316_p4;
        end else if ((1'b1 == ap_condition_1045)) begin
            ap_sig_allocacmp_ctrl_mem_interface_error_code_load_4 = or_ln1_fu_2167_p4;
        end else begin
            ap_sig_allocacmp_ctrl_mem_interface_error_code_load_4 = ctrl_mem_interface_error_code;
        end
    end else begin
        ap_sig_allocacmp_ctrl_mem_interface_error_code_load_4 = ctrl_mem_interface_error_code;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        if ((trunc_ln21_1_reg_2855 == 1'd0)) begin
            ap_sig_allocacmp_ctrl_mem_interface_error_code_load_5 = 32'd0;
        end else if (((compute_error_fu_2082_p1 == 1'd1) & (irq_error_en_fu_2086_p3 == 1'd1))) begin
            ap_sig_allocacmp_ctrl_mem_interface_error_code_load_5 = or_ln9_fu_2572_p4;
        end else if (((scheduler_error_reg_3021 == 1'd1) & (irq_error_en_fu_2086_p3 == 1'd1))) begin
            ap_sig_allocacmp_ctrl_mem_interface_error_code_load_5 = or_ln7_fu_2498_p4;
        end else if (((icmp_ln43_fu_2366_p2 == 1'd0) & (irq_error_en_fu_2086_p3 == 1'd1))) begin
            ap_sig_allocacmp_ctrl_mem_interface_error_code_load_5 = or_ln5_fu_2426_p3;
        end else if ((1'b1 == ap_condition_1063)) begin
            ap_sig_allocacmp_ctrl_mem_interface_error_code_load_5 = or_ln3_fu_2316_p4;
        end else if ((1'b1 == ap_condition_1045)) begin
            ap_sig_allocacmp_ctrl_mem_interface_error_code_load_5 = or_ln1_fu_2167_p4;
        end else begin
            ap_sig_allocacmp_ctrl_mem_interface_error_code_load_5 = ctrl_mem_interface_error_code;
        end
    end else begin
        ap_sig_allocacmp_ctrl_mem_interface_error_code_load_5 = ctrl_mem_interface_error_code;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (((icmp_ln22_reg_2977 == 1'd1) & (irq_error_en_fu_2086_p3 == 1'd1)) | ((irq_error_en_fu_2086_p3 == 1'd1) & (or_ln22_fu_2103_p2 == 1'd1))))) begin
        ap_sig_allocacmp_ctrl_mem_interface_irq_status_load_1 = or_ln_fu_2127_p4;
    end else begin
        ap_sig_allocacmp_ctrl_mem_interface_irq_status_load_1 = ctrl_mem_interface_irq_status;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        if ((1'b1 == ap_condition_1063)) begin
            ap_sig_allocacmp_ctrl_mem_interface_irq_status_load_2 = or_ln2_fu_2276_p4;
        end else if ((1'b1 == ap_condition_1045)) begin
            ap_sig_allocacmp_ctrl_mem_interface_irq_status_load_2 = or_ln_fu_2127_p4;
        end else begin
            ap_sig_allocacmp_ctrl_mem_interface_irq_status_load_2 = ctrl_mem_interface_irq_status;
        end
    end else begin
        ap_sig_allocacmp_ctrl_mem_interface_irq_status_load_2 = ctrl_mem_interface_irq_status;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        if (((icmp_ln43_fu_2366_p2 == 1'd0) & (irq_error_en_fu_2086_p3 == 1'd1))) begin
            ap_sig_allocacmp_ctrl_mem_interface_irq_status_load_3 = or_ln4_fu_2390_p4;
        end else if ((1'b1 == ap_condition_1063)) begin
            ap_sig_allocacmp_ctrl_mem_interface_irq_status_load_3 = or_ln2_fu_2276_p4;
        end else if ((1'b1 == ap_condition_1045)) begin
            ap_sig_allocacmp_ctrl_mem_interface_irq_status_load_3 = or_ln_fu_2127_p4;
        end else begin
            ap_sig_allocacmp_ctrl_mem_interface_irq_status_load_3 = ctrl_mem_interface_irq_status;
        end
    end else begin
        ap_sig_allocacmp_ctrl_mem_interface_irq_status_load_3 = ctrl_mem_interface_irq_status;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        if (((scheduler_error_reg_3021 == 1'd1) & (irq_error_en_fu_2086_p3 == 1'd1))) begin
            ap_sig_allocacmp_ctrl_mem_interface_irq_status_load_4 = or_ln6_fu_2458_p4;
        end else if (((icmp_ln43_fu_2366_p2 == 1'd0) & (irq_error_en_fu_2086_p3 == 1'd1))) begin
            ap_sig_allocacmp_ctrl_mem_interface_irq_status_load_4 = or_ln4_fu_2390_p4;
        end else if ((1'b1 == ap_condition_1063)) begin
            ap_sig_allocacmp_ctrl_mem_interface_irq_status_load_4 = or_ln2_fu_2276_p4;
        end else if ((1'b1 == ap_condition_1045)) begin
            ap_sig_allocacmp_ctrl_mem_interface_irq_status_load_4 = or_ln_fu_2127_p4;
        end else begin
            ap_sig_allocacmp_ctrl_mem_interface_irq_status_load_4 = ctrl_mem_interface_irq_status;
        end
    end else begin
        ap_sig_allocacmp_ctrl_mem_interface_irq_status_load_4 = ctrl_mem_interface_irq_status;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        if (((compute_error_fu_2082_p1 == 1'd1) & (irq_error_en_fu_2086_p3 == 1'd1))) begin
            ap_sig_allocacmp_ctrl_mem_interface_irq_status_load_5 = or_ln8_fu_2532_p4;
        end else if (((scheduler_error_reg_3021 == 1'd1) & (irq_error_en_fu_2086_p3 == 1'd1))) begin
            ap_sig_allocacmp_ctrl_mem_interface_irq_status_load_5 = or_ln6_fu_2458_p4;
        end else if (((icmp_ln43_fu_2366_p2 == 1'd0) & (irq_error_en_fu_2086_p3 == 1'd1))) begin
            ap_sig_allocacmp_ctrl_mem_interface_irq_status_load_5 = or_ln4_fu_2390_p4;
        end else if ((1'b1 == ap_condition_1063)) begin
            ap_sig_allocacmp_ctrl_mem_interface_irq_status_load_5 = or_ln2_fu_2276_p4;
        end else if ((1'b1 == ap_condition_1045)) begin
            ap_sig_allocacmp_ctrl_mem_interface_irq_status_load_5 = or_ln_fu_2127_p4;
        end else begin
            ap_sig_allocacmp_ctrl_mem_interface_irq_status_load_5 = ctrl_mem_interface_irq_status;
        end
    end else begin
        ap_sig_allocacmp_ctrl_mem_interface_irq_status_load_5 = ctrl_mem_interface_irq_status;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        if ((trunc_ln21_1_reg_2855 == 1'd0)) begin
            ap_sig_allocacmp_ctrl_mem_interface_irq_status_load_6 = 32'd0;
        end else if (((done_reg_3016 == 1'd1) & (icmp_ln74_fu_2588_p2 == 1'd1))) begin
            ap_sig_allocacmp_ctrl_mem_interface_irq_status_load_6 = or_ln10_fu_2617_p4;
        end else if ((icmp_ln74_fu_2588_p2 == 1'd0)) begin
            ap_sig_allocacmp_ctrl_mem_interface_irq_status_load_6 = 32'd0;
        end else if (((compute_error_fu_2082_p1 == 1'd1) & (irq_error_en_fu_2086_p3 == 1'd1))) begin
            ap_sig_allocacmp_ctrl_mem_interface_irq_status_load_6 = or_ln8_fu_2532_p4;
        end else if (((scheduler_error_reg_3021 == 1'd1) & (irq_error_en_fu_2086_p3 == 1'd1))) begin
            ap_sig_allocacmp_ctrl_mem_interface_irq_status_load_6 = or_ln6_fu_2458_p4;
        end else if (((icmp_ln43_fu_2366_p2 == 1'd0) & (irq_error_en_fu_2086_p3 == 1'd1))) begin
            ap_sig_allocacmp_ctrl_mem_interface_irq_status_load_6 = or_ln4_fu_2390_p4;
        end else if ((1'b1 == ap_condition_1063)) begin
            ap_sig_allocacmp_ctrl_mem_interface_irq_status_load_6 = or_ln2_fu_2276_p4;
        end else if ((1'b1 == ap_condition_1045)) begin
            ap_sig_allocacmp_ctrl_mem_interface_irq_status_load_6 = or_ln_fu_2127_p4;
        end else begin
            ap_sig_allocacmp_ctrl_mem_interface_irq_status_load_6 = ctrl_mem_interface_irq_status;
        end
    end else begin
        ap_sig_allocacmp_ctrl_mem_interface_irq_status_load_6 = ctrl_mem_interface_irq_status;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (trunc_ln21_1_reg_2855 == 1'd0))) begin
        ap_sig_allocacmp_ctrl_mem_interface_status_load = 32'd1;
    end else if ((((1'b1 == ap_CS_fsm_state5) & (compute_error_fu_2082_p1 == 1'd1) & (irq_error_en_fu_2086_p3 == 1'd1)) | ((1'b1 == ap_CS_fsm_state5) & (icmp_ln43_fu_2366_p2 == 1'd0) & (irq_error_en_fu_2086_p3 == 1'd1)) | ((1'b1 == ap_CS_fsm_state5) & (((((or_ln33_fu_2225_p2 == 1'd1) & (irq_error_en_fu_2086_p3 == 1'd1)) | ((or_ln34_1_fu_2252_p2 == 1'd1) & (irq_error_en_fu_2086_p3 == 1'd1))) | ((or_ln32_fu_2209_p2 == 1'd1) & (irq_error_en_fu_2086_p3 == 1'd1))) | ((or_ln31_fu_2193_p2 == 1'd1) & (irq_error_en_fu_2086_p3 == 1'd1)))) | ((1'b1 == ap_CS_fsm_state5) & (((icmp_ln22_reg_2977 == 1'd1) & (irq_error_en_fu_2086_p3 == 1'd1)) | ((irq_error_en_fu_2086_p3 == 1'd1) & (or_ln22_fu_2103_p2 == 1'd1)))) | ((scheduler_error_reg_3021 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (irq_error_en_fu_2086_p3 == 1'd1)))) begin
        ap_sig_allocacmp_ctrl_mem_interface_status_load = 32'd2;
    end else begin
        ap_sig_allocacmp_ctrl_mem_interface_status_load = ctrl_mem_interface_status;
    end
end

always @ (*) begin
    if (((grp_scheduler_hls_fu_1173_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        axis_in_ready_ap_vld = 1'b1;
    end else begin
        axis_in_ready_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((grp_compute_controller_fu_1306_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        control_reg_ap_vld = 1'b1;
    end else begin
        control_reg_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        dbg_compute_done_ap_vld = 1'b1;
    end else begin
        dbg_compute_done_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        dbg_compute_instruction_ap_vld = 1'b1;
    end else begin
        dbg_compute_instruction_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        dbg_compute_ready_ap_vld = 1'b1;
    end else begin
        dbg_compute_ready_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        dbg_compute_start_ap_vld = 1'b1;
    end else begin
        dbg_compute_start_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((grp_compute_controller_fu_1306_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        dbg_compute_state_ap_vld = 1'b1;
    end else begin
        dbg_compute_state_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((grp_compute_controller_fu_1306_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        dbg_ctrl_mem_ap_vld = 1'b1;
    end else begin
        dbg_ctrl_mem_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((grp_compute_controller_fu_1306_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        dbg_ctrl_reset_asserted_ap_vld = 1'b1;
    end else begin
        dbg_ctrl_reset_asserted_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((grp_compute_controller_fu_1306_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        dbg_done_ap_vld = 1'b1;
    end else begin
        dbg_done_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((grp_compute_controller_fu_1306_dbg_mac_complete_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        dbg_mac_complete = grp_compute_controller_fu_1306_dbg_mac_complete;
    end else begin
        dbg_mac_complete = dbg_mac_complete_reg;
    end
end

always @ (*) begin
    if (((grp_compute_controller_fu_1306_dbg_mac_ready_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        dbg_mac_ready = grp_compute_controller_fu_1306_dbg_mac_ready;
    end else begin
        dbg_mac_ready = dbg_mac_ready_reg;
    end
end

always @ (*) begin
    if (((grp_compute_controller_fu_1306_dbg_mac_start_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        dbg_mac_start = grp_compute_controller_fu_1306_dbg_mac_start;
    end else begin
        dbg_mac_start = dbg_mac_start_reg;
    end
end

always @ (*) begin
    if (((grp_compute_controller_fu_1306_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        dbg_req_head_ap_vld = 1'b1;
    end else begin
        dbg_req_head_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((grp_compute_controller_fu_1306_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        dbg_req_instruction_ap_vld = 1'b1;
    end else begin
        dbg_req_instruction_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((grp_compute_controller_fu_1306_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        dbg_req_layer_ap_vld = 1'b1;
    end else begin
        dbg_req_layer_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((grp_compute_controller_fu_1306_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        dbg_req_op_ap_vld = 1'b1;
    end else begin
        dbg_req_op_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((grp_compute_controller_fu_1306_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        dbg_req_tile_ap_vld = 1'b1;
    end else begin
        dbg_req_tile_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((grp_scheduler_hls_fu_1173_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        head_ctx_ref_0_o_ap_vld = 1'b1;
    end else begin
        head_ctx_ref_0_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((grp_scheduler_hls_fu_1173_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        head_ctx_ref_1_o_ap_vld = 1'b1;
    end else begin
        head_ctx_ref_1_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((grp_scheduler_hls_fu_1173_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        head_ctx_ref_2_o_ap_vld = 1'b1;
    end else begin
        head_ctx_ref_2_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((grp_scheduler_hls_fu_1173_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        head_ctx_ref_3_o_ap_vld = 1'b1;
    end else begin
        head_ctx_ref_3_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((grp_compute_controller_fu_1306_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        irq_clear_reg_ap_vld = 1'b1;
    end else begin
        irq_clear_reg_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((grp_compute_controller_fu_1306_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        irq_mask_reg_ap_vld = 1'b1;
    end else begin
        irq_mask_reg_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((grp_compute_controller_fu_1306_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        irq_ps = icmp_ln93_fu_2683_p2;
    end else begin
        irq_ps = irq_ps_preg;
    end
end

always @ (*) begin
    if (((grp_compute_controller_fu_1306_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        irq_status_reg_ap_vld = 1'b1;
    end else begin
        irq_status_reg_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((grp_compute_controller_fu_1306_mem_op_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        mem_op = grp_compute_controller_fu_1306_mem_op;
    end else begin
        mem_op = mem_op_reg;
    end
end

always @ (*) begin
    if (((grp_compute_controller_fu_1306_mem_read_request_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        mem_read_request = grp_compute_controller_fu_1306_mem_read_request;
    end else begin
        mem_read_request = mem_read_request_reg;
    end
end

always @ (*) begin
    if (((grp_compute_controller_fu_1306_mem_write_request_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        mem_write_request = grp_compute_controller_fu_1306_mem_write_request;
    end else begin
        mem_write_request = mem_write_request_reg;
    end
end

always @ (*) begin
    if (((grp_compute_controller_fu_1306_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        status_mem_ap_vld = 1'b1;
    end else begin
        status_mem_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((grp_scheduler_hls_fu_1173_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        stream_start_ap_vld = 1'b1;
    end else begin
        stream_start_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((grp_compute_controller_fu_1306_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        w1_base_addr_ap_vld = 1'b1;
    end else begin
        w1_base_addr_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((grp_compute_controller_fu_1306_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        w1_tile_stride_ap_vld = 1'b1;
    end else begin
        w1_tile_stride_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((grp_compute_controller_fu_1306_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        w2_base_addr_ap_vld = 1'b1;
    end else begin
        w2_base_addr_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((grp_compute_controller_fu_1306_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        w2_tile_stride_ap_vld = 1'b1;
    end else begin
        w2_tile_stride_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((grp_compute_controller_fu_1306_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        wk_base_addr_ap_vld = 1'b1;
    end else begin
        wk_base_addr_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((grp_compute_controller_fu_1306_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        wk_head_stride_ap_vld = 1'b1;
    end else begin
        wk_head_stride_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((grp_scheduler_hls_fu_1173_wl_instruction_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        wl_instruction = grp_scheduler_hls_fu_1173_wl_instruction;
    end else begin
        wl_instruction = wl_instruction_reg;
    end
end

always @ (*) begin
    if (((grp_scheduler_hls_fu_1173_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        wl_start_o_ap_vld = 1'b1;
    end else begin
        wl_start_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((grp_compute_controller_fu_1306_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        wo_base_addr_ap_vld = 1'b1;
    end else begin
        wo_base_addr_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((grp_compute_controller_fu_1306_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        wo_tile_stride_ap_vld = 1'b1;
    end else begin
        wo_tile_stride_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((grp_compute_controller_fu_1306_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        wq_base_addr_ap_vld = 1'b1;
    end else begin
        wq_base_addr_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((grp_compute_controller_fu_1306_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        wq_head_stride_ap_vld = 1'b1;
    end else begin
        wq_head_stride_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((grp_compute_controller_fu_1306_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        wv_base_addr_ap_vld = 1'b1;
    end else begin
        wv_base_addr_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((grp_compute_controller_fu_1306_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        wv_head_stride_ap_vld = 1'b1;
    end else begin
        wv_head_stride_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_scheduler_hls_fu_1173_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((grp_compute_controller_fu_1306_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign STATE = grp_scheduler_hls_fu_1173_ap_return_5;

assign and_ln93_fu_2677_p2 = (trunc_ln93_fu_2656_p1 & and_ln_fu_2669_p3);

assign and_ln_fu_2669_p3 = {{tmp_11_fu_2660_p4}, {1'd0}};

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

always @ (*) begin
    ap_condition_1045 = (((icmp_ln22_reg_2977 == 1'd1) & (irq_error_en_fu_2086_p3 == 1'd1)) | ((irq_error_en_fu_2086_p3 == 1'd1) & (or_ln22_fu_2103_p2 == 1'd1)));
end

always @ (*) begin
    ap_condition_1063 = (((((or_ln33_fu_2225_p2 == 1'd1) & (irq_error_en_fu_2086_p3 == 1'd1)) | ((or_ln34_1_fu_2252_p2 == 1'd1) & (irq_error_en_fu_2086_p3 == 1'd1))) | ((or_ln32_fu_2209_p2 == 1'd1) & (irq_error_en_fu_2086_p3 == 1'd1))) | ((or_ln31_fu_2193_p2 == 1'd1) & (irq_error_en_fu_2086_p3 == 1'd1)));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign axis_in_ready = grp_scheduler_hls_fu_1173_ap_return_0;

assign compute_error_fu_2082_p1 = grp_compute_controller_fu_1306_ap_return_6;

assign control_reg = ctrl_mem_control_reg_2845;

assign ctrl_mem_control_fu_1764_p1 = ctrl_mem[31:0];

assign ctrl_mem_dma_layer_len_fu_1792_p3 = {{ctrl_mem[127:96]}};

assign dbg_compute_done = compute_done;

assign dbg_compute_instruction = compute_instruction;

assign dbg_compute_ready = compute_ready;

assign dbg_compute_start = compute_start;

assign dbg_compute_state = grp_compute_controller_fu_1306_ap_return_0;

assign dbg_ctrl_mem = {{tmp_fu_2715_p4}, {trunc_ln195_fu_2724_p1}};

assign dbg_ctrl_reset_asserted = xor_ln116_reg_2972;

assign dbg_done = done_reg_3016;

assign dbg_mac_complete_ap_vld = grp_compute_controller_fu_1306_dbg_mac_complete_ap_vld;

assign dbg_mac_ready_ap_vld = grp_compute_controller_fu_1306_dbg_mac_ready_ap_vld;

assign dbg_mac_start_ap_vld = grp_compute_controller_fu_1306_dbg_mac_start_ap_vld;

assign dbg_req_head = grp_compute_controller_fu_1306_ap_return_4;

assign dbg_req_instruction = grp_compute_controller_fu_1306_ap_return_1;

assign dbg_req_layer = grp_compute_controller_fu_1306_ap_return_3;

assign dbg_req_op = grp_compute_controller_fu_1306_ap_return_2;

assign dbg_req_tile = grp_compute_controller_fu_1306_ap_return_5;

assign grp_compute_controller_fu_1306_ap_start = grp_compute_controller_fu_1306_ap_start_reg;

assign grp_scheduler_hls_fu_1173_ap_start = grp_scheduler_hls_fu_1173_ap_start_reg;

assign head_ctx_ref_0_o = grp_scheduler_hls_fu_1173_ap_return_6;

assign head_ctx_ref_1_o = grp_scheduler_hls_fu_1173_ap_return_7;

assign head_ctx_ref_2_o = grp_scheduler_hls_fu_1173_ap_return_8;

assign head_ctx_ref_3_o = grp_scheduler_hls_fu_1173_ap_return_9;

assign icmp_ln22_1_fu_2093_p2 = ((ctrl_mem_dma_head_len_reg_2871 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln22_2_fu_2098_p2 = ((ctrl_mem_dma_tile_len_reg_2876 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln22_fu_1998_p2 = ((ctrl_mem_dma_layer_len_fu_1792_p3 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln31_fu_2183_p2 = ((ctrl_mem_layer_stride_reg_2881 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln32_1_fu_2199_p2 = ((ctrl_mem_wk_head_stride_reg_2892 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln32_2_fu_2204_p2 = ((ctrl_mem_wv_head_stride_reg_2898 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln32_fu_2188_p2 = ((ctrl_mem_wq_head_stride_reg_2886 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln33_1_fu_2220_p2 = ((ctrl_mem_v_cache_stride_reg_2909 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln33_fu_2215_p2 = ((ctrl_mem_k_cache_stride_reg_2904 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln34_1_fu_2236_p2 = ((ctrl_mem_w1_tile_stride_reg_2920 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln34_2_fu_2241_p2 = ((ctrl_mem_w2_tile_stride_reg_2926 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln34_fu_2231_p2 = ((ctrl_mem_wo_tile_stride_reg_2914 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln43_fu_2366_p2 = ((or_ln43_6_fu_2360_p2 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln74_fu_2588_p2 = ((ctrl_mem_irq_clear_reg_2865 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln93_fu_2683_p2 = ((and_ln93_fu_2677_p2 != 3'd0) ? 1'b1 : 1'b0);

assign in_buf_address0 = grp_compute_controller_fu_1306_in_buf_address0;

assign in_buf_address1 = grp_compute_controller_fu_1306_in_buf_address1;

assign in_buf_ce0 = grp_compute_controller_fu_1306_in_buf_ce0;

assign in_buf_ce1 = grp_compute_controller_fu_1306_in_buf_ce1;

assign irq_clear_reg = ctrl_mem_irq_clear_reg_2865;

assign irq_error_en_fu_2086_p3 = ctrl_mem_read_reg_2811[32'd33];

assign irq_mask_reg = ctrl_mem_irq_mask_reg_2860;

assign irq_status_reg = ap_sig_allocacmp_ctrl_mem_interface_irq_status_load_6;

assign mem_op_ap_vld = grp_compute_controller_fu_1306_mem_op_ap_vld;

assign mem_read_request_ap_vld = grp_compute_controller_fu_1306_mem_read_request_ap_vld;

assign mem_write_request_ap_vld = grp_compute_controller_fu_1306_mem_write_request_ap_vld;

assign or_ln10_fu_2617_p4 = {{{tmp_10_fu_2603_p4}, {1'd1}}, {trunc_ln77_fu_2613_p1}};

assign or_ln1_fu_2167_p4 = {{{tmp_3_fu_2153_p4}, {1'd1}}, {trunc_ln26_fu_2163_p1}};

assign or_ln22_fu_2103_p2 = (icmp_ln22_2_fu_2098_p2 | icmp_ln22_1_fu_2093_p2);

assign or_ln2_fu_2276_p4 = {{{tmp_5_fu_2262_p4}, {1'd1}}, {trunc_ln36_fu_2272_p1}};

assign or_ln31_fu_2193_p2 = (icmp_ln32_fu_2188_p2 | icmp_ln31_fu_2183_p2);

assign or_ln32_fu_2209_p2 = (icmp_ln32_2_fu_2204_p2 | icmp_ln32_1_fu_2199_p2);

assign or_ln33_fu_2225_p2 = (icmp_ln33_fu_2215_p2 | icmp_ln33_1_fu_2220_p2);

assign or_ln34_1_fu_2252_p2 = (or_ln34_fu_2246_p2 | icmp_ln34_fu_2231_p2);

assign or_ln34_fu_2246_p2 = (icmp_ln34_2_fu_2241_p2 | icmp_ln34_1_fu_2236_p2);

assign or_ln3_fu_2316_p4 = {{{tmp_7_fu_2302_p4}, {1'd1}}, {trunc_ln38_fu_2312_p1}};

assign or_ln43_1_fu_2336_p2 = (ctrl_mem_wv_base_addr_cast4_reg_2942 | ctrl_mem_wo_base_addr_cast5_reg_2947);

assign or_ln43_2_fu_2340_p2 = (or_ln43_fu_2332_p2 | or_ln43_1_fu_2336_p2);

assign or_ln43_3_fu_2346_p2 = (ctrl_mem_w2_base_addr_cast7_reg_2957 | ctrl_mem_w1_base_addr_cast6_reg_2952);

assign or_ln43_4_fu_2350_p2 = (ctrl_mem_v_cache_addr_cast9_reg_2967 | ctrl_mem_k_cache_addr_cast8_reg_2962);

assign or_ln43_5_fu_2354_p2 = (or_ln43_4_fu_2350_p2 | or_ln43_3_fu_2346_p2);

assign or_ln43_6_fu_2360_p2 = (or_ln43_5_fu_2354_p2 | or_ln43_2_fu_2340_p2);

assign or_ln43_fu_2332_p2 = (ctrl_mem_wq_base_addr_cast2_reg_2932 | ctrl_mem_wk_base_addr_cast3_reg_2937);

assign or_ln4_fu_2390_p4 = {{{tmp_9_fu_2376_p4}, {1'd1}}, {trunc_ln48_fu_2386_p1}};

assign or_ln5_fu_2426_p3 = {{tmp_s_fu_2416_p4}, {1'd1}};

assign or_ln6_fu_2458_p4 = {{{tmp_2_fu_2444_p4}, {1'd1}}, {trunc_ln56_fu_2454_p1}};

assign or_ln7_fu_2498_p4 = {{{tmp_4_fu_2484_p4}, {1'd1}}, {trunc_ln58_fu_2494_p1}};

assign or_ln8_fu_2532_p4 = {{{tmp_6_fu_2518_p4}, {1'd1}}, {trunc_ln63_fu_2528_p1}};

assign or_ln9_fu_2572_p4 = {{{tmp_8_fu_2558_p4}, {1'd1}}, {trunc_ln65_fu_2568_p1}};

assign or_ln_fu_2127_p4 = {{{tmp_1_fu_2113_p4}, {1'd1}}, {trunc_ln24_fu_2123_p1}};

assign out_buf_address0 = grp_compute_controller_fu_1306_out_buf_address0;

assign out_buf_address1 = grp_compute_controller_fu_1306_out_buf_address1;

assign out_buf_ce0 = grp_compute_controller_fu_1306_out_buf_ce0;

assign out_buf_ce1 = grp_compute_controller_fu_1306_out_buf_ce1;

assign out_buf_d0 = grp_compute_controller_fu_1306_out_buf_d0;

assign out_buf_d1 = grp_compute_controller_fu_1306_out_buf_d1;

assign out_buf_we0 = grp_compute_controller_fu_1306_out_buf_we0;

assign out_buf_we1 = grp_compute_controller_fu_1306_out_buf_we1;

assign status_mem = {{{{ctrl_mem_interface_layer_index}, {ap_sig_allocacmp_ctrl_mem_interface_error_code_load_5}}, {ap_sig_allocacmp_ctrl_mem_interface_irq_status_load_6}}, {ap_sig_allocacmp_ctrl_mem_interface_status_load}};

assign stream_start = grp_scheduler_hls_fu_1173_ap_return_2;

assign tmp_10_fu_2603_p4 = {{ap_sig_allocacmp_ctrl_mem_interface_irq_status_load_5[31:3]}};

assign tmp_11_fu_2660_p4 = {{ctrl_mem_read_reg_2811[34:33]}};

assign tmp_1_fu_2113_p4 = {{ctrl_mem_interface_irq_status[31:2]}};

assign tmp_2_fu_2444_p4 = {{ap_sig_allocacmp_ctrl_mem_interface_irq_status_load_3[31:2]}};

assign tmp_3_fu_2153_p4 = {{ctrl_mem_interface_error_code[31:2]}};

assign tmp_4_fu_2484_p4 = {{ap_sig_allocacmp_ctrl_mem_interface_error_code_load_3[31:4]}};

assign tmp_5_fu_2262_p4 = {{ap_sig_allocacmp_ctrl_mem_interface_irq_status_load_1[31:2]}};

assign tmp_6_fu_2518_p4 = {{ap_sig_allocacmp_ctrl_mem_interface_irq_status_load_4[31:2]}};

assign tmp_7_fu_2302_p4 = {{ap_sig_allocacmp_ctrl_mem_interface_error_code_load_1[31:3]}};

assign tmp_8_fu_2558_p4 = {{ap_sig_allocacmp_ctrl_mem_interface_error_code_load_4[31:5]}};

assign tmp_9_fu_2376_p4 = {{ap_sig_allocacmp_ctrl_mem_interface_irq_status_load_2[31:2]}};

assign tmp_fu_2715_p4 = {{ctrl_mem_read_reg_2811[1247:512]}};

assign tmp_s_fu_2416_p4 = {{ap_sig_allocacmp_ctrl_mem_interface_error_code_load_2[31:1]}};

assign trunc_ln195_fu_2724_p1 = ctrl_mem_read_reg_2811[479:0];

assign trunc_ln21_1_fu_1772_p1 = ctrl_mem[0:0];

assign trunc_ln21_fu_1768_p1 = ctrl_mem[1:0];

assign trunc_ln24_fu_2123_p1 = ctrl_mem_interface_irq_status[0:0];

assign trunc_ln26_fu_2163_p1 = ctrl_mem_interface_error_code[0:0];

assign trunc_ln36_fu_2272_p1 = ap_sig_allocacmp_ctrl_mem_interface_irq_status_load_1[0:0];

assign trunc_ln38_fu_2312_p1 = ap_sig_allocacmp_ctrl_mem_interface_error_code_load_1[1:0];

assign trunc_ln48_fu_2386_p1 = ap_sig_allocacmp_ctrl_mem_interface_irq_status_load_2[0:0];

assign trunc_ln56_fu_2454_p1 = ap_sig_allocacmp_ctrl_mem_interface_irq_status_load_3[0:0];

assign trunc_ln58_fu_2494_p1 = ap_sig_allocacmp_ctrl_mem_interface_error_code_load_3[2:0];

assign trunc_ln63_fu_2528_p1 = ap_sig_allocacmp_ctrl_mem_interface_irq_status_load_4[0:0];

assign trunc_ln65_fu_2568_p1 = ap_sig_allocacmp_ctrl_mem_interface_error_code_load_4[3:0];

assign trunc_ln77_fu_2613_p1 = ap_sig_allocacmp_ctrl_mem_interface_irq_status_load_5[1:0];

assign trunc_ln93_fu_2656_p1 = ap_sig_allocacmp_ctrl_mem_interface_irq_status_load_6[2:0];

assign w1_base_addr = {{ctrl_mem_read_reg_2811[799:768]}};

assign w1_tile_stride = ctrl_mem_w1_tile_stride_reg_2920;

assign w2_base_addr = {{ctrl_mem_read_reg_2811[863:832]}};

assign w2_tile_stride = ctrl_mem_w2_tile_stride_reg_2926;

assign wk_base_addr = {{ctrl_mem_read_reg_2811[607:576]}};

assign wk_head_stride = ctrl_mem_wk_head_stride_reg_2892;

assign wl_instruction_ap_vld = grp_scheduler_hls_fu_1173_wl_instruction_ap_vld;

assign wl_start_o = grp_scheduler_hls_fu_1173_ap_return_1;

assign wo_base_addr = {{ctrl_mem_read_reg_2811[735:704]}};

assign wo_tile_stride = ctrl_mem_wo_tile_stride_reg_2914;

assign wq_base_addr = {{ctrl_mem_read_reg_2811[543:512]}};

assign wq_head_stride = ctrl_mem_wq_head_stride_reg_2886;

assign wv_base_addr = {{ctrl_mem_read_reg_2811[671:640]}};

assign wv_head_stride = ctrl_mem_wv_head_stride_reg_2898;

assign xor_ln116_fu_1968_p2 = (trunc_ln21_1_fu_1772_p1 ^ 1'd1);

endmodule //transformer_top
