// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module transformer_top_compute_controller_Pipeline_VITIS_LOOP_654_36 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_buf_address0,
        in_buf_ce0,
        in_buf_q0,
        in_buf_address1,
        in_buf_ce1,
        in_buf_q1,
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_59_address0,
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_59_ce0,
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_59_we0,
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_59_d0,
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_57_address0,
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_57_ce0,
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_57_we0,
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_57_d0,
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_56_address0,
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_56_ce0,
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_56_we0,
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_56_d0,
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_55_address0,
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_55_ce0,
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_55_we0,
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_55_d0,
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_54_address0,
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_54_ce0,
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_54_we0,
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_54_d0,
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_53_address0,
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_53_ce0,
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_53_we0,
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_53_d0,
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_52_address0,
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_52_ce0,
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_52_we0,
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_52_d0,
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_51_address0,
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_51_ce0,
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_51_we0,
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_51_d0,
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_50_address0,
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_50_ce0,
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_50_we0,
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_50_d0,
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_58_address0,
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_58_ce0,
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_58_we0,
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_58_d0,
        p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_23_address0,
        p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_23_ce0,
        p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_23_we0,
        p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_23_d0,
        p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_22_address0,
        p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_22_ce0,
        p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_22_we0,
        p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_22_d0,
        p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_21_address0,
        p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_21_ce0,
        p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_21_we0,
        p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_21_d0,
        p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_20_address0,
        p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_20_ce0,
        p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_20_we0,
        p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_20_d0,
        p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_19_address0,
        p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_19_ce0,
        p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_19_we0,
        p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_19_d0,
        p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_18_address0,
        p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_18_ce0,
        p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_18_we0,
        p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_18_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] in_buf_address0;
output   in_buf_ce0;
input  [7:0] in_buf_q0;
output  [7:0] in_buf_address1;
output   in_buf_ce1;
input  [7:0] in_buf_q1;
output  [0:0] compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_59_address0;
output   compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_59_ce0;
output   compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_59_we0;
output  [15:0] compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_59_d0;
output  [0:0] compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_57_address0;
output   compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_57_ce0;
output   compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_57_we0;
output  [15:0] compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_57_d0;
output  [0:0] compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_56_address0;
output   compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_56_ce0;
output   compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_56_we0;
output  [15:0] compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_56_d0;
output  [0:0] compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_55_address0;
output   compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_55_ce0;
output   compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_55_we0;
output  [15:0] compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_55_d0;
output  [0:0] compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_54_address0;
output   compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_54_ce0;
output   compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_54_we0;
output  [15:0] compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_54_d0;
output  [0:0] compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_53_address0;
output   compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_53_ce0;
output   compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_53_we0;
output  [15:0] compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_53_d0;
output  [0:0] compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_52_address0;
output   compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_52_ce0;
output   compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_52_we0;
output  [15:0] compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_52_d0;
output  [0:0] compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_51_address0;
output   compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_51_ce0;
output   compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_51_we0;
output  [15:0] compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_51_d0;
output  [0:0] compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_50_address0;
output   compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_50_ce0;
output   compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_50_we0;
output  [15:0] compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_50_d0;
output  [0:0] compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_58_address0;
output   compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_58_ce0;
output   compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_58_we0;
output  [15:0] compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_58_d0;
output  [0:0] p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_23_address0;
output   p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_23_ce0;
output   p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_23_we0;
output  [15:0] p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_23_d0;
output  [0:0] p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_22_address0;
output   p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_22_ce0;
output   p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_22_we0;
output  [15:0] p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_22_d0;
output  [0:0] p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_21_address0;
output   p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_21_ce0;
output   p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_21_we0;
output  [15:0] p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_21_d0;
output  [0:0] p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_20_address0;
output   p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_20_ce0;
output   p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_20_we0;
output  [15:0] p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_20_d0;
output  [0:0] p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_19_address0;
output   p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_19_ce0;
output   p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_19_we0;
output  [15:0] p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_19_d0;
output  [0:0] p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_18_address0;
output   p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_18_ce0;
output   p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_18_we0;
output  [15:0] p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_18_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln654_fu_351_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [3:0] trunc_ln654_fu_363_p1;
reg   [3:0] trunc_ln654_reg_493;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] tmp_reg_497;
wire   [63:0] zext_ln549_fu_383_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln550_fu_396_p1;
wire   [63:0] zext_ln654_fu_440_p1;
reg   [4:0] i_fu_106;
wire   [4:0] add_ln654_fu_357_p2;
wire    ap_loop_init;
reg   [4:0] ap_sig_allocacmp_i_3;
reg    in_buf_ce1_local;
reg    in_buf_ce0_local;
reg    p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_19_we0_local;
wire   [15:0] v_fu_459_p3;
reg    p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_19_ce0_local;
reg    p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_20_we0_local;
reg    p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_20_ce0_local;
reg    p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_21_we0_local;
reg    p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_21_ce0_local;
reg    p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_22_we0_local;
reg    p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_22_ce0_local;
reg    p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_23_we0_local;
reg    p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_23_ce0_local;
reg    compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_58_we0_local;
reg    compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_58_ce0_local;
reg    compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_50_we0_local;
reg    compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_50_ce0_local;
reg    compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_51_we0_local;
reg    compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_51_ce0_local;
reg    compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_52_we0_local;
reg    compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_52_ce0_local;
reg    compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_53_we0_local;
reg    compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_53_ce0_local;
reg    compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_54_we0_local;
reg    compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_54_ce0_local;
reg    compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_55_we0_local;
reg    compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_55_ce0_local;
reg    compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_56_we0_local;
reg    compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_56_ce0_local;
reg    compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_57_we0_local;
reg    compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_57_ce0_local;
reg    compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_59_we0_local;
reg    compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_59_ce0_local;
reg    p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_18_we0_local;
reg    p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_18_ce0_local;
wire   [5:0] byte_addr_assign_5_fu_375_p3;
wire   [5:0] or_ln550_1_fu_388_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 i_fu_106 = 5'd0;
#0 ap_done_reg = 1'b0;
end

transformer_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln654_fu_351_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_106 <= add_ln654_fu_357_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_106 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_reg_497 <= ap_sig_allocacmp_i_3[32'd4];
        trunc_ln654_reg_493 <= trunc_ln654_fu_363_p1;
    end
end

always @ (*) begin
    if (((icmp_ln654_fu_351_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_3 = 5'd0;
    end else begin
        ap_sig_allocacmp_i_3 = i_fu_106;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_50_ce0_local = 1'b1;
    end else begin
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_50_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln654_reg_493 == 4'd8))) begin
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_50_we0_local = 1'b1;
    end else begin
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_50_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_51_ce0_local = 1'b1;
    end else begin
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_51_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln654_reg_493 == 4'd7))) begin
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_51_we0_local = 1'b1;
    end else begin
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_51_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_52_ce0_local = 1'b1;
    end else begin
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_52_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln654_reg_493 == 4'd6))) begin
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_52_we0_local = 1'b1;
    end else begin
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_52_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_53_ce0_local = 1'b1;
    end else begin
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_53_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln654_reg_493 == 4'd5))) begin
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_53_we0_local = 1'b1;
    end else begin
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_53_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_54_ce0_local = 1'b1;
    end else begin
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_54_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln654_reg_493 == 4'd4))) begin
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_54_we0_local = 1'b1;
    end else begin
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_54_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_55_ce0_local = 1'b1;
    end else begin
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_55_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln654_reg_493 == 4'd3))) begin
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_55_we0_local = 1'b1;
    end else begin
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_55_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_56_ce0_local = 1'b1;
    end else begin
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_56_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln654_reg_493 == 4'd2))) begin
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_56_we0_local = 1'b1;
    end else begin
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_56_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_57_ce0_local = 1'b1;
    end else begin
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_57_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln654_reg_493 == 4'd1))) begin
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_57_we0_local = 1'b1;
    end else begin
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_57_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_58_ce0_local = 1'b1;
    end else begin
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_58_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln654_reg_493 == 4'd9))) begin
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_58_we0_local = 1'b1;
    end else begin
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_58_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_59_ce0_local = 1'b1;
    end else begin
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_59_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln654_reg_493 == 4'd0))) begin
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_59_we0_local = 1'b1;
    end else begin
        compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_59_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_buf_ce0_local = 1'b1;
    end else begin
        in_buf_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_buf_ce1_local = 1'b1;
    end else begin
        in_buf_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_18_ce0_local = 1'b1;
    end else begin
        p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_18_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln654_reg_493 == 4'd15))) begin
        p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_18_we0_local = 1'b1;
    end else begin
        p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_18_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_19_ce0_local = 1'b1;
    end else begin
        p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_19_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln654_reg_493 == 4'd14))) begin
        p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_19_we0_local = 1'b1;
    end else begin
        p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_19_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_20_ce0_local = 1'b1;
    end else begin
        p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_20_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln654_reg_493 == 4'd13))) begin
        p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_20_we0_local = 1'b1;
    end else begin
        p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_20_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_21_ce0_local = 1'b1;
    end else begin
        p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_21_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln654_reg_493 == 4'd12))) begin
        p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_21_we0_local = 1'b1;
    end else begin
        p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_21_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_22_ce0_local = 1'b1;
    end else begin
        p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_22_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln654_reg_493 == 4'd11))) begin
        p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_22_we0_local = 1'b1;
    end else begin
        p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_22_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_23_ce0_local = 1'b1;
    end else begin
        p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_23_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln654_reg_493 == 4'd10))) begin
        p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_23_we0_local = 1'b1;
    end else begin
        p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_23_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln654_fu_357_p2 = (ap_sig_allocacmp_i_3 + 5'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign byte_addr_assign_5_fu_375_p3 = {{ap_sig_allocacmp_i_3}, {1'd0}};

assign compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_50_address0 = zext_ln654_fu_440_p1;

assign compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_50_ce0 = compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_50_ce0_local;

assign compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_50_d0 = v_fu_459_p3;

assign compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_50_we0 = compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_50_we0_local;

assign compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_51_address0 = zext_ln654_fu_440_p1;

assign compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_51_ce0 = compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_51_ce0_local;

assign compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_51_d0 = v_fu_459_p3;

assign compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_51_we0 = compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_51_we0_local;

assign compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_52_address0 = zext_ln654_fu_440_p1;

assign compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_52_ce0 = compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_52_ce0_local;

assign compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_52_d0 = v_fu_459_p3;

assign compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_52_we0 = compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_52_we0_local;

assign compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_53_address0 = zext_ln654_fu_440_p1;

assign compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_53_ce0 = compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_53_ce0_local;

assign compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_53_d0 = v_fu_459_p3;

assign compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_53_we0 = compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_53_we0_local;

assign compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_54_address0 = zext_ln654_fu_440_p1;

assign compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_54_ce0 = compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_54_ce0_local;

assign compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_54_d0 = v_fu_459_p3;

assign compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_54_we0 = compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_54_we0_local;

assign compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_55_address0 = zext_ln654_fu_440_p1;

assign compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_55_ce0 = compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_55_ce0_local;

assign compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_55_d0 = v_fu_459_p3;

assign compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_55_we0 = compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_55_we0_local;

assign compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_56_address0 = zext_ln654_fu_440_p1;

assign compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_56_ce0 = compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_56_ce0_local;

assign compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_56_d0 = v_fu_459_p3;

assign compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_56_we0 = compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_56_we0_local;

assign compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_57_address0 = zext_ln654_fu_440_p1;

assign compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_57_ce0 = compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_57_ce0_local;

assign compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_57_d0 = v_fu_459_p3;

assign compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_57_we0 = compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_57_we0_local;

assign compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_58_address0 = zext_ln654_fu_440_p1;

assign compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_58_ce0 = compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_58_ce0_local;

assign compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_58_d0 = v_fu_459_p3;

assign compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_58_we0 = compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_58_we0_local;

assign compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_59_address0 = zext_ln654_fu_440_p1;

assign compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_59_ce0 = compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_59_ce0_local;

assign compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_59_d0 = v_fu_459_p3;

assign compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_59_we0 = compute_controller_ControlMemSpace_bool_unsigned_int_bool_bool_bool_bool_59_we0_local;

assign icmp_ln654_fu_351_p2 = ((ap_sig_allocacmp_i_3 == 5'd22) ? 1'b1 : 1'b0);

assign in_buf_address0 = zext_ln550_fu_396_p1;

assign in_buf_address1 = zext_ln549_fu_383_p1;

assign in_buf_ce0 = in_buf_ce0_local;

assign in_buf_ce1 = in_buf_ce1_local;

assign or_ln550_1_fu_388_p3 = {{ap_sig_allocacmp_i_3}, {1'd1}};

assign p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_18_address0 = zext_ln654_fu_440_p1;

assign p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_18_ce0 = p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_18_ce0_local;

assign p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_18_d0 = v_fu_459_p3;

assign p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_18_we0 = p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_18_we0_local;

assign p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_19_address0 = zext_ln654_fu_440_p1;

assign p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_19_ce0 = p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_19_ce0_local;

assign p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_19_d0 = v_fu_459_p3;

assign p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_19_we0 = p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_19_we0_local;

assign p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_20_address0 = zext_ln654_fu_440_p1;

assign p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_20_ce0 = p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_20_ce0_local;

assign p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_20_d0 = v_fu_459_p3;

assign p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_20_we0 = p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_20_we0_local;

assign p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_21_address0 = zext_ln654_fu_440_p1;

assign p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_21_ce0 = p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_21_ce0_local;

assign p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_21_d0 = v_fu_459_p3;

assign p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_21_we0 = p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_21_we0_local;

assign p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_22_address0 = zext_ln654_fu_440_p1;

assign p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_22_ce0 = p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_22_ce0_local;

assign p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_22_d0 = v_fu_459_p3;

assign p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_22_we0 = p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_22_we0_local;

assign p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_23_address0 = zext_ln654_fu_440_p1;

assign p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_23_ce0 = p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_23_ce0_local;

assign p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_23_d0 = v_fu_459_p3;

assign p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_23_we0 = p_ZZ18compute_controller15ControlMemSpacebjRbS0_bS0_S0_RjPKhPhR12ComputeStateS1_R_23_we0_local;

assign trunc_ln654_fu_363_p1 = ap_sig_allocacmp_i_3[3:0];

assign v_fu_459_p3 = {{in_buf_q0}, {in_buf_q1}};

assign zext_ln549_fu_383_p1 = byte_addr_assign_5_fu_375_p3;

assign zext_ln550_fu_396_p1 = or_ln550_1_fu_388_p3;

assign zext_ln654_fu_440_p1 = tmp_reg_497;

endmodule //transformer_top_compute_controller_Pipeline_VITIS_LOOP_654_36
