

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "2"],
		"CDFG" : "weight_stager",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "1",
		"VariableLatency" : "0", "ExactLatency" : "0", "EstimateLatencyMin" : "0", "EstimateLatencyMax" : "0",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "wl_start", "Type" : "None", "Direction" : "I"},
			{"Name" : "wl_addr_sel", "Type" : "None", "Direction" : "I"},
			{"Name" : "wl_layer", "Type" : "None", "Direction" : "I"},
			{"Name" : "wl_head", "Type" : "None", "Direction" : "I"},
			{"Name" : "wl_tile", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctrl_mem", "Type" : "None", "Direction" : "I"},
			{"Name" : "wl_ready", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "memory_request", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "error", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "addr_latched", "Type" : "OVld", "Direction" : "IO"}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32s_32s_32_1_1_U1", "Parent" : "0"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32s_32s_32_1_1_U2", "Parent" : "0"}]}
