

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43"],
		"CDFG" : "scheduler_hls",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "1",
		"VariableLatency" : "0", "ExactLatency" : "0", "EstimateLatencyMin" : "0", "EstimateLatencyMax" : "0",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "cntrl_start", "Type" : "None", "Direction" : "I"},
			{"Name" : "cntrl_reset_n", "Type" : "None", "Direction" : "I"},
			{"Name" : "cntrl_layer_idx", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "cntrl_busy", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "cntrl_start_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "axis_in_valid", "Type" : "None", "Direction" : "I"},
			{"Name" : "axis_in_last", "Type" : "None", "Direction" : "I"},
			{"Name" : "axis_in_ready", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "wl_ready", "Type" : "None", "Direction" : "I"},
			{"Name" : "wl_start", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "wl_addr_sel", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "wl_layer", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "wl_head", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "wl_tile", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "dma_done", "Type" : "None", "Direction" : "I"},
			{"Name" : "compute_ready", "Type" : "None", "Direction" : "I"},
			{"Name" : "compute_done", "Type" : "None", "Direction" : "I"},
			{"Name" : "requant_ready", "Type" : "None", "Direction" : "I"},
			{"Name" : "requant_done", "Type" : "None", "Direction" : "I"},
			{"Name" : "head_ctx_ref_0", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "head_ctx_ref_1", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "head_ctx_ref_2", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "head_ctx_ref_3", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "compute_start", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "compute_op", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "requant_start", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "requant_op", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "stream_ready", "Type" : "None", "Direction" : "I"},
			{"Name" : "stream_start", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "stream_done", "Type" : "None", "Direction" : "I"},
			{"Name" : "done", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "debug_compute_done", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "STATE", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "attn_started", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "attn_compute_done", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "group_idx", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "start_head_group", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "concat_compute_done", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "concat_started", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "outproj_started", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "outproj_compute_done", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "resid0_started", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "resid0_compute_done", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ln0_started", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ln0_compute_done", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ffn_w1_compute_done", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ffn_act_compute_done", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ffn_w2_compute_done", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ffn_stage", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ffn_started", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "resid1_started", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "resid1_compute_done", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ln1_started", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ln1_compute_done", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "st", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "layer_idx", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "stream_started", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "wo_tile", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "wo_dma_busy", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "wo_comp_busy", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "w1_tile", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "w1_dma_busy", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "w1_comp_busy", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "w2_tile", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "w2_dma_busy", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "w2_comp_busy", "Type" : "OVld", "Direction" : "IO"}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_drive_group_head_phase_fu_7660", "Parent" : "0",
		"CDFG" : "drive_group_head_phase",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "0", "ap_start" : "0", "ap_ready" : "1", "ap_done" : "0", "ap_continue" : "0", "ap_idle" : "0", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "1",
		"VariableLatency" : "0", "ExactLatency" : "0", "EstimateLatencyMin" : "0", "EstimateLatencyMax" : "0",
		"Combinational" : "1",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "p_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "head_ctx_ref_layer_stamp_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "head_ctx_ref_head_idx_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "head_ctx_ref_phase_read_5", "Type" : "None", "Direction" : "I"},
			{"Name" : "head_ctx_ref_phase_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read2", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read7", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read8", "Type" : "None", "Direction" : "I"},
			{"Name" : "head_ctx_ref_compute_op_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "head_ctx_ref_last_compute_op_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "head_ctx_ref_last_wl_addr_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read12", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read13", "Type" : "None", "Direction" : "I"},
			{"Name" : "head_ctx_ref_wl_addr_sel_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read15", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read16", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read17", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read19", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read20", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read21", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read22", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read23", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read24", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read25", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read26", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read27", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read28", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read29", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read30", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read31", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read32", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read33", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read34", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read35", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read36", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read37", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read38", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read39", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read40", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read41", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read42", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read43", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read44", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read45", "Type" : "None", "Direction" : "I"},
			{"Name" : "layer_idx", "Type" : "None", "Direction" : "I"},
			{"Name" : "start_r", "Type" : "None", "Direction" : "I"}]},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_9_2_32_1_1_U47", "Parent" : "0"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_9_2_32_1_1_U48", "Parent" : "0"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_9_2_4_1_1_U49", "Parent" : "0"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_9_2_1_1_1_U50", "Parent" : "0"},
	{"ID" : "6", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_9_2_1_1_1_U51", "Parent" : "0"},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_9_2_1_1_1_U52", "Parent" : "0"},
	{"ID" : "8", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_9_2_4_1_1_U53", "Parent" : "0"},
	{"ID" : "9", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_9_2_4_1_1_U54", "Parent" : "0"},
	{"ID" : "10", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_9_2_4_1_1_U55", "Parent" : "0"},
	{"ID" : "11", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_9_2_1_1_1_U56", "Parent" : "0"},
	{"ID" : "12", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_9_2_1_1_1_U57", "Parent" : "0"},
	{"ID" : "13", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_9_2_4_1_1_U58", "Parent" : "0"},
	{"ID" : "14", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_9_2_32_1_1_U59", "Parent" : "0"},
	{"ID" : "15", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_9_2_32_1_1_U60", "Parent" : "0"},
	{"ID" : "16", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_9_2_1_1_1_U61", "Parent" : "0"},
	{"ID" : "17", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_9_2_1_1_1_U62", "Parent" : "0"},
	{"ID" : "18", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_9_2_1_1_1_U63", "Parent" : "0"},
	{"ID" : "19", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_9_2_1_1_1_U64", "Parent" : "0"},
	{"ID" : "20", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_9_2_1_1_1_U65", "Parent" : "0"},
	{"ID" : "21", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_9_2_1_1_1_U66", "Parent" : "0"},
	{"ID" : "22", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_9_2_1_1_1_U67", "Parent" : "0"},
	{"ID" : "23", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_9_2_1_1_1_U68", "Parent" : "0"},
	{"ID" : "24", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_9_2_1_1_1_U69", "Parent" : "0"},
	{"ID" : "25", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_9_2_1_1_1_U70", "Parent" : "0"},
	{"ID" : "26", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_9_2_1_1_1_U71", "Parent" : "0"},
	{"ID" : "27", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_9_2_1_1_1_U72", "Parent" : "0"},
	{"ID" : "28", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_9_2_1_1_1_U73", "Parent" : "0"},
	{"ID" : "29", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_9_2_1_1_1_U74", "Parent" : "0"},
	{"ID" : "30", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_9_2_1_1_1_U75", "Parent" : "0"},
	{"ID" : "31", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_9_2_1_1_1_U76", "Parent" : "0"},
	{"ID" : "32", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_9_2_1_1_1_U77", "Parent" : "0"},
	{"ID" : "33", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_9_2_1_1_1_U78", "Parent" : "0"},
	{"ID" : "34", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_9_2_1_1_1_U79", "Parent" : "0"},
	{"ID" : "35", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_9_2_1_1_1_U80", "Parent" : "0"},
	{"ID" : "36", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_9_2_1_1_1_U81", "Parent" : "0"},
	{"ID" : "37", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_9_2_1_1_1_U82", "Parent" : "0"},
	{"ID" : "38", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_9_2_1_1_1_U83", "Parent" : "0"},
	{"ID" : "39", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_9_2_1_1_1_U84", "Parent" : "0"},
	{"ID" : "40", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_9_2_1_1_1_U85", "Parent" : "0"},
	{"ID" : "41", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_9_2_1_1_1_U86", "Parent" : "0"},
	{"ID" : "42", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_9_2_1_1_1_U87", "Parent" : "0"},
	{"ID" : "43", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_9_2_1_1_1_U88", "Parent" : "0"}]}
