// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module transformer_top_p_anonymous_namespace_region_read_bytes_5 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        r_total_bytes_val,
        r_num_chunks_read,
        r_chunks_bank_read,
        r_chunks_bank_read_28,
        r_chunks_bank_read_29,
        r_chunks_bank_read_30,
        r_chunks_offset_read,
        r_chunks_offset_read_28,
        r_chunks_offset_read_29,
        r_chunks_offset_read_30,
        r_chunks_size_read,
        r_chunks_size_read_28,
        r_chunks_size_read_29,
        r_chunks_size_read_30,
        src_offset,
        bytes,
        p_ZN12_GLOBAL_N_17scratchE_1_address0,
        p_ZN12_GLOBAL_N_17scratchE_1_ce0,
        p_ZN12_GLOBAL_N_17scratchE_1_we0,
        p_ZN12_GLOBAL_N_17scratchE_1_d0,
        p_ZN12_GLOBAL_N_17scratchE_2_address0,
        p_ZN12_GLOBAL_N_17scratchE_2_ce0,
        p_ZN12_GLOBAL_N_17scratchE_2_we0,
        p_ZN12_GLOBAL_N_17scratchE_2_d0,
        p_ZN12_GLOBAL_N_17scratchE_3_address0,
        p_ZN12_GLOBAL_N_17scratchE_3_ce0,
        p_ZN12_GLOBAL_N_17scratchE_3_we0,
        p_ZN12_GLOBAL_N_17scratchE_3_d0,
        p_ZN12_GLOBAL_N_17scratchE_0_address0,
        p_ZN12_GLOBAL_N_17scratchE_0_ce0,
        p_ZN12_GLOBAL_N_17scratchE_0_we0,
        p_ZN12_GLOBAL_N_17scratchE_0_d0,
        p_anonymous_namespace_uram_banks_address0,
        p_anonymous_namespace_uram_banks_ce0,
        p_anonymous_namespace_uram_banks_q0,
        ap_return
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] r_total_bytes_val;
input  [7:0] r_num_chunks_read;
input  [4:0] r_chunks_bank_read;
input  [4:0] r_chunks_bank_read_28;
input  [4:0] r_chunks_bank_read_29;
input  [4:0] r_chunks_bank_read_30;
input  [19:0] r_chunks_offset_read;
input  [19:0] r_chunks_offset_read_28;
input  [19:0] r_chunks_offset_read_29;
input  [19:0] r_chunks_offset_read_30;
input  [31:0] r_chunks_size_read;
input  [31:0] r_chunks_size_read_28;
input  [31:0] r_chunks_size_read_29;
input  [31:0] r_chunks_size_read_30;
input  [31:0] src_offset;
input  [13:0] bytes;
output  [10:0] p_ZN12_GLOBAL_N_17scratchE_1_address0;
output   p_ZN12_GLOBAL_N_17scratchE_1_ce0;
output   p_ZN12_GLOBAL_N_17scratchE_1_we0;
output  [7:0] p_ZN12_GLOBAL_N_17scratchE_1_d0;
output  [10:0] p_ZN12_GLOBAL_N_17scratchE_2_address0;
output   p_ZN12_GLOBAL_N_17scratchE_2_ce0;
output   p_ZN12_GLOBAL_N_17scratchE_2_we0;
output  [7:0] p_ZN12_GLOBAL_N_17scratchE_2_d0;
output  [10:0] p_ZN12_GLOBAL_N_17scratchE_3_address0;
output   p_ZN12_GLOBAL_N_17scratchE_3_ce0;
output   p_ZN12_GLOBAL_N_17scratchE_3_we0;
output  [7:0] p_ZN12_GLOBAL_N_17scratchE_3_d0;
output  [10:0] p_ZN12_GLOBAL_N_17scratchE_0_address0;
output   p_ZN12_GLOBAL_N_17scratchE_0_ce0;
output   p_ZN12_GLOBAL_N_17scratchE_0_we0;
output  [7:0] p_ZN12_GLOBAL_N_17scratchE_0_d0;
output  [17:0] p_anonymous_namespace_uram_banks_address0;
output   p_anonymous_namespace_uram_banks_ce0;
input  [31:0] p_anonymous_namespace_uram_banks_q0;
output  [0:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[0:0] ap_return;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln1231_fu_309_p2;
wire    ap_CS_fsm_state2;
wire   [2:0] add_ln1231_fu_338_p2;
reg   [2:0] add_ln1231_reg_525;
reg   [31:0] logical_load_reg_530;
wire   [1:0] trunc_ln1231_fu_347_p1;
reg   [1:0] trunc_ln1231_reg_535;
wire   [0:0] icmp_ln1235_fu_371_p2;
reg   [0:0] icmp_ln1235_reg_540;
reg   [31:0] copied_load_reg_544;
wire   [31:0] take_fu_403_p3;
reg   [31:0] take_reg_549;
wire    grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_ap_start;
wire    grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_ap_done;
wire    grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_ap_idle;
wire    grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_ap_ready;
wire   [31:0] grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_copied_6_out;
wire    grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_copied_6_out_ap_vld;
wire   [31:0] grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_remaining_1_out_o;
wire    grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_remaining_1_out_o_ap_vld;
wire   [10:0] grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_p_ZN12_GLOBAL_N_17scratchE_1_address0;
wire    grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_p_ZN12_GLOBAL_N_17scratchE_1_ce0;
wire    grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_p_ZN12_GLOBAL_N_17scratchE_1_we0;
wire   [7:0] grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_p_ZN12_GLOBAL_N_17scratchE_1_d0;
wire   [10:0] grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_p_ZN12_GLOBAL_N_17scratchE_2_address0;
wire    grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_p_ZN12_GLOBAL_N_17scratchE_2_ce0;
wire    grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_p_ZN12_GLOBAL_N_17scratchE_2_we0;
wire   [7:0] grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_p_ZN12_GLOBAL_N_17scratchE_2_d0;
wire   [10:0] grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_p_ZN12_GLOBAL_N_17scratchE_3_address0;
wire    grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_p_ZN12_GLOBAL_N_17scratchE_3_ce0;
wire    grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_p_ZN12_GLOBAL_N_17scratchE_3_we0;
wire   [7:0] grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_p_ZN12_GLOBAL_N_17scratchE_3_d0;
wire   [10:0] grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_p_ZN12_GLOBAL_N_17scratchE_0_address0;
wire    grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_p_ZN12_GLOBAL_N_17scratchE_0_ce0;
wire    grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_p_ZN12_GLOBAL_N_17scratchE_0_we0;
wire   [7:0] grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_p_ZN12_GLOBAL_N_17scratchE_0_d0;
wire   [17:0] grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_p_anonymous_namespace_uram_banks_address0;
wire    grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_p_anonymous_namespace_uram_banks_ce0;
reg   [0:0] retval_0_reg_216;
wire   [0:0] icmp_ln1226_fu_265_p2;
wire   [0:0] or_ln1231_2_fu_332_p2;
reg    grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_ap_start_reg;
reg   [4:0] ap_NS_fsm;
wire    ap_NS_fsm_state3;
wire    ap_CS_fsm_state4;
reg   [31:0] copied_fu_116;
reg   [31:0] remaining_fu_112;
reg   [31:0] logical_fu_104;
wire   [31:0] logical_26_fu_377_p2;
reg    ap_block_state4_on_subcall_done;
reg   [2:0] c_fu_108;
wire   [31:0] bytes_cast_fu_255_p1;
wire   [31:0] add_ln1226_fu_259_p2;
wire   [7:0] zext_ln1231_fu_297_p1;
wire   [0:0] icmp_ln1233_fu_315_p2;
wire   [0:0] tmp_546_fu_301_p3;
wire   [0:0] xor_ln1233_fu_320_p2;
wire   [0:0] or_ln1231_fu_326_p2;
wire   [31:0] tmp_fu_351_p9;
wire   [1:0] tmp_fu_351_p10;
wire   [31:0] tmp_fu_351_p11;
wire   [31:0] room_fu_391_p2;
wire   [0:0] icmp_ln1240_fu_397_p2;
reg   [0:0] ap_return_preg;
wire    ap_CS_fsm_state5;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire   [1:0] tmp_fu_351_p1;
wire   [1:0] tmp_fu_351_p3;
wire  signed [1:0] tmp_fu_351_p5;
wire  signed [1:0] tmp_fu_351_p7;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_ap_start_reg = 1'b0;
#0 copied_fu_116 = 32'd0;
#0 remaining_fu_112 = 32'd0;
#0 logical_fu_104 = 32'd0;
#0 c_fu_108 = 3'd0;
#0 ap_return_preg = 1'd0;
end

transformer_top_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2 grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_ap_start),
    .ap_done(grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_ap_done),
    .ap_idle(grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_ap_idle),
    .ap_ready(grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_ap_ready),
    .copied(copied_load_reg_544),
    .logical(logical_load_reg_530),
    .take(take_reg_549),
    .r_chunks_offset_read(r_chunks_offset_read),
    .r_chunks_offset_read_28(r_chunks_offset_read_28),
    .r_chunks_offset_read_29(r_chunks_offset_read_29),
    .r_chunks_offset_read_30(r_chunks_offset_read_30),
    .empty(trunc_ln1231_reg_535),
    .r_chunks_bank_read(r_chunks_bank_read),
    .r_chunks_bank_read_28(r_chunks_bank_read_28),
    .r_chunks_bank_read_29(r_chunks_bank_read_29),
    .r_chunks_bank_read_30(r_chunks_bank_read_30),
    .copied_6_out(grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_copied_6_out),
    .copied_6_out_ap_vld(grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_copied_6_out_ap_vld),
    .remaining_1_out_i(remaining_fu_112),
    .remaining_1_out_o(grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_remaining_1_out_o),
    .remaining_1_out_o_ap_vld(grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_remaining_1_out_o_ap_vld),
    .p_ZN12_GLOBAL_N_17scratchE_1_address0(grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_p_ZN12_GLOBAL_N_17scratchE_1_address0),
    .p_ZN12_GLOBAL_N_17scratchE_1_ce0(grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_p_ZN12_GLOBAL_N_17scratchE_1_ce0),
    .p_ZN12_GLOBAL_N_17scratchE_1_we0(grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_p_ZN12_GLOBAL_N_17scratchE_1_we0),
    .p_ZN12_GLOBAL_N_17scratchE_1_d0(grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_p_ZN12_GLOBAL_N_17scratchE_1_d0),
    .p_ZN12_GLOBAL_N_17scratchE_2_address0(grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_p_ZN12_GLOBAL_N_17scratchE_2_address0),
    .p_ZN12_GLOBAL_N_17scratchE_2_ce0(grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_p_ZN12_GLOBAL_N_17scratchE_2_ce0),
    .p_ZN12_GLOBAL_N_17scratchE_2_we0(grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_p_ZN12_GLOBAL_N_17scratchE_2_we0),
    .p_ZN12_GLOBAL_N_17scratchE_2_d0(grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_p_ZN12_GLOBAL_N_17scratchE_2_d0),
    .p_ZN12_GLOBAL_N_17scratchE_3_address0(grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_p_ZN12_GLOBAL_N_17scratchE_3_address0),
    .p_ZN12_GLOBAL_N_17scratchE_3_ce0(grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_p_ZN12_GLOBAL_N_17scratchE_3_ce0),
    .p_ZN12_GLOBAL_N_17scratchE_3_we0(grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_p_ZN12_GLOBAL_N_17scratchE_3_we0),
    .p_ZN12_GLOBAL_N_17scratchE_3_d0(grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_p_ZN12_GLOBAL_N_17scratchE_3_d0),
    .p_ZN12_GLOBAL_N_17scratchE_0_address0(grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_p_ZN12_GLOBAL_N_17scratchE_0_address0),
    .p_ZN12_GLOBAL_N_17scratchE_0_ce0(grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_p_ZN12_GLOBAL_N_17scratchE_0_ce0),
    .p_ZN12_GLOBAL_N_17scratchE_0_we0(grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_p_ZN12_GLOBAL_N_17scratchE_0_we0),
    .p_ZN12_GLOBAL_N_17scratchE_0_d0(grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_p_ZN12_GLOBAL_N_17scratchE_0_d0),
    .p_anonymous_namespace_uram_banks_address0(grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_p_anonymous_namespace_uram_banks_address0),
    .p_anonymous_namespace_uram_banks_ce0(grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_p_anonymous_namespace_uram_banks_ce0),
    .p_anonymous_namespace_uram_banks_q0(p_anonymous_namespace_uram_banks_q0)
);

(* dissolve_hierarchy = "yes" *) transformer_top_sparsemux_9_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_9_2_32_1_1_U3733(
    .din0(r_chunks_size_read),
    .din1(r_chunks_size_read_28),
    .din2(r_chunks_size_read_29),
    .din3(r_chunks_size_read_30),
    .def(tmp_fu_351_p9),
    .sel(tmp_fu_351_p10),
    .dout(tmp_fu_351_p11)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_preg <= 1'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            ap_return_preg <= retval_0_reg_216;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state3) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_ap_start_reg <= 1'b1;
        end else if ((grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_ap_ready == 1'b1)) begin
            grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (icmp_ln1226_fu_265_p2 == 1'd0) & (ap_start == 1'b1))) begin
        c_fu_108 <= 3'd0;
    end else if (((1'b0 == ap_block_state4_on_subcall_done) & (1'b1 == ap_CS_fsm_state4))) begin
        c_fu_108 <= add_ln1231_reg_525;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (icmp_ln1226_fu_265_p2 == 1'd0) & (ap_start == 1'b1))) begin
        copied_fu_116 <= 32'd0;
    end else if (((1'b1 == ap_CS_fsm_state4) & (grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_copied_6_out_ap_vld == 1'b1) & (icmp_ln1235_reg_540 == 1'd1))) begin
        copied_fu_116 <= grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_copied_6_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (icmp_ln1226_fu_265_p2 == 1'd0) & (ap_start == 1'b1))) begin
        logical_fu_104 <= src_offset;
    end else if (((1'b1 == ap_CS_fsm_state2) & (or_ln1231_2_fu_332_p2 == 1'd0) & (icmp_ln1235_fu_371_p2 == 1'd0))) begin
        logical_fu_104 <= logical_26_fu_377_p2;
    end else if (((1'b0 == ap_block_state4_on_subcall_done) & (1'b1 == ap_CS_fsm_state4) & (icmp_ln1235_reg_540 == 1'd1))) begin
        logical_fu_104 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (icmp_ln1226_fu_265_p2 == 1'd0) & (ap_start == 1'b1))) begin
        remaining_fu_112 <= bytes_cast_fu_255_p1;
    end else if (((1'b1 == ap_CS_fsm_state4) & (grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_remaining_1_out_o_ap_vld == 1'b1) & (icmp_ln1235_reg_540 == 1'd1))) begin
        remaining_fu_112 <= grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_remaining_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (or_ln1231_2_fu_332_p2 == 1'd1))) begin
        retval_0_reg_216 <= icmp_ln1231_fu_309_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (icmp_ln1226_fu_265_p2 == 1'd1) & (ap_start == 1'b1))) begin
        retval_0_reg_216 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln1231_reg_525 <= add_ln1231_fu_338_p2;
        copied_load_reg_544 <= copied_fu_116;
        icmp_ln1235_reg_540 <= icmp_ln1235_fu_371_p2;
        logical_load_reg_530 <= logical_fu_104;
        take_reg_549 <= take_fu_403_p3;
        trunc_ln1231_reg_535 <= trunc_ln1231_fu_347_p1;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state4_on_subcall_done)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_return = retval_0_reg_216;
    end else begin
        ap_return = ap_return_preg;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (icmp_ln1226_fu_265_p2 == 1'd0) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else if (((1'b1 == ap_CS_fsm_state1) & (icmp_ln1226_fu_265_p2 == 1'd1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (or_ln1231_2_fu_332_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else if (((1'b1 == ap_CS_fsm_state2) & (or_ln1231_2_fu_332_p2 == 1'd0) & (icmp_ln1235_fu_371_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b0 == ap_block_state4_on_subcall_done) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1226_fu_259_p2 = (bytes_cast_fu_255_p1 + src_offset);

assign add_ln1231_fu_338_p2 = (c_fu_108 + 3'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_NS_fsm_state3 = ap_NS_fsm[32'd2];

always @ (*) begin
    ap_block_state4_on_subcall_done = ((grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_ap_done == 1'b0) & (icmp_ln1235_reg_540 == 1'd1));
end

assign bytes_cast_fu_255_p1 = bytes;

assign grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_ap_start = grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_ap_start_reg;

assign icmp_ln1226_fu_265_p2 = ((add_ln1226_fu_259_p2 > r_total_bytes_val) ? 1'b1 : 1'b0);

assign icmp_ln1231_fu_309_p2 = ((remaining_fu_112 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln1233_fu_315_p2 = ((zext_ln1231_fu_297_p1 < r_num_chunks_read) ? 1'b1 : 1'b0);

assign icmp_ln1235_fu_371_p2 = ((logical_fu_104 < tmp_fu_351_p11) ? 1'b1 : 1'b0);

assign icmp_ln1240_fu_397_p2 = ((remaining_fu_112 < room_fu_391_p2) ? 1'b1 : 1'b0);

assign logical_26_fu_377_p2 = (logical_fu_104 - tmp_fu_351_p11);

assign or_ln1231_2_fu_332_p2 = (or_ln1231_fu_326_p2 | icmp_ln1231_fu_309_p2);

assign or_ln1231_fu_326_p2 = (xor_ln1233_fu_320_p2 | tmp_546_fu_301_p3);

assign p_ZN12_GLOBAL_N_17scratchE_0_address0 = grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_p_ZN12_GLOBAL_N_17scratchE_0_address0;

assign p_ZN12_GLOBAL_N_17scratchE_0_ce0 = grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_p_ZN12_GLOBAL_N_17scratchE_0_ce0;

assign p_ZN12_GLOBAL_N_17scratchE_0_d0 = grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_p_ZN12_GLOBAL_N_17scratchE_0_d0;

assign p_ZN12_GLOBAL_N_17scratchE_0_we0 = grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_p_ZN12_GLOBAL_N_17scratchE_0_we0;

assign p_ZN12_GLOBAL_N_17scratchE_1_address0 = grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_p_ZN12_GLOBAL_N_17scratchE_1_address0;

assign p_ZN12_GLOBAL_N_17scratchE_1_ce0 = grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_p_ZN12_GLOBAL_N_17scratchE_1_ce0;

assign p_ZN12_GLOBAL_N_17scratchE_1_d0 = grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_p_ZN12_GLOBAL_N_17scratchE_1_d0;

assign p_ZN12_GLOBAL_N_17scratchE_1_we0 = grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_p_ZN12_GLOBAL_N_17scratchE_1_we0;

assign p_ZN12_GLOBAL_N_17scratchE_2_address0 = grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_p_ZN12_GLOBAL_N_17scratchE_2_address0;

assign p_ZN12_GLOBAL_N_17scratchE_2_ce0 = grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_p_ZN12_GLOBAL_N_17scratchE_2_ce0;

assign p_ZN12_GLOBAL_N_17scratchE_2_d0 = grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_p_ZN12_GLOBAL_N_17scratchE_2_d0;

assign p_ZN12_GLOBAL_N_17scratchE_2_we0 = grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_p_ZN12_GLOBAL_N_17scratchE_2_we0;

assign p_ZN12_GLOBAL_N_17scratchE_3_address0 = grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_p_ZN12_GLOBAL_N_17scratchE_3_address0;

assign p_ZN12_GLOBAL_N_17scratchE_3_ce0 = grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_p_ZN12_GLOBAL_N_17scratchE_3_ce0;

assign p_ZN12_GLOBAL_N_17scratchE_3_d0 = grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_p_ZN12_GLOBAL_N_17scratchE_3_d0;

assign p_ZN12_GLOBAL_N_17scratchE_3_we0 = grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_p_ZN12_GLOBAL_N_17scratchE_3_we0;

assign p_anonymous_namespace_uram_banks_address0 = grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_p_anonymous_namespace_uram_banks_address0;

assign p_anonymous_namespace_uram_banks_ce0 = grp_p_anonymous_namespace_region_read_bytes_5_Pipeline_VITIS_LOOP_1241_2_fu_227_p_anonymous_namespace_uram_banks_ce0;

assign room_fu_391_p2 = (tmp_fu_351_p11 - logical_fu_104);

assign take_fu_403_p3 = ((icmp_ln1240_fu_397_p2[0:0] == 1'b1) ? remaining_fu_112 : room_fu_391_p2);

assign tmp_546_fu_301_p3 = c_fu_108[32'd2];

assign tmp_fu_351_p10 = c_fu_108[1:0];

assign tmp_fu_351_p9 = 'bx;

assign trunc_ln1231_fu_347_p1 = c_fu_108[1:0];

assign xor_ln1233_fu_320_p2 = (icmp_ln1233_fu_315_p2 ^ 1'd1);

assign zext_ln1231_fu_297_p1 = c_fu_108;

endmodule //transformer_top_p_anonymous_namespace_region_read_bytes_5
