set SynModuleInfo {
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_367_4 MODELNAME compute_controller_Pipeline_VITIS_LOOP_367_4 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_367_4
    SUBMODULES {
      {MODELNAME compute_controller_flow_control_loop_pipe_sequential_init RTLNAME compute_controller_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME compute_controller_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_372_5 MODELNAME compute_controller_Pipeline_VITIS_LOOP_372_5 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_372_5}
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_378_6_VITIS_LOOP_379_7 MODELNAME compute_controller_Pipeline_VITIS_LOOP_378_6_VITIS_LOOP_379_7 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_378_6_VITIS_LOOP_379_7}
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_391_8 MODELNAME compute_controller_Pipeline_VITIS_LOOP_391_8 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_391_8}
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_395_9 MODELNAME compute_controller_Pipeline_VITIS_LOOP_395_9 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_395_9}
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_407_10 MODELNAME compute_controller_Pipeline_VITIS_LOOP_407_10 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_407_10}
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_43_2 MODELNAME compute_controller_Pipeline_VITIS_LOOP_43_2 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_43_2
    SUBMODULES {
      {MODELNAME compute_controller_mul_8s_4s_12_1_1 RTLNAME compute_controller_mul_8s_4s_12_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME compute_controller_mac_muladd_8s_4s_12s_32_4_1 RTLNAME compute_controller_mac_muladd_8s_4s_12s_32_4_1 BINDTYPE op TYPE all IMPL dsp_slice LATENCY 3}
    }
  }
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_43_21 MODELNAME compute_controller_Pipeline_VITIS_LOOP_43_21 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_43_21}
  {SRCNAME compute_controller MODELNAME compute_controller RTLNAME compute_controller IS_TOP 1
    SUBMODULES {
      {MODELNAME compute_controller_mul_7s_6ns_7_1_1 RTLNAME compute_controller_mul_7s_6ns_7_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME compute_controller_mul_6s_5ns_6_1_1 RTLNAME compute_controller_mul_6s_5ns_6_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME compute_controller_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_3_RAM_AUbkb RTLNAME compute_controller_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_3_RAM_AUbkb BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME compute_controller_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_9_RAM_AUfYi RTLNAME compute_controller_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_9_RAM_AUfYi BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME compute_controller_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_11_RAM_AjbC RTLNAME compute_controller_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_11_RAM_AjbC BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME compute_controller_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_10_RAM_AkbM RTLNAME compute_controller_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_10_RAM_AkbM BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME compute_controller_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_5_RAM_AUlbW RTLNAME compute_controller_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_5_RAM_AUlbW BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
}
