set SynModuleInfo {
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_375_4 MODELNAME compute_controller_Pipeline_VITIS_LOOP_375_4 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_375_4
    SUBMODULES {
      {MODELNAME compute_controller_flow_control_loop_pipe_sequential_init RTLNAME compute_controller_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME compute_controller_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_384_6_VITIS_LOOP_385_7 MODELNAME compute_controller_Pipeline_VITIS_LOOP_384_6_VITIS_LOOP_385_7 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_384_6_VITIS_LOOP_385_7}
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_397_8 MODELNAME compute_controller_Pipeline_VITIS_LOOP_397_8 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_397_8}
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_413_10 MODELNAME compute_controller_Pipeline_VITIS_LOOP_413_10 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_413_10
    SUBMODULES {
      {MODELNAME compute_controller_sparsemux_33_4_19_1_1 RTLNAME compute_controller_sparsemux_33_4_19_1_1 BINDTYPE op TYPE sparsemux IMPL compactencoding_dontcare}
    }
  }
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_47_2 MODELNAME compute_controller_Pipeline_VITIS_LOOP_47_2 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_47_2
    SUBMODULES {
      {MODELNAME compute_controller_mul_8s_4s_12_1_1 RTLNAME compute_controller_mul_8s_4s_12_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME compute_controller_mac_muladd_8s_4s_12s_13_4_1 RTLNAME compute_controller_mac_muladd_8s_4s_12s_13_4_1 BINDTYPE op TYPE all IMPL dsp_slice LATENCY 3}
    }
  }
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_47_21 MODELNAME compute_controller_Pipeline_VITIS_LOOP_47_21 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_47_21}
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_47_22 MODELNAME compute_controller_Pipeline_VITIS_LOOP_47_22 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_47_22}
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_47_23 MODELNAME compute_controller_Pipeline_VITIS_LOOP_47_23 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_47_23}
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_47_24 MODELNAME compute_controller_Pipeline_VITIS_LOOP_47_24 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_47_24}
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_47_25 MODELNAME compute_controller_Pipeline_VITIS_LOOP_47_25 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_47_25}
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_47_26 MODELNAME compute_controller_Pipeline_VITIS_LOOP_47_26 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_47_26}
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_47_27 MODELNAME compute_controller_Pipeline_VITIS_LOOP_47_27 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_47_27}
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_47_28 MODELNAME compute_controller_Pipeline_VITIS_LOOP_47_28 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_47_28}
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_47_29 MODELNAME compute_controller_Pipeline_VITIS_LOOP_47_29 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_47_29}
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_47_210 MODELNAME compute_controller_Pipeline_VITIS_LOOP_47_210 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_47_210}
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_47_211 MODELNAME compute_controller_Pipeline_VITIS_LOOP_47_211 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_47_211}
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_47_212 MODELNAME compute_controller_Pipeline_VITIS_LOOP_47_212 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_47_212}
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_47_213 MODELNAME compute_controller_Pipeline_VITIS_LOOP_47_213 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_47_213}
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_47_214 MODELNAME compute_controller_Pipeline_VITIS_LOOP_47_214 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_47_214}
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_47_215 MODELNAME compute_controller_Pipeline_VITIS_LOOP_47_215 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_47_215}
  {SRCNAME compute_controller MODELNAME compute_controller RTLNAME compute_controller IS_TOP 1
    SUBMODULES {
      {MODELNAME compute_controller_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_9_RAM_AUbkb RTLNAME compute_controller_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_9_RAM_AUbkb BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME compute_controller_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_29_RAM_ArcU RTLNAME compute_controller_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_29_RAM_ArcU BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME compute_controller_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_39_RAM_AHfu RTLNAME compute_controller_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_39_RAM_AHfu BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME compute_controller_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_19_RAM_AXh4 RTLNAME compute_controller_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_19_RAM_AXh4 BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
}
