set SynModuleInfo {
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_624_35 MODELNAME compute_controller_Pipeline_VITIS_LOOP_624_35 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_624_35
    SUBMODULES {
      {MODELNAME compute_controller_flow_control_loop_pipe_sequential_init RTLNAME compute_controller_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME compute_controller_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_629_36 MODELNAME compute_controller_Pipeline_VITIS_LOOP_629_36 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_629_36}
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_633_37_VITIS_LOOP_634_38 MODELNAME compute_controller_Pipeline_VITIS_LOOP_633_37_VITIS_LOOP_634_38 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_633_37_VITIS_LOOP_634_38
    SUBMODULES {
      {MODELNAME compute_controller_mac_muladd_6ns_5ns_8ns_9_4_1 RTLNAME compute_controller_mac_muladd_6ns_5ns_8ns_9_4_1 BINDTYPE op TYPE all IMPL dsp_slice LATENCY 3}
    }
  }
  {SRCNAME read_i32 MODELNAME read_i32 RTLNAME compute_controller_read_i32}
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_646_39 MODELNAME compute_controller_Pipeline_VITIS_LOOP_646_39 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_646_39}
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_650_40 MODELNAME compute_controller_Pipeline_VITIS_LOOP_650_40 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_650_40}
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_654_41 MODELNAME compute_controller_Pipeline_VITIS_LOOP_654_41 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_654_41}
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_658_42 MODELNAME compute_controller_Pipeline_VITIS_LOOP_658_42 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_658_42}
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_667_43 MODELNAME compute_controller_Pipeline_VITIS_LOOP_667_43 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_667_43
    SUBMODULES {
      {MODELNAME compute_controller_mul_32s_16s_48_1_1 RTLNAME compute_controller_mul_32s_16s_48_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME compute_controller_sparsemux_11_3_32_1_1 RTLNAME compute_controller_sparsemux_11_3_32_1_1 BINDTYPE op TYPE sparsemux IMPL compactencoding_dontcare}
      {MODELNAME compute_controller_sparsemux_11_3_16_1_1 RTLNAME compute_controller_sparsemux_11_3_16_1_1 BINDTYPE op TYPE sparsemux IMPL compactencoding_dontcare}
    }
  }
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_608_33 MODELNAME compute_controller_Pipeline_VITIS_LOOP_608_33 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_608_33}
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_137_1 MODELNAME compute_controller_Pipeline_VITIS_LOOP_137_1 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_137_1
    SUBMODULES {
      {MODELNAME compute_controller_sparsemux_33_4_16_1_1 RTLNAME compute_controller_sparsemux_33_4_16_1_1 BINDTYPE op TYPE sparsemux IMPL compactencoding_dontcare}
    }
  }
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_616_34 MODELNAME compute_controller_Pipeline_VITIS_LOOP_616_34 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_616_34
    SUBMODULES {
      {MODELNAME compute_controller_sparsemux_33_4_15_1_1 RTLNAME compute_controller_sparsemux_33_4_15_1_1 BINDTYPE op TYPE sparsemux IMPL compactencoding_dontcare}
    }
  }
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_545_24 MODELNAME compute_controller_Pipeline_VITIS_LOOP_545_24 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_545_24}
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_554_26_VITIS_LOOP_555_27 MODELNAME compute_controller_Pipeline_VITIS_LOOP_554_26_VITIS_LOOP_555_27 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_554_26_VITIS_LOOP_555_27}
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_567_28 MODELNAME compute_controller_Pipeline_VITIS_LOOP_567_28 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_567_28}
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_575_30 MODELNAME compute_controller_Pipeline_VITIS_LOOP_575_30 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_575_30}
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_590_32 MODELNAME compute_controller_Pipeline_VITIS_LOOP_590_32 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_590_32
    SUBMODULES {
      {MODELNAME compute_controller_sparsemux_33_4_32_1_1 RTLNAME compute_controller_sparsemux_33_4_32_1_1 BINDTYPE op TYPE sparsemux IMPL compactencoding_dontcare}
    }
  }
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_518_22 MODELNAME compute_controller_Pipeline_VITIS_LOOP_518_22 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_518_22}
  {SRCNAME LAYER_NORM_Pipeline_VITIS_LOOP_105_1 MODELNAME LAYER_NORM_Pipeline_VITIS_LOOP_105_1 RTLNAME compute_controller_LAYER_NORM_Pipeline_VITIS_LOOP_105_1
    SUBMODULES {
      {MODELNAME compute_controller_sparsemux_33_4_8_1_1 RTLNAME compute_controller_sparsemux_33_4_8_1_1 BINDTYPE op TYPE sparsemux IMPL compactencoding_dontcare}
      {MODELNAME compute_controller_mac_muladd_8s_8s_23s_23_4_1 RTLNAME compute_controller_mac_muladd_8s_8s_23s_23_4_1 BINDTYPE op TYPE all IMPL dsp_slice LATENCY 3}
    }
  }
  {SRCNAME {sqrt_fixed<32, 16>} MODELNAME sqrt_fixed_32_16_s RTLNAME compute_controller_sqrt_fixed_32_16_s}
  {SRCNAME LAYER_NORM MODELNAME LAYER_NORM RTLNAME compute_controller_LAYER_NORM
    SUBMODULES {
      {MODELNAME compute_controller_mul_25s_25s_48_1_1 RTLNAME compute_controller_mul_25s_25s_48_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME compute_controller_mul_26s_32s_48_1_1 RTLNAME compute_controller_mul_26s_32s_48_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME compute_controller_mul_32s_32s_48_1_1 RTLNAME compute_controller_mul_32s_32s_48_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME compute_controller_mul_32s_34ns_65_1_1 RTLNAME compute_controller_mul_32s_34ns_65_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME compute_controller_udiv_33s_24ns_32_37_seq_1 RTLNAME compute_controller_udiv_33s_24ns_32_37_seq_1 BINDTYPE op TYPE udiv IMPL auto_seq LATENCY 36 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_537_23 MODELNAME compute_controller_Pipeline_VITIS_LOOP_537_23 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_537_23}
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_498_20 MODELNAME compute_controller_Pipeline_VITIS_LOOP_498_20 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_498_20}
  {SRCNAME RES_ADD MODELNAME RES_ADD RTLNAME compute_controller_RES_ADD}
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_509_21 MODELNAME compute_controller_Pipeline_VITIS_LOOP_509_21 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_509_21}
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_474_18 MODELNAME compute_controller_Pipeline_VITIS_LOOP_474_18 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_474_18}
  {SRCNAME REQUANT_D_MODEL_int32_to_int8 MODELNAME REQUANT_D_MODEL_int32_to_int8 RTLNAME compute_controller_REQUANT_D_MODEL_int32_to_int8
    SUBMODULES {
      {MODELNAME compute_controller_mul_32s_32s_64_1_1 RTLNAME compute_controller_mul_32s_32s_64_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_489_19 MODELNAME compute_controller_Pipeline_VITIS_LOOP_489_19 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_489_19}
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_424_11 MODELNAME compute_controller_Pipeline_VITIS_LOOP_424_11 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_424_11}
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_433_13_VITIS_LOOP_434_14 MODELNAME compute_controller_Pipeline_VITIS_LOOP_433_13_VITIS_LOOP_434_14 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_433_13_VITIS_LOOP_434_14}
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_446_15 MODELNAME compute_controller_Pipeline_VITIS_LOOP_446_15 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_446_15}
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_461_17 MODELNAME compute_controller_Pipeline_VITIS_LOOP_461_17 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_461_17}
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_41_2 MODELNAME compute_controller_Pipeline_VITIS_LOOP_41_2 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_41_2
    SUBMODULES {
      {MODELNAME compute_controller_mul_16s_4s_20_1_1 RTLNAME compute_controller_mul_16s_4s_20_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME compute_controller_mac_muladd_16s_4s_20s_21_4_1 RTLNAME compute_controller_mac_muladd_16s_4s_20s_21_4_1 BINDTYPE op TYPE all IMPL dsp_slice LATENCY 3}
    }
  }
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_41_21 MODELNAME compute_controller_Pipeline_VITIS_LOOP_41_21 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_41_21}
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_41_22 MODELNAME compute_controller_Pipeline_VITIS_LOOP_41_22 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_41_22}
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_41_23 MODELNAME compute_controller_Pipeline_VITIS_LOOP_41_23 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_41_23}
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_41_24 MODELNAME compute_controller_Pipeline_VITIS_LOOP_41_24 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_41_24}
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_41_25 MODELNAME compute_controller_Pipeline_VITIS_LOOP_41_25 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_41_25}
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_41_26 MODELNAME compute_controller_Pipeline_VITIS_LOOP_41_26 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_41_26}
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_41_27 MODELNAME compute_controller_Pipeline_VITIS_LOOP_41_27 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_41_27}
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_41_28 MODELNAME compute_controller_Pipeline_VITIS_LOOP_41_28 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_41_28}
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_41_29 MODELNAME compute_controller_Pipeline_VITIS_LOOP_41_29 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_41_29}
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_41_210 MODELNAME compute_controller_Pipeline_VITIS_LOOP_41_210 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_41_210}
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_41_211 MODELNAME compute_controller_Pipeline_VITIS_LOOP_41_211 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_41_211}
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_41_212 MODELNAME compute_controller_Pipeline_VITIS_LOOP_41_212 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_41_212}
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_41_213 MODELNAME compute_controller_Pipeline_VITIS_LOOP_41_213 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_41_213}
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_41_214 MODELNAME compute_controller_Pipeline_VITIS_LOOP_41_214 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_41_214}
  {SRCNAME compute_controller_Pipeline_VITIS_LOOP_41_215 MODELNAME compute_controller_Pipeline_VITIS_LOOP_41_215 RTLNAME compute_controller_compute_controller_Pipeline_VITIS_LOOP_41_215}
  {SRCNAME compute_controller MODELNAME compute_controller RTLNAME compute_controller IS_TOP 1
    SUBMODULES {
      {MODELNAME compute_controller_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_59_RAM_Abkb RTLNAME compute_controller_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_59_RAM_Abkb BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME compute_controller_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_99_RAM_ArcU RTLNAME compute_controller_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_99_RAM_ArcU BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME compute_controller_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_149_RAM_Hfu RTLNAME compute_controller_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_149_RAM_Hfu BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME compute_controller_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_69_RAM_AXh4 RTLNAME compute_controller_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_69_RAM_AXh4 BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME compute_controller_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_178_RAM_bdk RTLNAME compute_controller_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_178_RAM_bdk BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME compute_controller_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_172_RAM_bjl RTLNAME compute_controller_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_172_RAM_bjl BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME compute_controller_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_168_RAM_btn RTLNAME compute_controller_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_168_RAM_btn BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME compute_controller_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_162_RAM_bzo RTLNAME compute_controller_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_162_RAM_bzo BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME compute_controller_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_40_RAM_AbZs RTLNAME compute_controller_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_40_RAM_AbZs BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME compute_controller_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_20_RAM_Acfu RTLNAME compute_controller_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_20_RAM_Acfu BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME compute_controller_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_39_RAM_Acvx RTLNAME compute_controller_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_39_RAM_Acvx BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME compute_controller_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_189_RAM_dhF RTLNAME compute_controller_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_189_RAM_dhF BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
}
