

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "4", "15", "16", "42", "44", "55"],
		"CDFG" : "compute_controller",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "1", "EstimateLatencyMax" : "79",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "reset", "Type" : "None", "Direction" : "I"},
			{"Name" : "compute_start", "Type" : "None", "Direction" : "I"},
			{"Name" : "compute_instruction", "Type" : "None", "Direction" : "I"},
			{"Name" : "compute_ready", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "compute_done", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "mem_transfer_done", "Type" : "None", "Direction" : "I"},
			{"Name" : "mem_read_request", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "mem_write_request", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "mem_op", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "int8_activation", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "4", "SubInstance" : "grp_LAYER_NORM_fu_599", "Port" : "int8_activation", "Inst_start_state" : "1", "Inst_end_state" : "9"},
					{"ID" : "15", "SubInstance" : "grp_RES_ADD_fu_612", "Port" : "int8_activation", "Inst_start_state" : "1", "Inst_end_state" : "9"},
					{"ID" : "55", "SubInstance" : "grp_OUT_PROJ_fu_666", "Port" : "int8_activation", "Inst_start_state" : "10", "Inst_end_state" : "11"}]},
			{"Name" : "OUT_PROJ_valueB", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "55", "SubInstance" : "grp_OUT_PROJ_fu_666", "Port" : "OUT_PROJ_valueB", "Inst_start_state" : "10", "Inst_end_state" : "11"}]},
			{"Name" : "OUT_PROJ_bias", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "OUT_PROJ_accum", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "55", "SubInstance" : "grp_OUT_PROJ_fu_666", "Port" : "OUT_PROJ_accum", "Inst_start_state" : "10", "Inst_end_state" : "11"}]},
			{"Name" : "FFN1_weights1", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "44", "SubInstance" : "grp_compute_controller_Pipeline_VITIS_LOOP_113_1_fu_644", "Port" : "FFN1_weights1", "Inst_start_state" : "7", "Inst_end_state" : "8"}]},
			{"Name" : "FFN1_biases", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "44", "SubInstance" : "grp_compute_controller_Pipeline_VITIS_LOOP_113_1_fu_644", "Port" : "FFN1_biases", "Inst_start_state" : "7", "Inst_end_state" : "8"}]},
			{"Name" : "FFN1_scale", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "44", "SubInstance" : "grp_compute_controller_Pipeline_VITIS_LOOP_113_1_fu_644", "Port" : "FFN1_scale", "Inst_start_state" : "7", "Inst_end_state" : "8"}]},
			{"Name" : "FFN1_output", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "44", "SubInstance" : "grp_compute_controller_Pipeline_VITIS_LOOP_113_1_fu_644", "Port" : "FFN1_output", "Inst_start_state" : "7", "Inst_end_state" : "8"}]},
			{"Name" : "RELU_input", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "42", "SubInstance" : "grp_compute_controller_Pipeline_VITIS_LOOP_132_1_fu_636", "Port" : "RELU_input", "Inst_start_state" : "1", "Inst_end_state" : "3"}]},
			{"Name" : "RELU_output", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "42", "SubInstance" : "grp_compute_controller_Pipeline_VITIS_LOOP_132_1_fu_636", "Port" : "RELU_output", "Inst_start_state" : "1", "Inst_end_state" : "3"}]},
			{"Name" : "FFN2_input", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "16", "SubInstance" : "grp_FFN_POST_ACT_fu_622", "Port" : "FFN2_input", "Inst_start_state" : "1", "Inst_end_state" : "3"}]},
			{"Name" : "FFN2_weights2", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "16", "SubInstance" : "grp_FFN_POST_ACT_fu_622", "Port" : "FFN2_weights2", "Inst_start_state" : "1", "Inst_end_state" : "3"}]},
			{"Name" : "FFN2_biases", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "16", "SubInstance" : "grp_FFN_POST_ACT_fu_622", "Port" : "FFN2_biases", "Inst_start_state" : "1", "Inst_end_state" : "3"}]},
			{"Name" : "FFN2_scale", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "16", "SubInstance" : "grp_FFN_POST_ACT_fu_622", "Port" : "FFN2_scale", "Inst_start_state" : "1", "Inst_end_state" : "3"}]},
			{"Name" : "FFN2_output", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "16", "SubInstance" : "grp_FFN_POST_ACT_fu_622", "Port" : "FFN2_output", "Inst_start_state" : "1", "Inst_end_state" : "3"}]},
			{"Name" : "requant_activation", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_REQUANT_D_MODEL_int32_to_int8_fu_585", "Port" : "requant_activation", "Inst_start_state" : "1", "Inst_end_state" : "9"}]},
			{"Name" : "requant_scale", "Type" : "None", "Direction" : "I"},
			{"Name" : "requant_shift", "Type" : "None", "Direction" : "I"},
			{"Name" : "requant_zero_point", "Type" : "None", "Direction" : "I"},
			{"Name" : "requant_output", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_REQUANT_D_MODEL_int32_to_int8_fu_585", "Port" : "requant_output", "Inst_start_state" : "1", "Inst_end_state" : "9"}]},
			{"Name" : "layerNorm_gamma", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "4", "SubInstance" : "grp_LAYER_NORM_fu_599", "Port" : "layerNorm_gamma", "Inst_start_state" : "1", "Inst_end_state" : "9"}]},
			{"Name" : "layerNorm_beta", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "4", "SubInstance" : "grp_LAYER_NORM_fu_599", "Port" : "layerNorm_beta", "Inst_start_state" : "1", "Inst_end_state" : "9"}]},
			{"Name" : "layerNorm_epsilon", "Type" : "None", "Direction" : "I"},
			{"Name" : "layerNorm_out", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "4", "SubInstance" : "grp_LAYER_NORM_fu_599", "Port" : "layerNorm_out", "Inst_start_state" : "1", "Inst_end_state" : "9"}]},
			{"Name" : "residualAdd_residual", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "15", "SubInstance" : "grp_RES_ADD_fu_612", "Port" : "residualAdd_residual", "Inst_start_state" : "1", "Inst_end_state" : "9"}]},
			{"Name" : "residualAdd_output", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "15", "SubInstance" : "grp_RES_ADD_fu_612", "Port" : "residualAdd_output", "Inst_start_state" : "1", "Inst_end_state" : "9"}]},
			{"Name" : "error", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "state", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "req_instruction", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "req_op", "Type" : "OVld", "Direction" : "IO"}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_REQUANT_D_MODEL_int32_to_int8_fu_585", "Parent" : "0", "Child" : ["2", "3"],
		"CDFG" : "REQUANT_D_MODEL_int32_to_int8",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "5", "EstimateLatencyMax" : "5",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "requant_activation", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "M", "Type" : "None", "Direction" : "I"},
			{"Name" : "n", "Type" : "None", "Direction" : "I"},
			{"Name" : "z_out", "Type" : "None", "Direction" : "I"},
			{"Name" : "requant_output", "Type" : "Memory", "Direction" : "O"}]},
	{"ID" : "2", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_REQUANT_D_MODEL_int32_to_int8_fu_585.mul_32s_32s_64_1_1_U1", "Parent" : "1"},
	{"ID" : "3", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_REQUANT_D_MODEL_int32_to_int8_fu_585.mul_32s_32s_64_1_1_U2", "Parent" : "1"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_LAYER_NORM_fu_599", "Parent" : "0", "Child" : ["5", "8", "9", "10", "11", "12", "13", "14"],
		"CDFG" : "LAYER_NORM",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "65", "EstimateLatencyMax" : "65",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "int8_activation", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "5", "SubInstance" : "grp_LAYER_NORM_Pipeline_VITIS_LOOP_79_1_fu_412", "Port" : "int8_activation", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "layerNorm_gamma", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "layerNorm_beta", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "epsilon", "Type" : "None", "Direction" : "I"},
			{"Name" : "layerNorm_out", "Type" : "Memory", "Direction" : "O"}]},
	{"ID" : "5", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_LAYER_NORM_fu_599.grp_LAYER_NORM_Pipeline_VITIS_LOOP_79_1_fu_412", "Parent" : "4", "Child" : ["6", "7"],
		"CDFG" : "LAYER_NORM_Pipeline_VITIS_LOOP_79_1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "13", "EstimateLatencyMax" : "13",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "int8_activation", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "square_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "sum_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_79_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter4", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter4", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "6", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_LAYER_NORM_fu_599.grp_LAYER_NORM_Pipeline_VITIS_LOOP_79_1_fu_412.mac_muladd_8s_8s_19s_19_4_1_U9", "Parent" : "5"},
	{"ID" : "7", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_LAYER_NORM_fu_599.grp_LAYER_NORM_Pipeline_VITIS_LOOP_79_1_fu_412.flow_control_loop_pipe_sequential_init_U", "Parent" : "5"},
	{"ID" : "8", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_LAYER_NORM_fu_599.grp_sqrt_fixed_32_16_s_fu_420", "Parent" : "4",
		"CDFG" : "sqrt_fixed_32_16_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "0", "ap_start" : "0", "ap_ready" : "0", "ap_done" : "0", "ap_continue" : "0", "ap_idle" : "0", "real_start" : "0",
		"Pipeline" : "Aligned", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "1",
		"VariableLatency" : "0", "ExactLatency" : "6", "EstimateLatencyMin" : "6", "EstimateLatencyMax" : "6",
		"Combinational" : "0",
		"Datapath" : "1",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "x", "Type" : "None", "Direction" : "I"}]},
	{"ID" : "9", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_LAYER_NORM_fu_599.mul_24s_24s_48_1_1_U15", "Parent" : "4"},
	{"ID" : "10", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_LAYER_NORM_fu_599.mul_25s_32s_48_1_1_U16", "Parent" : "4"},
	{"ID" : "11", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_LAYER_NORM_fu_599.mul_25s_32s_48_1_1_U17", "Parent" : "4"},
	{"ID" : "12", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_LAYER_NORM_fu_599.mul_32s_32s_48_1_1_U18", "Parent" : "4"},
	{"ID" : "13", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_LAYER_NORM_fu_599.mul_32s_32s_48_1_1_U19", "Parent" : "4"},
	{"ID" : "14", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_LAYER_NORM_fu_599.udiv_33s_24ns_32_37_seq_1_U20", "Parent" : "4"},
	{"ID" : "15", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_RES_ADD_fu_612", "Parent" : "0",
		"CDFG" : "RES_ADD",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "4", "EstimateLatencyMax" : "4",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "int8_activation", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "residualAdd_residual", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "residualAdd_output", "Type" : "Memory", "Direction" : "O"}]},
	{"ID" : "16", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_FFN_POST_ACT_fu_622", "Parent" : "0", "Child" : ["17"],
		"CDFG" : "FFN_POST_ACT",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "77", "EstimateLatencyMax" : "77",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "FFN2_input", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "FFN2_weights2", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "17", "SubInstance" : "grp_FFN_POST_ACT_Pipeline_VITIS_LOOP_151_1_fu_273", "Port" : "FFN2_weights2", "Inst_start_state" : "12", "Inst_end_state" : "13"}]},
			{"Name" : "FFN2_biases", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "17", "SubInstance" : "grp_FFN_POST_ACT_Pipeline_VITIS_LOOP_151_1_fu_273", "Port" : "FFN2_biases", "Inst_start_state" : "12", "Inst_end_state" : "13"}]},
			{"Name" : "FFN2_scale", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "17", "SubInstance" : "grp_FFN_POST_ACT_Pipeline_VITIS_LOOP_151_1_fu_273", "Port" : "FFN2_scale", "Inst_start_state" : "12", "Inst_end_state" : "13"}]},
			{"Name" : "FFN2_output", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "17", "SubInstance" : "grp_FFN_POST_ACT_Pipeline_VITIS_LOOP_151_1_fu_273", "Port" : "FFN2_output", "Inst_start_state" : "12", "Inst_end_state" : "13"}]}]},
	{"ID" : "17", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_FFN_POST_ACT_fu_622.grp_FFN_POST_ACT_Pipeline_VITIS_LOOP_151_1_fu_273", "Parent" : "16", "Child" : ["18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41"],
		"CDFG" : "FFN_POST_ACT_Pipeline_VITIS_LOOP_151_1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "65", "EstimateLatencyMax" : "65",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "FFN2_biases", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "FFN2_weights2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "FFN2_scale", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "FFN2_input_load_12_cast", "Type" : "None", "Direction" : "I"},
			{"Name" : "FFN2_input_load_11_cast", "Type" : "None", "Direction" : "I"},
			{"Name" : "FFN2_input_load_10_cast", "Type" : "None", "Direction" : "I"},
			{"Name" : "FFN2_input_load_9_cast", "Type" : "None", "Direction" : "I"},
			{"Name" : "FFN2_input_load_8_cast", "Type" : "None", "Direction" : "I"},
			{"Name" : "FFN2_input_load_7_cast", "Type" : "None", "Direction" : "I"},
			{"Name" : "FFN2_input_load_6_cast", "Type" : "None", "Direction" : "I"},
			{"Name" : "FFN2_input_load_5_cast", "Type" : "None", "Direction" : "I"},
			{"Name" : "FFN2_input_load_4_cast", "Type" : "None", "Direction" : "I"},
			{"Name" : "FFN2_input_load_3_cast", "Type" : "None", "Direction" : "I"},
			{"Name" : "FFN2_input_load_2_cast", "Type" : "None", "Direction" : "I"},
			{"Name" : "FFN2_input_load_1_cast", "Type" : "None", "Direction" : "I"},
			{"Name" : "FFN2_input_load_cast", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln151", "Type" : "None", "Direction" : "I"},
			{"Name" : "FFN2_input_load_20_cast", "Type" : "None", "Direction" : "I"},
			{"Name" : "FFN2_input_load_19_cast", "Type" : "None", "Direction" : "I"},
			{"Name" : "FFN2_input_load_18_cast", "Type" : "None", "Direction" : "I"},
			{"Name" : "FFN2_input_load_17_cast", "Type" : "None", "Direction" : "I"},
			{"Name" : "FFN2_input_load_16_cast", "Type" : "None", "Direction" : "I"},
			{"Name" : "FFN2_input_load_15_cast", "Type" : "None", "Direction" : "I"},
			{"Name" : "FFN2_input_load_14_cast", "Type" : "None", "Direction" : "I"},
			{"Name" : "FFN2_input_load_13_cast", "Type" : "None", "Direction" : "I"},
			{"Name" : "FFN2_output", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_151_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "11", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage8", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage8_subdone", "QuitState" : "ap_ST_fsm_pp0_stage8", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage8_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "18", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_FFN_POST_ACT_fu_622.grp_FFN_POST_ACT_Pipeline_VITIS_LOOP_151_1_fu_273.mul_16s_4s_20_1_1_U33", "Parent" : "17"},
	{"ID" : "19", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_FFN_POST_ACT_fu_622.grp_FFN_POST_ACT_Pipeline_VITIS_LOOP_151_1_fu_273.mul_16s_4s_20_1_1_U34", "Parent" : "17"},
	{"ID" : "20", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_FFN_POST_ACT_fu_622.grp_FFN_POST_ACT_Pipeline_VITIS_LOOP_151_1_fu_273.mul_16s_4s_20_1_1_U35", "Parent" : "17"},
	{"ID" : "21", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_FFN_POST_ACT_fu_622.grp_FFN_POST_ACT_Pipeline_VITIS_LOOP_151_1_fu_273.mul_16s_4s_20_1_1_U36", "Parent" : "17"},
	{"ID" : "22", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_FFN_POST_ACT_fu_622.grp_FFN_POST_ACT_Pipeline_VITIS_LOOP_151_1_fu_273.mul_16s_4s_20_1_1_U37", "Parent" : "17"},
	{"ID" : "23", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_FFN_POST_ACT_fu_622.grp_FFN_POST_ACT_Pipeline_VITIS_LOOP_151_1_fu_273.mul_16s_4s_20_1_1_U38", "Parent" : "17"},
	{"ID" : "24", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_FFN_POST_ACT_fu_622.grp_FFN_POST_ACT_Pipeline_VITIS_LOOP_151_1_fu_273.mul_16s_4s_20_1_1_U39", "Parent" : "17"},
	{"ID" : "25", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_FFN_POST_ACT_fu_622.grp_FFN_POST_ACT_Pipeline_VITIS_LOOP_151_1_fu_273.mac_muladd_16s_4s_4s_20_4_1_U40", "Parent" : "17"},
	{"ID" : "26", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_FFN_POST_ACT_fu_622.grp_FFN_POST_ACT_Pipeline_VITIS_LOOP_151_1_fu_273.mac_muladd_16s_4s_20s_21_4_1_U41", "Parent" : "17"},
	{"ID" : "27", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_FFN_POST_ACT_fu_622.grp_FFN_POST_ACT_Pipeline_VITIS_LOOP_151_1_fu_273.mac_muladd_16s_4s_20s_21_4_1_U42", "Parent" : "17"},
	{"ID" : "28", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_FFN_POST_ACT_fu_622.grp_FFN_POST_ACT_Pipeline_VITIS_LOOP_151_1_fu_273.mac_muladd_16s_4s_21s_21_4_1_U43", "Parent" : "17"},
	{"ID" : "29", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_FFN_POST_ACT_fu_622.grp_FFN_POST_ACT_Pipeline_VITIS_LOOP_151_1_fu_273.mac_muladd_16s_4s_21s_21_4_1_U44", "Parent" : "17"},
	{"ID" : "30", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_FFN_POST_ACT_fu_622.grp_FFN_POST_ACT_Pipeline_VITIS_LOOP_151_1_fu_273.mac_muladd_16s_4s_20s_21_4_1_U45", "Parent" : "17"},
	{"ID" : "31", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_FFN_POST_ACT_fu_622.grp_FFN_POST_ACT_Pipeline_VITIS_LOOP_151_1_fu_273.mac_muladd_16s_4s_21s_21_4_1_U46", "Parent" : "17"},
	{"ID" : "32", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_FFN_POST_ACT_fu_622.grp_FFN_POST_ACT_Pipeline_VITIS_LOOP_151_1_fu_273.mac_muladd_16s_4s_20s_21_4_1_U47", "Parent" : "17"},
	{"ID" : "33", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_FFN_POST_ACT_fu_622.grp_FFN_POST_ACT_Pipeline_VITIS_LOOP_151_1_fu_273.mac_muladd_16s_4s_21s_21_4_1_U48", "Parent" : "17"},
	{"ID" : "34", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_FFN_POST_ACT_fu_622.grp_FFN_POST_ACT_Pipeline_VITIS_LOOP_151_1_fu_273.mac_muladd_16s_4s_20s_21_4_1_U49", "Parent" : "17"},
	{"ID" : "35", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_FFN_POST_ACT_fu_622.grp_FFN_POST_ACT_Pipeline_VITIS_LOOP_151_1_fu_273.mac_muladd_16s_4s_21s_21_4_1_U50", "Parent" : "17"},
	{"ID" : "36", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_FFN_POST_ACT_fu_622.grp_FFN_POST_ACT_Pipeline_VITIS_LOOP_151_1_fu_273.mac_muladd_16s_4s_20s_21_4_1_U51", "Parent" : "17"},
	{"ID" : "37", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_FFN_POST_ACT_fu_622.grp_FFN_POST_ACT_Pipeline_VITIS_LOOP_151_1_fu_273.mac_muladd_16s_4s_20s_21_4_1_U52", "Parent" : "17"},
	{"ID" : "38", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_FFN_POST_ACT_fu_622.grp_FFN_POST_ACT_Pipeline_VITIS_LOOP_151_1_fu_273.mac_muladd_16s_4s_21s_21_4_1_U53", "Parent" : "17"},
	{"ID" : "39", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_FFN_POST_ACT_fu_622.grp_FFN_POST_ACT_Pipeline_VITIS_LOOP_151_1_fu_273.mac_muladd_16s_4s_20s_21_4_1_U54", "Parent" : "17"},
	{"ID" : "40", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_FFN_POST_ACT_fu_622.grp_FFN_POST_ACT_Pipeline_VITIS_LOOP_151_1_fu_273.am_addmul_23s_23s_16s_32_4_1_U55", "Parent" : "17"},
	{"ID" : "41", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_FFN_POST_ACT_fu_622.grp_FFN_POST_ACT_Pipeline_VITIS_LOOP_151_1_fu_273.flow_control_loop_pipe_sequential_init_U", "Parent" : "17"},
	{"ID" : "42", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_compute_controller_Pipeline_VITIS_LOOP_132_1_fu_636", "Parent" : "0", "Child" : ["43"],
		"CDFG" : "compute_controller_Pipeline_VITIS_LOOP_132_1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "24", "EstimateLatencyMax" : "24",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "RELU_input", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "RELU_output", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_132_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "43", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_controller_Pipeline_VITIS_LOOP_132_1_fu_636.flow_control_loop_pipe_sequential_init_U", "Parent" : "42"},
	{"ID" : "44", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_compute_controller_Pipeline_VITIS_LOOP_113_1_fu_644", "Parent" : "0", "Child" : ["45", "46", "47", "48", "49", "50", "51", "52", "53", "54"],
		"CDFG" : "compute_controller_Pipeline_VITIS_LOOP_113_1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "15", "EstimateLatencyMax" : "15",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "FFN1_biases", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "FFN1_weights1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "FFN1_scale", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "int8_activation_load_cast", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln113", "Type" : "None", "Direction" : "I"},
			{"Name" : "int8_activation_load_6_cast", "Type" : "None", "Direction" : "I"},
			{"Name" : "int8_activation_load_5_cast", "Type" : "None", "Direction" : "I"},
			{"Name" : "int8_activation_load_4_cast", "Type" : "None", "Direction" : "I"},
			{"Name" : "int8_activation_load_3_cast", "Type" : "None", "Direction" : "I"},
			{"Name" : "int8_activation_load_2_cast", "Type" : "None", "Direction" : "I"},
			{"Name" : "int8_activation_load_1_cast", "Type" : "None", "Direction" : "I"},
			{"Name" : "FFN1_output", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_113_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "4", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage1", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage1_subdone", "QuitState" : "ap_ST_fsm_pp0_stage1", "QuitStateIter" : "ap_enable_reg_pp0_iter2", "QuitStateBlock" : "ap_block_pp0_stage1_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "45", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_controller_Pipeline_VITIS_LOOP_113_1_fu_644.mul_8s_4s_12_1_1_U94", "Parent" : "44"},
	{"ID" : "46", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_controller_Pipeline_VITIS_LOOP_113_1_fu_644.mul_8s_4s_12_1_1_U95", "Parent" : "44"},
	{"ID" : "47", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_controller_Pipeline_VITIS_LOOP_113_1_fu_644.mul_8s_4s_12_1_1_U96", "Parent" : "44"},
	{"ID" : "48", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_controller_Pipeline_VITIS_LOOP_113_1_fu_644.mac_muladd_8s_4s_4s_12_4_1_U97", "Parent" : "44"},
	{"ID" : "49", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_controller_Pipeline_VITIS_LOOP_113_1_fu_644.mac_muladd_8s_4s_12s_13_4_1_U98", "Parent" : "44"},
	{"ID" : "50", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_controller_Pipeline_VITIS_LOOP_113_1_fu_644.mac_muladd_8s_4s_12s_13_4_1_U99", "Parent" : "44"},
	{"ID" : "51", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_controller_Pipeline_VITIS_LOOP_113_1_fu_644.mac_muladd_8s_4s_12s_13_4_1_U100", "Parent" : "44"},
	{"ID" : "52", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_controller_Pipeline_VITIS_LOOP_113_1_fu_644.mac_muladd_8s_4s_12s_13_4_1_U101", "Parent" : "44"},
	{"ID" : "53", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_controller_Pipeline_VITIS_LOOP_113_1_fu_644.am_addmul_14s_14s_16s_31_4_1_U102", "Parent" : "44"},
	{"ID" : "54", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_controller_Pipeline_VITIS_LOOP_113_1_fu_644.flow_control_loop_pipe_sequential_init_U", "Parent" : "44"},
	{"ID" : "55", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_OUT_PROJ_fu_666", "Parent" : "0", "Child" : ["56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71"],
		"CDFG" : "OUT_PROJ",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "9", "EstimateLatencyMax" : "9",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "int8_activation", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "OUT_PROJ_valueB", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "bias_0_0_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "bias_0_1_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "OUT_PROJ_accum", "Type" : "Memory", "Direction" : "O"}]},
	{"ID" : "56", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_OUT_PROJ_fu_666.mul_8s_4s_12_1_1_U119", "Parent" : "55"},
	{"ID" : "57", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_OUT_PROJ_fu_666.mul_8s_4s_12_1_1_U120", "Parent" : "55"},
	{"ID" : "58", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_OUT_PROJ_fu_666.mul_8s_4s_12_1_1_U121", "Parent" : "55"},
	{"ID" : "59", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_OUT_PROJ_fu_666.mul_8s_4s_12_1_1_U122", "Parent" : "55"},
	{"ID" : "60", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_OUT_PROJ_fu_666.mul_8s_4s_12_1_1_U123", "Parent" : "55"},
	{"ID" : "61", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_OUT_PROJ_fu_666.mul_8s_4s_12_1_1_U124", "Parent" : "55"},
	{"ID" : "62", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_OUT_PROJ_fu_666.mac_muladd_8s_4s_12s_13_4_1_U125", "Parent" : "55"},
	{"ID" : "63", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_OUT_PROJ_fu_666.mac_muladd_8s_4s_12s_13_4_1_U126", "Parent" : "55"},
	{"ID" : "64", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_OUT_PROJ_fu_666.mac_muladd_8s_4s_32s_32_4_1_U127", "Parent" : "55"},
	{"ID" : "65", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_OUT_PROJ_fu_666.mac_muladd_8s_4s_13s_13_4_1_U128", "Parent" : "55"},
	{"ID" : "66", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_OUT_PROJ_fu_666.mac_muladd_8s_4s_12s_13_4_1_U129", "Parent" : "55"},
	{"ID" : "67", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_OUT_PROJ_fu_666.mac_muladd_8s_4s_12s_13_4_1_U130", "Parent" : "55"},
	{"ID" : "68", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_OUT_PROJ_fu_666.mac_muladd_8s_4s_32s_32_4_1_U131", "Parent" : "55"},
	{"ID" : "69", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_OUT_PROJ_fu_666.mac_muladd_8s_4s_13s_13_4_1_U132", "Parent" : "55"},
	{"ID" : "70", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_OUT_PROJ_fu_666.mac_muladd_8s_4s_12s_13_4_1_U133", "Parent" : "55"},
	{"ID" : "71", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_OUT_PROJ_fu_666.mac_muladd_8s_4s_12s_13_4_1_U134", "Parent" : "55"}]}
