

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "15", "17", "19", "21", "23", "25", "31", "37", "38"],
		"CDFG" : "compute_controller",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "2", "EstimateLatencyMax" : "211",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "reset", "Type" : "None", "Direction" : "I"},
			{"Name" : "compute_start", "Type" : "None", "Direction" : "I"},
			{"Name" : "compute_instruction", "Type" : "None", "Direction" : "I"},
			{"Name" : "compute_ready", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "compute_done", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "mem_transfer_done", "Type" : "None", "Direction" : "I"},
			{"Name" : "mem_read_request", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "mem_write_request", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "mem_op", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "in_buf", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "13", "SubInstance" : "grp_compute_controller_Pipeline_VITIS_LOOP_367_4_fu_1588", "Port" : "in_buf", "Inst_start_state" : "1", "Inst_end_state" : "4"},
					{"ID" : "17", "SubInstance" : "grp_compute_controller_Pipeline_VITIS_LOOP_378_6_VITIS_LOOP_379_7_fu_1614", "Port" : "in_buf", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "out_buf", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "23", "SubInstance" : "grp_compute_controller_Pipeline_VITIS_LOOP_407_10_fu_1644", "Port" : "out_buf", "Inst_start_state" : "12", "Inst_end_state" : "13"}]},
			{"Name" : "dbg_state", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "dbg_req_instruction", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "dbg_req_op", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "dbg_req_layer", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "dbg_req_head", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "dbg_req_tile", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "dbg_mac_start", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "dbg_mac_ready", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "dbg_mac_complete", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "error", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "state", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "req_instruction", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "req_op", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "mac_ready", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "mac_complete", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "req_layer_idx", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "req_head_idx", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "req_tile_idx", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "capture_pending", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_3", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "13", "SubInstance" : "grp_compute_controller_Pipeline_VITIS_LOOP_367_4_fu_1588", "Port" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_3", "Inst_start_state" : "1", "Inst_end_state" : "4"},
					{"ID" : "15", "SubInstance" : "grp_compute_controller_Pipeline_VITIS_LOOP_372_5_fu_1602", "Port" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_3", "Inst_start_state" : "5", "Inst_end_state" : "6"},
					{"ID" : "25", "SubInstance" : "grp_compute_controller_Pipeline_VITIS_LOOP_43_2_fu_1654", "Port" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_3", "Inst_start_state" : "15", "Inst_end_state" : "16"},
					{"ID" : "31", "SubInstance" : "grp_compute_controller_Pipeline_VITIS_LOOP_43_21_fu_1678", "Port" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_3", "Inst_start_state" : "18", "Inst_end_state" : "19"}]},
			{"Name" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_2", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "13", "SubInstance" : "grp_compute_controller_Pipeline_VITIS_LOOP_367_4_fu_1588", "Port" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_2", "Inst_start_state" : "1", "Inst_end_state" : "4"},
					{"ID" : "15", "SubInstance" : "grp_compute_controller_Pipeline_VITIS_LOOP_372_5_fu_1602", "Port" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_2", "Inst_start_state" : "5", "Inst_end_state" : "6"},
					{"ID" : "25", "SubInstance" : "grp_compute_controller_Pipeline_VITIS_LOOP_43_2_fu_1654", "Port" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_2", "Inst_start_state" : "15", "Inst_end_state" : "16"},
					{"ID" : "31", "SubInstance" : "grp_compute_controller_Pipeline_VITIS_LOOP_43_21_fu_1678", "Port" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_2", "Inst_start_state" : "18", "Inst_end_state" : "19"}]},
			{"Name" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_1", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "13", "SubInstance" : "grp_compute_controller_Pipeline_VITIS_LOOP_367_4_fu_1588", "Port" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_1", "Inst_start_state" : "1", "Inst_end_state" : "4"},
					{"ID" : "15", "SubInstance" : "grp_compute_controller_Pipeline_VITIS_LOOP_372_5_fu_1602", "Port" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_1", "Inst_start_state" : "5", "Inst_end_state" : "6"},
					{"ID" : "25", "SubInstance" : "grp_compute_controller_Pipeline_VITIS_LOOP_43_2_fu_1654", "Port" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_1", "Inst_start_state" : "15", "Inst_end_state" : "16"},
					{"ID" : "31", "SubInstance" : "grp_compute_controller_Pipeline_VITIS_LOOP_43_21_fu_1678", "Port" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_1", "Inst_start_state" : "18", "Inst_end_state" : "19"}]},
			{"Name" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "13", "SubInstance" : "grp_compute_controller_Pipeline_VITIS_LOOP_367_4_fu_1588", "Port" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u", "Inst_start_state" : "1", "Inst_end_state" : "4"},
					{"ID" : "15", "SubInstance" : "grp_compute_controller_Pipeline_VITIS_LOOP_372_5_fu_1602", "Port" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u", "Inst_start_state" : "5", "Inst_end_state" : "6"},
					{"ID" : "25", "SubInstance" : "grp_compute_controller_Pipeline_VITIS_LOOP_43_2_fu_1654", "Port" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u", "Inst_start_state" : "15", "Inst_end_state" : "16"},
					{"ID" : "31", "SubInstance" : "grp_compute_controller_Pipeline_VITIS_LOOP_43_21_fu_1678", "Port" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u", "Inst_start_state" : "18", "Inst_end_state" : "19"}]},
			{"Name" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_9", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "17", "SubInstance" : "grp_compute_controller_Pipeline_VITIS_LOOP_378_6_VITIS_LOOP_379_7_fu_1614", "Port" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_9", "Inst_start_state" : "5", "Inst_end_state" : "6"},
					{"ID" : "25", "SubInstance" : "grp_compute_controller_Pipeline_VITIS_LOOP_43_2_fu_1654", "Port" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_9", "Inst_start_state" : "15", "Inst_end_state" : "16"},
					{"ID" : "31", "SubInstance" : "grp_compute_controller_Pipeline_VITIS_LOOP_43_21_fu_1678", "Port" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_9", "Inst_start_state" : "18", "Inst_end_state" : "19"}]},
			{"Name" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_8", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "17", "SubInstance" : "grp_compute_controller_Pipeline_VITIS_LOOP_378_6_VITIS_LOOP_379_7_fu_1614", "Port" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_8", "Inst_start_state" : "5", "Inst_end_state" : "6"},
					{"ID" : "25", "SubInstance" : "grp_compute_controller_Pipeline_VITIS_LOOP_43_2_fu_1654", "Port" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_8", "Inst_start_state" : "15", "Inst_end_state" : "16"},
					{"ID" : "31", "SubInstance" : "grp_compute_controller_Pipeline_VITIS_LOOP_43_21_fu_1678", "Port" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_8", "Inst_start_state" : "18", "Inst_end_state" : "19"}]},
			{"Name" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_7", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "17", "SubInstance" : "grp_compute_controller_Pipeline_VITIS_LOOP_378_6_VITIS_LOOP_379_7_fu_1614", "Port" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_7", "Inst_start_state" : "5", "Inst_end_state" : "6"},
					{"ID" : "25", "SubInstance" : "grp_compute_controller_Pipeline_VITIS_LOOP_43_2_fu_1654", "Port" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_7", "Inst_start_state" : "15", "Inst_end_state" : "16"},
					{"ID" : "31", "SubInstance" : "grp_compute_controller_Pipeline_VITIS_LOOP_43_21_fu_1678", "Port" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_7", "Inst_start_state" : "18", "Inst_end_state" : "19"}]},
			{"Name" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_6", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "17", "SubInstance" : "grp_compute_controller_Pipeline_VITIS_LOOP_378_6_VITIS_LOOP_379_7_fu_1614", "Port" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_6", "Inst_start_state" : "5", "Inst_end_state" : "6"},
					{"ID" : "25", "SubInstance" : "grp_compute_controller_Pipeline_VITIS_LOOP_43_2_fu_1654", "Port" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_6", "Inst_start_state" : "15", "Inst_end_state" : "16"},
					{"ID" : "31", "SubInstance" : "grp_compute_controller_Pipeline_VITIS_LOOP_43_21_fu_1678", "Port" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_6", "Inst_start_state" : "18", "Inst_end_state" : "19"}]},
			{"Name" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_11", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "19", "SubInstance" : "grp_compute_controller_Pipeline_VITIS_LOOP_391_8_fu_1628", "Port" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_11", "Inst_start_state" : "8", "Inst_end_state" : "9"},
					{"ID" : "21", "SubInstance" : "grp_compute_controller_Pipeline_VITIS_LOOP_395_9_fu_1638", "Port" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_11", "Inst_start_state" : "10", "Inst_end_state" : "11"}]},
			{"Name" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_10", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "19", "SubInstance" : "grp_compute_controller_Pipeline_VITIS_LOOP_391_8_fu_1628", "Port" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_10", "Inst_start_state" : "8", "Inst_end_state" : "9"}]},
			{"Name" : "busy", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_5", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_4", "Type" : "Memory", "Direction" : "IO"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_40_1", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "39", "FirstState" : "ap_ST_fsm_state14", "LastState" : ["ap_ST_fsm_state20"], "QuitState" : ["ap_ST_fsm_state17"], "PreState" : ["ap_ST_fsm_state13"], "PostState" : ["ap_ST_fsm_state25"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_3_U", "Parent" : "0"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_2_U", "Parent" : "0"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_1_U", "Parent" : "0"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_U", "Parent" : "0"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_9_U", "Parent" : "0"},
	{"ID" : "6", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_8_U", "Parent" : "0"},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_7_U", "Parent" : "0"},
	{"ID" : "8", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_6_U", "Parent" : "0"},
	{"ID" : "9", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_11_U", "Parent" : "0"},
	{"ID" : "10", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_10_U", "Parent" : "0"},
	{"ID" : "11", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_5_U", "Parent" : "0"},
	{"ID" : "12", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_4_U", "Parent" : "0"},
	{"ID" : "13", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_compute_controller_Pipeline_VITIS_LOOP_367_4_fu_1588", "Parent" : "0", "Child" : ["14"],
		"CDFG" : "compute_controller_Pipeline_VITIS_LOOP_367_4",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "10", "EstimateLatencyMax" : "10",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "in_buf", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_3", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_367_4", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "14", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_controller_Pipeline_VITIS_LOOP_367_4_fu_1588.flow_control_loop_pipe_sequential_init_U", "Parent" : "13"},
	{"ID" : "15", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_compute_controller_Pipeline_VITIS_LOOP_372_5_fu_1602", "Parent" : "0", "Child" : ["16"],
		"CDFG" : "compute_controller_Pipeline_VITIS_LOOP_372_5",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "16", "EstimateLatencyMax" : "16",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_3", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_372_5", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_state1", "FirstStateIter" : "", "FirstStateBlock" : "ap_ST_fsm_state1_blk", "LastState" : "ap_ST_fsm_state1", "LastStateIter" : "", "LastStateBlock" : "ap_ST_fsm_state1_blk", "QuitState" : "ap_ST_fsm_state1", "QuitStateIter" : "", "QuitStateBlock" : "ap_ST_fsm_state1_blk", "OneDepthLoop" : "1", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "16", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_controller_Pipeline_VITIS_LOOP_372_5_fu_1602.flow_control_loop_pipe_sequential_init_U", "Parent" : "15"},
	{"ID" : "17", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_compute_controller_Pipeline_VITIS_LOOP_378_6_VITIS_LOOP_379_7_fu_1614", "Parent" : "0", "Child" : ["18"],
		"CDFG" : "compute_controller_Pipeline_VITIS_LOOP_378_6_VITIS_LOOP_379_7",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "112", "EstimateLatencyMax" : "112",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "in_buf", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_9", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_8", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_7", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_6", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_378_6_VITIS_LOOP_379_7", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "18", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_controller_Pipeline_VITIS_LOOP_378_6_VITIS_LOOP_379_7_fu_1614.flow_control_loop_pipe_sequential_init_U", "Parent" : "17"},
	{"ID" : "19", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_compute_controller_Pipeline_VITIS_LOOP_391_8_fu_1628", "Parent" : "0", "Child" : ["20"],
		"CDFG" : "compute_controller_Pipeline_VITIS_LOOP_391_8",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "4", "EstimateLatencyMax" : "4",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "byte_val_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_11", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_10", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_391_8", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_state1", "FirstStateIter" : "", "FirstStateBlock" : "ap_ST_fsm_state1_blk", "LastState" : "ap_ST_fsm_state1", "LastStateIter" : "", "LastStateBlock" : "ap_ST_fsm_state1_blk", "QuitState" : "ap_ST_fsm_state1", "QuitStateIter" : "", "QuitStateBlock" : "ap_ST_fsm_state1_blk", "OneDepthLoop" : "1", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "20", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_controller_Pipeline_VITIS_LOOP_391_8_fu_1628.flow_control_loop_pipe_sequential_init_U", "Parent" : "19"},
	{"ID" : "21", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_compute_controller_Pipeline_VITIS_LOOP_395_9_fu_1638", "Parent" : "0", "Child" : ["22"],
		"CDFG" : "compute_controller_Pipeline_VITIS_LOOP_395_9",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "5", "EstimateLatencyMax" : "5",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_11", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_395_9", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_state1", "FirstStateIter" : "", "FirstStateBlock" : "ap_ST_fsm_state1_blk", "LastState" : "ap_ST_fsm_state1", "LastStateIter" : "", "LastStateBlock" : "ap_ST_fsm_state1_blk", "QuitState" : "ap_ST_fsm_state1", "QuitStateIter" : "", "QuitStateBlock" : "ap_ST_fsm_state1_blk", "OneDepthLoop" : "1", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "22", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_controller_Pipeline_VITIS_LOOP_395_9_fu_1638.flow_control_loop_pipe_sequential_init_U", "Parent" : "21"},
	{"ID" : "23", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_compute_controller_Pipeline_VITIS_LOOP_407_10_fu_1644", "Parent" : "0", "Child" : ["24"],
		"CDFG" : "compute_controller_Pipeline_VITIS_LOOP_407_10",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "6", "EstimateLatencyMax" : "6",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_26", "Type" : "None", "Direction" : "I"},
			{"Name" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_25", "Type" : "None", "Direction" : "I"},
			{"Name" : "out_buf", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_407_10", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "2", "FirstState" : "ap_ST_fsm_state1", "FirstStateIter" : "", "FirstStateBlock" : "ap_ST_fsm_state1_blk", "LastState" : "ap_ST_fsm_state2", "LastStateIter" : "", "LastStateBlock" : "ap_ST_fsm_state2_blk", "QuitState" : "ap_ST_fsm_state2", "QuitStateIter" : "", "QuitStateBlock" : "ap_ST_fsm_state2_blk", "OneDepthLoop" : "1", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "24", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_controller_Pipeline_VITIS_LOOP_407_10_fu_1644.flow_control_loop_pipe_sequential_init_U", "Parent" : "23"},
	{"ID" : "25", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_compute_controller_Pipeline_VITIS_LOOP_43_2_fu_1654", "Parent" : "0", "Child" : ["26", "27", "28", "29", "30"],
		"CDFG" : "compute_controller_Pipeline_VITIS_LOOP_43_2",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "11", "EstimateLatencyMax" : "11",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "sext_ln42", "Type" : "None", "Direction" : "I"},
			{"Name" : "mul_ln45", "Type" : "None", "Direction" : "I"},
			{"Name" : "acc_2_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_9", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_3", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_8", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_7", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_6", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_43_2", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter4", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter4", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "26", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_controller_Pipeline_VITIS_LOOP_43_2_fu_1654.mul_8s_4s_12_1_1_U22", "Parent" : "25"},
	{"ID" : "27", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_controller_Pipeline_VITIS_LOOP_43_2_fu_1654.mul_8s_4s_12_1_1_U23", "Parent" : "25"},
	{"ID" : "28", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_controller_Pipeline_VITIS_LOOP_43_2_fu_1654.mac_muladd_8s_4s_12s_32_4_1_U24", "Parent" : "25"},
	{"ID" : "29", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_controller_Pipeline_VITIS_LOOP_43_2_fu_1654.mac_muladd_8s_4s_12s_32_4_1_U25", "Parent" : "25"},
	{"ID" : "30", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_controller_Pipeline_VITIS_LOOP_43_2_fu_1654.flow_control_loop_pipe_sequential_init_U", "Parent" : "25"},
	{"ID" : "31", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_compute_controller_Pipeline_VITIS_LOOP_43_21_fu_1678", "Parent" : "0", "Child" : ["32", "33", "34", "35", "36"],
		"CDFG" : "compute_controller_Pipeline_VITIS_LOOP_43_21",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "11", "EstimateLatencyMax" : "11",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "sext_ln42_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "trunc_ln19", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty", "Type" : "None", "Direction" : "I"},
			{"Name" : "acc_6_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_7", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_3", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_6", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_9", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u_8", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_bool_u", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_43_2", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter4", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter4", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "32", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_controller_Pipeline_VITIS_LOOP_43_21_fu_1678.mul_8s_4s_12_1_1_U39", "Parent" : "31"},
	{"ID" : "33", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_controller_Pipeline_VITIS_LOOP_43_21_fu_1678.mul_8s_4s_12_1_1_U40", "Parent" : "31"},
	{"ID" : "34", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_controller_Pipeline_VITIS_LOOP_43_21_fu_1678.mac_muladd_8s_4s_12s_32_4_1_U41", "Parent" : "31"},
	{"ID" : "35", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_controller_Pipeline_VITIS_LOOP_43_21_fu_1678.mac_muladd_8s_4s_12s_32_4_1_U42", "Parent" : "31"},
	{"ID" : "36", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_controller_Pipeline_VITIS_LOOP_43_21_fu_1678.flow_control_loop_pipe_sequential_init_U", "Parent" : "31"},
	{"ID" : "37", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_7s_6ns_7_1_1_U55", "Parent" : "0"},
	{"ID" : "38", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_6s_5ns_6_1_1_U56", "Parent" : "0"}]}
