

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1"],
		"CDFG" : "compute_controller",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "1", "EstimateLatencyMax" : "10",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "reset", "Type" : "None", "Direction" : "I"},
			{"Name" : "compute_start", "Type" : "None", "Direction" : "I"},
			{"Name" : "compute_instruction", "Type" : "None", "Direction" : "I"},
			{"Name" : "compute_ready", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "compute_done", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "mem_transfer_done", "Type" : "None", "Direction" : "I"},
			{"Name" : "mem_read_request", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "mem_write_request", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "mem_op", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "OUT_PROJ_valueA", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_OUT_PROJ_fu_307", "Port" : "OUT_PROJ_valueA", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "OUT_PROJ_valueB", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_OUT_PROJ_fu_307", "Port" : "OUT_PROJ_valueB", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "OUT_PROJ_accum", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_OUT_PROJ_fu_307", "Port" : "OUT_PROJ_accum", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "error", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "state", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "req_instruction", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "req_op", "Type" : "OVld", "Direction" : "IO"}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_OUT_PROJ_fu_307", "Parent" : "0", "Child" : ["2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17"],
		"CDFG" : "OUT_PROJ",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "9", "EstimateLatencyMax" : "9",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "OUT_PROJ_valueA", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "OUT_PROJ_valueB", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "OUT_PROJ_accum", "Type" : "Memory", "Direction" : "O"}]},
	{"ID" : "2", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_OUT_PROJ_fu_307.mul_8s_4s_12_1_1_U1", "Parent" : "1"},
	{"ID" : "3", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_OUT_PROJ_fu_307.mul_8s_4s_12_1_1_U2", "Parent" : "1"},
	{"ID" : "4", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_OUT_PROJ_fu_307.mul_8s_4s_12_1_1_U3", "Parent" : "1"},
	{"ID" : "5", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_OUT_PROJ_fu_307.mul_8s_4s_12_1_1_U4", "Parent" : "1"},
	{"ID" : "6", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_OUT_PROJ_fu_307.mul_8s_4s_12_1_1_U5", "Parent" : "1"},
	{"ID" : "7", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_OUT_PROJ_fu_307.mul_8s_4s_12_1_1_U6", "Parent" : "1"},
	{"ID" : "8", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_OUT_PROJ_fu_307.mul_8s_4s_12_1_1_U7", "Parent" : "1"},
	{"ID" : "9", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_OUT_PROJ_fu_307.mul_8s_4s_12_1_1_U8", "Parent" : "1"},
	{"ID" : "10", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_OUT_PROJ_fu_307.mac_muladd_8s_4s_12s_13_4_1_U9", "Parent" : "1"},
	{"ID" : "11", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_OUT_PROJ_fu_307.mac_muladd_8s_4s_12s_13_4_1_U10", "Parent" : "1"},
	{"ID" : "12", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_OUT_PROJ_fu_307.mac_muladd_8s_4s_12s_13_4_1_U11", "Parent" : "1"},
	{"ID" : "13", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_OUT_PROJ_fu_307.mac_muladd_8s_4s_12s_13_4_1_U12", "Parent" : "1"},
	{"ID" : "14", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_OUT_PROJ_fu_307.mac_muladd_8s_4s_12s_13_4_1_U13", "Parent" : "1"},
	{"ID" : "15", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_OUT_PROJ_fu_307.mac_muladd_8s_4s_12s_13_4_1_U14", "Parent" : "1"},
	{"ID" : "16", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_OUT_PROJ_fu_307.mac_muladd_8s_4s_12s_13_4_1_U15", "Parent" : "1"},
	{"ID" : "17", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_OUT_PROJ_fu_307.mac_muladd_8s_4s_12s_13_4_1_U16", "Parent" : "1"}]}
