#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("reset", 1, hls_in, 0, "ap_none", "in_data", 1),
	Port_Property("compute_start", 1, hls_in, 1, "ap_none", "in_data", 1),
	Port_Property("compute_instruction", 32, hls_in, 2, "ap_none", "in_data", 1),
	Port_Property("compute_ready", 1, hls_out, 3, "ap_vld", "out_data", 1),
	Port_Property("compute_ready_ap_vld", 1, hls_out, 3, "ap_vld", "out_vld", 1),
	Port_Property("compute_done", 1, hls_out, 4, "ap_vld", "out_data", 1),
	Port_Property("compute_done_ap_vld", 1, hls_out, 4, "ap_vld", "out_vld", 1),
	Port_Property("mem_transfer_done", 1, hls_in, 5, "ap_none", "in_data", 1),
	Port_Property("mem_read_request", 1, hls_out, 6, "ap_vld", "out_data", 1),
	Port_Property("mem_read_request_ap_vld", 1, hls_out, 6, "ap_vld", "out_vld", 1),
	Port_Property("mem_write_request", 1, hls_out, 7, "ap_vld", "out_data", 1),
	Port_Property("mem_write_request_ap_vld", 1, hls_out, 7, "ap_vld", "out_vld", 1),
	Port_Property("mem_op", 32, hls_out, 8, "ap_vld", "out_data", 1),
	Port_Property("mem_op_ap_vld", 1, hls_out, 8, "ap_vld", "out_vld", 1),
	Port_Property("OUT_PROJ_valueA_address0", 3, hls_out, 9, "ap_memory", "mem_address", 1),
	Port_Property("OUT_PROJ_valueA_ce0", 1, hls_out, 9, "ap_memory", "mem_ce", 1),
	Port_Property("OUT_PROJ_valueA_q0", 8, hls_in, 9, "ap_memory", "mem_dout", 1),
	Port_Property("OUT_PROJ_valueA_address1", 3, hls_out, 9, "ap_memory", "MemPortADDR2", 1),
	Port_Property("OUT_PROJ_valueA_ce1", 1, hls_out, 9, "ap_memory", "MemPortCE2", 1),
	Port_Property("OUT_PROJ_valueA_q1", 8, hls_in, 9, "ap_memory", "MemPortDOUT2", 1),
	Port_Property("OUT_PROJ_valueB_address0", 4, hls_out, 10, "ap_memory", "mem_address", 1),
	Port_Property("OUT_PROJ_valueB_ce0", 1, hls_out, 10, "ap_memory", "mem_ce", 1),
	Port_Property("OUT_PROJ_valueB_q0", 4, hls_in, 10, "ap_memory", "mem_dout", 1),
	Port_Property("OUT_PROJ_valueB_address1", 4, hls_out, 10, "ap_memory", "MemPortADDR2", 1),
	Port_Property("OUT_PROJ_valueB_ce1", 1, hls_out, 10, "ap_memory", "MemPortCE2", 1),
	Port_Property("OUT_PROJ_valueB_q1", 4, hls_in, 10, "ap_memory", "MemPortDOUT2", 1),
	Port_Property("OUT_PROJ_accum_address0", 1, hls_out, 11, "ap_memory", "mem_address", 1),
	Port_Property("OUT_PROJ_accum_ce0", 1, hls_out, 11, "ap_memory", "mem_ce", 1),
	Port_Property("OUT_PROJ_accum_we0", 1, hls_out, 11, "ap_memory", "mem_we", 1),
	Port_Property("OUT_PROJ_accum_d0", 32, hls_out, 11, "ap_memory", "mem_din", 1),
	Port_Property("OUT_PROJ_accum_address1", 1, hls_out, 11, "ap_memory", "MemPortADDR2", 1),
	Port_Property("OUT_PROJ_accum_ce1", 1, hls_out, 11, "ap_memory", "MemPortCE2", 1),
	Port_Property("OUT_PROJ_accum_we1", 1, hls_out, 11, "ap_memory", "MemPortWE2", 1),
	Port_Property("OUT_PROJ_accum_d1", 32, hls_out, 11, "ap_memory", "MemPortDIN2", 1),
	Port_Property("error", 1, hls_out, 12, "ap_vld", "out_data", 1),
	Port_Property("error_ap_vld", 1, hls_out, 12, "ap_vld", "out_vld", 1),
};
const char* HLS_Design_Meta::dut_name = "compute_controller";
