-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity headed_compute_controller_headed_compute_controller_Pipeline_VITIS_LOOP_650_31 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in_buf_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    in_buf_ce0 : OUT STD_LOGIC;
    in_buf_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    in_buf_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
    in_buf_ce1 : OUT STD_LOGIC;
    in_buf_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_33_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_33_ce0 : OUT STD_LOGIC;
    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_33_we0 : OUT STD_LOGIC;
    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_33_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_32_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_32_ce0 : OUT STD_LOGIC;
    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_32_we0 : OUT STD_LOGIC;
    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_32_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_31_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_31_ce0 : OUT STD_LOGIC;
    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_31_we0 : OUT STD_LOGIC;
    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_31_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_30_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_30_ce0 : OUT STD_LOGIC;
    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_30_we0 : OUT STD_LOGIC;
    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_30_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_29_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_29_ce0 : OUT STD_LOGIC;
    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_29_we0 : OUT STD_LOGIC;
    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_29_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_28_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_28_ce0 : OUT STD_LOGIC;
    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_28_we0 : OUT STD_LOGIC;
    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_28_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_27_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_27_ce0 : OUT STD_LOGIC;
    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_27_we0 : OUT STD_LOGIC;
    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_27_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_26_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_26_ce0 : OUT STD_LOGIC;
    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_26_we0 : OUT STD_LOGIC;
    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_26_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_25_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_25_ce0 : OUT STD_LOGIC;
    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_25_we0 : OUT STD_LOGIC;
    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_25_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_24_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_24_ce0 : OUT STD_LOGIC;
    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_24_we0 : OUT STD_LOGIC;
    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_24_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_17_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_17_ce0 : OUT STD_LOGIC;
    p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_17_we0 : OUT STD_LOGIC;
    p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_17_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_16_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_16_ce0 : OUT STD_LOGIC;
    p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_16_we0 : OUT STD_LOGIC;
    p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_16_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_15_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_15_ce0 : OUT STD_LOGIC;
    p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_15_we0 : OUT STD_LOGIC;
    p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_15_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_14_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_14_ce0 : OUT STD_LOGIC;
    p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_14_we0 : OUT STD_LOGIC;
    p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_14_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_13_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_13_ce0 : OUT STD_LOGIC;
    p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_13_we0 : OUT STD_LOGIC;
    p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_13_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_12_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_12_ce0 : OUT STD_LOGIC;
    p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_12_we0 : OUT STD_LOGIC;
    p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_12_d0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of headed_compute_controller_headed_compute_controller_Pipeline_VITIS_LOOP_650_31 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (7 downto 0) := "00000100";
    constant ap_ST_fsm_pp0_stage3 : STD_LOGIC_VECTOR (7 downto 0) := "00001000";
    constant ap_ST_fsm_pp0_stage4 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_ST_fsm_pp0_stage5 : STD_LOGIC_VECTOR (7 downto 0) := "00100000";
    constant ap_ST_fsm_pp0_stage6 : STD_LOGIC_VECTOR (7 downto 0) := "01000000";
    constant ap_ST_fsm_pp0_stage7 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv7_10 : STD_LOGIC_VECTOR (6 downto 0) := "0010000";
    constant ap_const_lv7_11 : STD_LOGIC_VECTOR (6 downto 0) := "0010001";
    constant ap_const_lv7_12 : STD_LOGIC_VECTOR (6 downto 0) := "0010010";
    constant ap_const_lv7_13 : STD_LOGIC_VECTOR (6 downto 0) := "0010011";
    constant ap_const_lv7_14 : STD_LOGIC_VECTOR (6 downto 0) := "0010100";
    constant ap_const_lv7_15 : STD_LOGIC_VECTOR (6 downto 0) := "0010101";
    constant ap_const_lv7_16 : STD_LOGIC_VECTOR (6 downto 0) := "0010110";
    constant ap_const_lv7_17 : STD_LOGIC_VECTOR (6 downto 0) := "0010111";
    constant ap_const_lv7_18 : STD_LOGIC_VECTOR (6 downto 0) := "0011000";
    constant ap_const_lv7_19 : STD_LOGIC_VECTOR (6 downto 0) := "0011001";
    constant ap_const_lv7_1A : STD_LOGIC_VECTOR (6 downto 0) := "0011010";
    constant ap_const_lv7_1B : STD_LOGIC_VECTOR (6 downto 0) := "0011011";
    constant ap_const_lv7_1C : STD_LOGIC_VECTOR (6 downto 0) := "0011100";
    constant ap_const_lv7_1D : STD_LOGIC_VECTOR (6 downto 0) := "0011101";
    constant ap_const_lv7_1E : STD_LOGIC_VECTOR (6 downto 0) := "0011110";
    constant ap_const_lv7_1F : STD_LOGIC_VECTOR (6 downto 0) := "0011111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln650_fu_473_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage7 : signal is "none";
    signal ap_block_pp0_stage7_subdone : BOOLEAN;
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal h_3_reg_680 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln650_reg_685 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln656_fu_497_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln656_reg_689 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln650_fu_528_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln650_reg_717 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_pp0_stage2_11001 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage3 : signal is "none";
    signal ap_block_pp0_stage3_11001 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage4 : signal is "none";
    signal ap_block_pp0_stage4_11001 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage5 : signal is "none";
    signal ap_block_pp0_stage5_11001 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage6 : signal is "none";
    signal ap_block_pp0_stage6_11001 : BOOLEAN;
    signal ap_block_pp0_stage7_11001 : BOOLEAN;
    signal zext_ln561_fu_507_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln561_1_fu_518_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal zext_ln561_2_fu_538_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln561_3_fu_548_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage2 : BOOLEAN;
    signal zext_ln561_4_fu_558_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln561_5_fu_568_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage3 : BOOLEAN;
    signal zext_ln561_6_fu_578_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln561_7_fu_588_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage4 : BOOLEAN;
    signal zext_ln561_8_fu_598_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln561_9_fu_608_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage5 : BOOLEAN;
    signal zext_ln561_10_fu_618_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln561_11_fu_628_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage6 : BOOLEAN;
    signal zext_ln561_12_fu_638_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln561_13_fu_648_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage7 : BOOLEAN;
    signal zext_ln561_14_fu_658_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln561_15_fu_668_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal h_fu_100 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal add_ln650_fu_479_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_h_3 : STD_LOGIC_VECTOR (2 downto 0);
    signal in_buf_ce1_local : STD_LOGIC;
    signal in_buf_address1_local : STD_LOGIC_VECTOR (6 downto 0);
    signal in_buf_ce0_local : STD_LOGIC;
    signal in_buf_address0_local : STD_LOGIC_VECTOR (6 downto 0);
    signal headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_33_we0_local : STD_LOGIC;
    signal headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_33_ce0_local : STD_LOGIC;
    signal headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_32_we0_local : STD_LOGIC;
    signal headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_32_ce0_local : STD_LOGIC;
    signal headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_31_we0_local : STD_LOGIC;
    signal headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_31_ce0_local : STD_LOGIC;
    signal headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_30_we0_local : STD_LOGIC;
    signal headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_30_ce0_local : STD_LOGIC;
    signal headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_29_we0_local : STD_LOGIC;
    signal headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_29_ce0_local : STD_LOGIC;
    signal headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_28_we0_local : STD_LOGIC;
    signal headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_28_ce0_local : STD_LOGIC;
    signal headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_27_we0_local : STD_LOGIC;
    signal headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_27_ce0_local : STD_LOGIC;
    signal headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_26_we0_local : STD_LOGIC;
    signal headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_26_ce0_local : STD_LOGIC;
    signal headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_25_we0_local : STD_LOGIC;
    signal headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_25_ce0_local : STD_LOGIC;
    signal headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_24_we0_local : STD_LOGIC;
    signal headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_24_ce0_local : STD_LOGIC;
    signal p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_17_we0_local : STD_LOGIC;
    signal p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_17_ce0_local : STD_LOGIC;
    signal p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_16_we0_local : STD_LOGIC;
    signal p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_16_ce0_local : STD_LOGIC;
    signal p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_15_we0_local : STD_LOGIC;
    signal p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_15_ce0_local : STD_LOGIC;
    signal p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_14_we0_local : STD_LOGIC;
    signal p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_14_ce0_local : STD_LOGIC;
    signal p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_13_we0_local : STD_LOGIC;
    signal p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_13_ce0_local : STD_LOGIC;
    signal p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_12_we0_local : STD_LOGIC;
    signal p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_12_ce0_local : STD_LOGIC;
    signal trunc_ln656_fu_485_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal shl_ln2_fu_489_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln656_fu_501_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln656_1_fu_512_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln656_2_fu_533_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln656_3_fu_543_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln656_4_fu_553_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln656_5_fu_563_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln656_6_fu_573_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln656_7_fu_583_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln656_8_fu_593_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln656_9_fu_603_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln656_10_fu_613_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln656_11_fu_623_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln656_12_fu_633_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln656_13_fu_643_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln656_14_fu_653_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln656_15_fu_663_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_idle_pp0_1to1 : STD_LOGIC;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal ap_block_pp0_stage3_subdone : BOOLEAN;
    signal ap_block_pp0_stage4_subdone : BOOLEAN;
    signal ap_block_pp0_stage5_subdone : BOOLEAN;
    signal ap_block_pp0_stage6_subdone : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component headed_compute_controller_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component headed_compute_controller_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage7_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    h_fu_100_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln650_fu_473_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    h_fu_100 <= add_ln650_fu_479_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    h_fu_100 <= ap_const_lv3_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                h_3_reg_680 <= ap_sig_allocacmp_h_3;
                icmp_ln650_reg_685 <= icmp_ln650_fu_473_p2;
                    zext_ln656_reg_689(5 downto 4) <= zext_ln656_fu_497_p1(5 downto 4);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                    zext_ln650_reg_717(2 downto 0) <= zext_ln650_fu_528_p1(2 downto 0);
            end if;
        end if;
    end process;
    zext_ln656_reg_689(3 downto 0) <= "0000";
    zext_ln656_reg_689(6) <= '0';
    zext_ln650_reg_717(63 downto 3) <= "0000000000000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_condition_exit_pp0_iter0_stage0, ap_block_pp0_stage7_subdone, ap_idle_pp0_1to1, ap_block_pp0_stage1_subdone, ap_block_pp0_stage2_subdone, ap_block_pp0_stage3_subdone, ap_block_pp0_stage4_subdone, ap_block_pp0_stage5_subdone, ap_block_pp0_stage6_subdone, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((not(((ap_start_int = ap_const_logic_0) and (ap_idle_pp0_1to1 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when ap_ST_fsm_pp0_stage3 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                end if;
            when ap_ST_fsm_pp0_stage4 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage4_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage5;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
                end if;
            when ap_ST_fsm_pp0_stage5 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage5_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage6;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage5;
                end if;
            when ap_ST_fsm_pp0_stage6 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage6_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage7;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage6;
                end if;
            when ap_ST_fsm_pp0_stage7 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage7_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage7;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXX";
        end case;
    end process;
    add_ln650_fu_479_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_h_3) + unsigned(ap_const_lv3_1));
    add_ln656_10_fu_613_p2 <= std_logic_vector(unsigned(zext_ln656_reg_689) + unsigned(ap_const_lv7_1A));
    add_ln656_11_fu_623_p2 <= std_logic_vector(unsigned(zext_ln656_reg_689) + unsigned(ap_const_lv7_1B));
    add_ln656_12_fu_633_p2 <= std_logic_vector(unsigned(zext_ln656_reg_689) + unsigned(ap_const_lv7_1C));
    add_ln656_13_fu_643_p2 <= std_logic_vector(unsigned(zext_ln656_reg_689) + unsigned(ap_const_lv7_1D));
    add_ln656_14_fu_653_p2 <= std_logic_vector(unsigned(zext_ln656_reg_689) + unsigned(ap_const_lv7_1E));
    add_ln656_15_fu_663_p2 <= std_logic_vector(unsigned(zext_ln656_reg_689) + unsigned(ap_const_lv7_1F));
    add_ln656_1_fu_512_p2 <= std_logic_vector(unsigned(zext_ln656_fu_497_p1) + unsigned(ap_const_lv7_11));
    add_ln656_2_fu_533_p2 <= std_logic_vector(unsigned(zext_ln656_reg_689) + unsigned(ap_const_lv7_12));
    add_ln656_3_fu_543_p2 <= std_logic_vector(unsigned(zext_ln656_reg_689) + unsigned(ap_const_lv7_13));
    add_ln656_4_fu_553_p2 <= std_logic_vector(unsigned(zext_ln656_reg_689) + unsigned(ap_const_lv7_14));
    add_ln656_5_fu_563_p2 <= std_logic_vector(unsigned(zext_ln656_reg_689) + unsigned(ap_const_lv7_15));
    add_ln656_6_fu_573_p2 <= std_logic_vector(unsigned(zext_ln656_reg_689) + unsigned(ap_const_lv7_16));
    add_ln656_7_fu_583_p2 <= std_logic_vector(unsigned(zext_ln656_reg_689) + unsigned(ap_const_lv7_17));
    add_ln656_8_fu_593_p2 <= std_logic_vector(unsigned(zext_ln656_reg_689) + unsigned(ap_const_lv7_18));
    add_ln656_9_fu_603_p2 <= std_logic_vector(unsigned(zext_ln656_reg_689) + unsigned(ap_const_lv7_19));
    add_ln656_fu_501_p2 <= std_logic_vector(unsigned(zext_ln656_fu_497_p1) + unsigned(ap_const_lv7_10));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2);
    ap_CS_fsm_pp0_stage3 <= ap_CS_fsm(3);
    ap_CS_fsm_pp0_stage4 <= ap_CS_fsm(4);
    ap_CS_fsm_pp0_stage5 <= ap_CS_fsm(5);
    ap_CS_fsm_pp0_stage6 <= ap_CS_fsm(6);
    ap_CS_fsm_pp0_stage7 <= ap_CS_fsm(7);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage4_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage4_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage5_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage5_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage6_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage6_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage7 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage7_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage7_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln650_fu_473_p2)
    begin
        if (((icmp_ln650_fu_473_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to1_assign_proc : process(ap_enable_reg_pp0_iter1)
    begin
        if ((ap_enable_reg_pp0_iter1 = ap_const_logic_0)) then 
            ap_idle_pp0_1to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to1 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage7, ap_block_pp0_stage7_subdone, ap_enable_reg_pp0_iter0_reg)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage7_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_h_3_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, h_fu_100, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_h_3 <= ap_const_lv3_0;
        else 
            ap_sig_allocacmp_h_3 <= h_fu_100;
        end if; 
    end process;

    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_24_address0 <= zext_ln650_reg_717(4 - 1 downto 0);
    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_24_ce0 <= headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_24_ce0_local;

    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_24_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage5, ap_block_pp0_stage5_11001)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage5_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5))) then 
            headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_24_ce0_local <= ap_const_logic_1;
        else 
            headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_24_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_24_d0 <= in_buf_q0;
    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_24_we0 <= headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_24_we0_local;

    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_24_we0_local_assign_proc : process(ap_enable_reg_pp0_iter0_reg, icmp_ln650_reg_685, ap_CS_fsm_pp0_stage5, ap_block_pp0_stage5_11001)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage5_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5) and (icmp_ln650_reg_685 = ap_const_lv1_0))) then 
            headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_24_we0_local <= ap_const_logic_1;
        else 
            headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_24_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_25_address0 <= zext_ln650_reg_717(4 - 1 downto 0);
    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_25_ce0 <= headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_25_ce0_local;

    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_25_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage5, ap_block_pp0_stage5_11001)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage5_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5))) then 
            headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_25_ce0_local <= ap_const_logic_1;
        else 
            headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_25_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_25_d0 <= in_buf_q1;
    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_25_we0 <= headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_25_we0_local;

    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_25_we0_local_assign_proc : process(ap_enable_reg_pp0_iter0_reg, icmp_ln650_reg_685, ap_CS_fsm_pp0_stage5, ap_block_pp0_stage5_11001)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage5_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5) and (icmp_ln650_reg_685 = ap_const_lv1_0))) then 
            headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_25_we0_local <= ap_const_logic_1;
        else 
            headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_25_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_26_address0 <= zext_ln650_reg_717(4 - 1 downto 0);
    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_26_ce0 <= headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_26_ce0_local;

    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_26_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage4, ap_block_pp0_stage4_11001)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then 
            headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_26_ce0_local <= ap_const_logic_1;
        else 
            headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_26_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_26_d0 <= in_buf_q0;
    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_26_we0 <= headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_26_we0_local;

    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_26_we0_local_assign_proc : process(ap_enable_reg_pp0_iter0_reg, icmp_ln650_reg_685, ap_CS_fsm_pp0_stage4, ap_block_pp0_stage4_11001)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (icmp_ln650_reg_685 = ap_const_lv1_0))) then 
            headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_26_we0_local <= ap_const_logic_1;
        else 
            headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_26_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_27_address0 <= zext_ln650_reg_717(4 - 1 downto 0);
    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_27_ce0 <= headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_27_ce0_local;

    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_27_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage4, ap_block_pp0_stage4_11001)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then 
            headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_27_ce0_local <= ap_const_logic_1;
        else 
            headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_27_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_27_d0 <= in_buf_q1;
    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_27_we0 <= headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_27_we0_local;

    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_27_we0_local_assign_proc : process(ap_enable_reg_pp0_iter0_reg, icmp_ln650_reg_685, ap_CS_fsm_pp0_stage4, ap_block_pp0_stage4_11001)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (icmp_ln650_reg_685 = ap_const_lv1_0))) then 
            headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_27_we0_local <= ap_const_logic_1;
        else 
            headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_27_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_28_address0 <= zext_ln650_reg_717(4 - 1 downto 0);
    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_28_ce0 <= headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_28_ce0_local;

    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_28_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_28_ce0_local <= ap_const_logic_1;
        else 
            headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_28_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_28_d0 <= in_buf_q0;
    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_28_we0 <= headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_28_we0_local;

    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_28_we0_local_assign_proc : process(ap_enable_reg_pp0_iter0_reg, icmp_ln650_reg_685, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (icmp_ln650_reg_685 = ap_const_lv1_0))) then 
            headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_28_we0_local <= ap_const_logic_1;
        else 
            headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_28_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_29_address0 <= zext_ln650_reg_717(4 - 1 downto 0);
    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_29_ce0 <= headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_29_ce0_local;

    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_29_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_29_ce0_local <= ap_const_logic_1;
        else 
            headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_29_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_29_d0 <= in_buf_q1;
    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_29_we0 <= headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_29_we0_local;

    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_29_we0_local_assign_proc : process(ap_enable_reg_pp0_iter0_reg, icmp_ln650_reg_685, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (icmp_ln650_reg_685 = ap_const_lv1_0))) then 
            headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_29_we0_local <= ap_const_logic_1;
        else 
            headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_29_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_30_address0 <= zext_ln650_reg_717(4 - 1 downto 0);
    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_30_ce0 <= headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_30_ce0_local;

    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_30_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_30_ce0_local <= ap_const_logic_1;
        else 
            headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_30_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_30_d0 <= in_buf_q0;
    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_30_we0 <= headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_30_we0_local;

    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_30_we0_local_assign_proc : process(ap_enable_reg_pp0_iter0_reg, icmp_ln650_reg_685, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (icmp_ln650_reg_685 = ap_const_lv1_0))) then 
            headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_30_we0_local <= ap_const_logic_1;
        else 
            headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_30_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_31_address0 <= zext_ln650_reg_717(4 - 1 downto 0);
    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_31_ce0 <= headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_31_ce0_local;

    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_31_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_31_ce0_local <= ap_const_logic_1;
        else 
            headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_31_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_31_d0 <= in_buf_q1;
    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_31_we0 <= headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_31_we0_local;

    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_31_we0_local_assign_proc : process(ap_enable_reg_pp0_iter0_reg, icmp_ln650_reg_685, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (icmp_ln650_reg_685 = ap_const_lv1_0))) then 
            headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_31_we0_local <= ap_const_logic_1;
        else 
            headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_31_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_32_address0 <= zext_ln650_fu_528_p1(4 - 1 downto 0);
    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_32_ce0 <= headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_32_ce0_local;

    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_32_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_32_ce0_local <= ap_const_logic_1;
        else 
            headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_32_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_32_d0 <= in_buf_q0;
    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_32_we0 <= headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_32_we0_local;

    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_32_we0_local_assign_proc : process(ap_enable_reg_pp0_iter0_reg, icmp_ln650_reg_685, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (icmp_ln650_reg_685 = ap_const_lv1_0))) then 
            headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_32_we0_local <= ap_const_logic_1;
        else 
            headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_32_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_33_address0 <= zext_ln650_fu_528_p1(4 - 1 downto 0);
    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_33_ce0 <= headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_33_ce0_local;

    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_33_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_33_ce0_local <= ap_const_logic_1;
        else 
            headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_33_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_33_d0 <= in_buf_q1;
    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_33_we0 <= headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_33_we0_local;

    headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_33_we0_local_assign_proc : process(ap_enable_reg_pp0_iter0_reg, icmp_ln650_reg_685, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (icmp_ln650_reg_685 = ap_const_lv1_0))) then 
            headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_33_we0_local <= ap_const_logic_1;
        else 
            headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_33_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln650_fu_473_p2 <= "1" when (ap_sig_allocacmp_h_3 = ap_const_lv3_4) else "0";
    in_buf_address0 <= in_buf_address0_local;

    in_buf_address0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage7, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage1, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage4, ap_CS_fsm_pp0_stage5, ap_CS_fsm_pp0_stage6, ap_block_pp0_stage0, zext_ln561_1_fu_518_p1, ap_block_pp0_stage1, zext_ln561_3_fu_548_p1, ap_block_pp0_stage2, zext_ln561_5_fu_568_p1, ap_block_pp0_stage3, zext_ln561_7_fu_588_p1, ap_block_pp0_stage4, zext_ln561_9_fu_608_p1, ap_block_pp0_stage5, zext_ln561_11_fu_628_p1, ap_block_pp0_stage6, zext_ln561_13_fu_648_p1, ap_block_pp0_stage7, zext_ln561_15_fu_668_p1)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage7) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then 
            in_buf_address0_local <= zext_ln561_15_fu_668_p1(7 - 1 downto 0);
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage6) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6))) then 
            in_buf_address0_local <= zext_ln561_13_fu_648_p1(7 - 1 downto 0);
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage5) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5))) then 
            in_buf_address0_local <= zext_ln561_11_fu_628_p1(7 - 1 downto 0);
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage4) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then 
            in_buf_address0_local <= zext_ln561_9_fu_608_p1(7 - 1 downto 0);
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            in_buf_address0_local <= zext_ln561_7_fu_588_p1(7 - 1 downto 0);
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            in_buf_address0_local <= zext_ln561_5_fu_568_p1(7 - 1 downto 0);
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            in_buf_address0_local <= zext_ln561_3_fu_548_p1(7 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_buf_address0_local <= zext_ln561_1_fu_518_p1(7 - 1 downto 0);
        else 
            in_buf_address0_local <= "XXXXXXX";
        end if; 
    end process;

    in_buf_address1 <= in_buf_address1_local;

    in_buf_address1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage7, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage1, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage4, ap_CS_fsm_pp0_stage5, ap_CS_fsm_pp0_stage6, zext_ln561_fu_507_p1, ap_block_pp0_stage0, ap_block_pp0_stage1, zext_ln561_2_fu_538_p1, ap_block_pp0_stage2, zext_ln561_4_fu_558_p1, ap_block_pp0_stage3, zext_ln561_6_fu_578_p1, ap_block_pp0_stage4, zext_ln561_8_fu_598_p1, ap_block_pp0_stage5, zext_ln561_10_fu_618_p1, ap_block_pp0_stage6, zext_ln561_12_fu_638_p1, ap_block_pp0_stage7, zext_ln561_14_fu_658_p1)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage7) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then 
            in_buf_address1_local <= zext_ln561_14_fu_658_p1(7 - 1 downto 0);
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage6) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6))) then 
            in_buf_address1_local <= zext_ln561_12_fu_638_p1(7 - 1 downto 0);
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage5) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5))) then 
            in_buf_address1_local <= zext_ln561_10_fu_618_p1(7 - 1 downto 0);
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage4) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then 
            in_buf_address1_local <= zext_ln561_8_fu_598_p1(7 - 1 downto 0);
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            in_buf_address1_local <= zext_ln561_6_fu_578_p1(7 - 1 downto 0);
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            in_buf_address1_local <= zext_ln561_4_fu_558_p1(7 - 1 downto 0);
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            in_buf_address1_local <= zext_ln561_2_fu_538_p1(7 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_buf_address1_local <= zext_ln561_fu_507_p1(7 - 1 downto 0);
        else 
            in_buf_address1_local <= "XXXXXXX";
        end if; 
    end process;

    in_buf_ce0 <= in_buf_ce0_local;

    in_buf_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage7, ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001, ap_CS_fsm_pp0_stage4, ap_block_pp0_stage4_11001, ap_CS_fsm_pp0_stage5, ap_block_pp0_stage5_11001, ap_CS_fsm_pp0_stage6, ap_block_pp0_stage6_11001, ap_block_pp0_stage7_11001)
    begin
        if ((((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage7_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage6_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage5_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and 
    (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            in_buf_ce0_local <= ap_const_logic_1;
        else 
            in_buf_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_buf_ce1 <= in_buf_ce1_local;

    in_buf_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage7, ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001, ap_CS_fsm_pp0_stage4, ap_block_pp0_stage4_11001, ap_CS_fsm_pp0_stage5, ap_block_pp0_stage5_11001, ap_CS_fsm_pp0_stage6, ap_block_pp0_stage6_11001, ap_block_pp0_stage7_11001)
    begin
        if ((((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage7_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage6_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage5_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and 
    (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            in_buf_ce1_local <= ap_const_logic_1;
        else 
            in_buf_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_12_address0 <= zext_ln650_reg_717(4 - 1 downto 0);
    p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_12_ce0 <= p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_12_ce0_local;

    p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_12_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_12_ce0_local <= ap_const_logic_1;
        else 
            p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_12_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_12_d0 <= in_buf_q0;
    p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_12_we0 <= p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_12_we0_local;

    p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_12_we0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_12_we0_local <= ap_const_logic_1;
        else 
            p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_12_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_13_address0 <= zext_ln650_reg_717(4 - 1 downto 0);
    p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_13_ce0 <= p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_13_ce0_local;

    p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_13_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_13_ce0_local <= ap_const_logic_1;
        else 
            p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_13_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_13_d0 <= in_buf_q1;
    p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_13_we0 <= p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_13_we0_local;

    p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_13_we0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_13_we0_local <= ap_const_logic_1;
        else 
            p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_13_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_14_address0 <= zext_ln650_reg_717(4 - 1 downto 0);
    p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_14_ce0 <= p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_14_ce0_local;

    p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_14_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage7, ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage7_11001)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage7_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then 
            p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_14_ce0_local <= ap_const_logic_1;
        else 
            p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_14_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_14_d0 <= in_buf_q0;
    p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_14_we0 <= p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_14_we0_local;

    p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_14_we0_local_assign_proc : process(ap_CS_fsm_pp0_stage7, ap_enable_reg_pp0_iter0_reg, icmp_ln650_reg_685, ap_block_pp0_stage7_11001)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage7_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7) and (icmp_ln650_reg_685 = ap_const_lv1_0))) then 
            p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_14_we0_local <= ap_const_logic_1;
        else 
            p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_14_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_15_address0 <= zext_ln650_reg_717(4 - 1 downto 0);
    p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_15_ce0 <= p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_15_ce0_local;

    p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_15_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage7, ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage7_11001)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage7_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then 
            p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_15_ce0_local <= ap_const_logic_1;
        else 
            p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_15_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_15_d0 <= in_buf_q1;
    p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_15_we0 <= p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_15_we0_local;

    p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_15_we0_local_assign_proc : process(ap_CS_fsm_pp0_stage7, ap_enable_reg_pp0_iter0_reg, icmp_ln650_reg_685, ap_block_pp0_stage7_11001)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage7_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7) and (icmp_ln650_reg_685 = ap_const_lv1_0))) then 
            p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_15_we0_local <= ap_const_logic_1;
        else 
            p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_15_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_16_address0 <= zext_ln650_reg_717(4 - 1 downto 0);
    p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_16_ce0 <= p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_16_ce0_local;

    p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_16_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage6, ap_block_pp0_stage6_11001)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage6_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6))) then 
            p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_16_ce0_local <= ap_const_logic_1;
        else 
            p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_16_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_16_d0 <= in_buf_q0;
    p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_16_we0 <= p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_16_we0_local;

    p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_16_we0_local_assign_proc : process(ap_enable_reg_pp0_iter0_reg, icmp_ln650_reg_685, ap_CS_fsm_pp0_stage6, ap_block_pp0_stage6_11001)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage6_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6) and (icmp_ln650_reg_685 = ap_const_lv1_0))) then 
            p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_16_we0_local <= ap_const_logic_1;
        else 
            p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_16_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_17_address0 <= zext_ln650_reg_717(4 - 1 downto 0);
    p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_17_ce0 <= p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_17_ce0_local;

    p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_17_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage6, ap_block_pp0_stage6_11001)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage6_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6))) then 
            p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_17_ce0_local <= ap_const_logic_1;
        else 
            p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_17_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_17_d0 <= in_buf_q1;
    p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_17_we0 <= p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_17_we0_local;

    p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_17_we0_local_assign_proc : process(ap_enable_reg_pp0_iter0_reg, icmp_ln650_reg_685, ap_CS_fsm_pp0_stage6, ap_block_pp0_stage6_11001)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage6_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6) and (icmp_ln650_reg_685 = ap_const_lv1_0))) then 
            p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_17_we0_local <= ap_const_logic_1;
        else 
            p_ZZ25headed_compute_controllerbbjRbS_bS_S_RjPKhPhR12ComputeStateS0_RhS6_S6_S6_S_17_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    shl_ln2_fu_489_p3 <= (trunc_ln656_fu_485_p1 & ap_const_lv4_0);
    trunc_ln656_fu_485_p1 <= ap_sig_allocacmp_h_3(2 - 1 downto 0);
    zext_ln561_10_fu_618_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln656_10_fu_613_p2),64));
    zext_ln561_11_fu_628_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln656_11_fu_623_p2),64));
    zext_ln561_12_fu_638_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln656_12_fu_633_p2),64));
    zext_ln561_13_fu_648_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln656_13_fu_643_p2),64));
    zext_ln561_14_fu_658_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln656_14_fu_653_p2),64));
    zext_ln561_15_fu_668_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln656_15_fu_663_p2),64));
    zext_ln561_1_fu_518_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln656_1_fu_512_p2),64));
    zext_ln561_2_fu_538_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln656_2_fu_533_p2),64));
    zext_ln561_3_fu_548_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln656_3_fu_543_p2),64));
    zext_ln561_4_fu_558_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln656_4_fu_553_p2),64));
    zext_ln561_5_fu_568_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln656_5_fu_563_p2),64));
    zext_ln561_6_fu_578_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln656_6_fu_573_p2),64));
    zext_ln561_7_fu_588_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln656_7_fu_583_p2),64));
    zext_ln561_8_fu_598_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln656_8_fu_593_p2),64));
    zext_ln561_9_fu_608_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln656_9_fu_603_p2),64));
    zext_ln561_fu_507_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln656_fu_501_p2),64));
    zext_ln650_fu_528_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(h_3_reg_680),64));
    zext_ln656_fu_497_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln2_fu_489_p3),7));
end behav;
