-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity headed_compute_controller_SOFTMAX_Pipeline_VITIS_LOOP_266_3 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    exp_buf_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    exp_buf_1_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    exp_buf_2_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    exp_buf_3_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    exp_buf_4_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    exp_buf_5_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    exp_buf_6_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    exp_buf_7_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    exp_buf_8_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    exp_buf_9_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    exp_buf_10_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    exp_buf_11_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    exp_buf_12_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    exp_buf_13_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    exp_buf_14_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    exp_buf_15_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    inv_sum_q15_1 : IN STD_LOGIC_VECTOR (30 downto 0);
    soft_out_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    soft_out_ce0 : OUT STD_LOGIC;
    soft_out_we0 : OUT STD_LOGIC;
    soft_out_d0 : OUT STD_LOGIC_VECTOR (14 downto 0) );
end;


architecture behav of headed_compute_controller_SOFTMAX_Pipeline_VITIS_LOOP_266_3 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_1D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011101";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv15_7FFF : STD_LOGIC_VECTOR (14 downto 0) := "111111111111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal icmp_ln266_fu_244_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal zext_ln266_fu_256_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_fu_112 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal add_ln266_fu_250_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_6 : STD_LOGIC_VECTOR (4 downto 0);
    signal soft_out_we0_local : STD_LOGIC;
    signal prob_q15_fu_360_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal soft_out_ce0_local : STD_LOGIC;
    signal mul_ln268_fu_231_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_fu_265_p33 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_fu_265_p34 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_265_p35 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln268_fu_231_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_5_fu_352_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln269_1_fu_342_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal mul_ln268_fu_231_p10 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_fu_265_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_265_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_265_p5 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_265_p7 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_265_p9 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_265_p11 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_265_p13 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_265_p15 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_265_p17 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_265_p19 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_265_p21 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_265_p23 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_265_p25 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_265_p27 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_265_p29 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_265_p31 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component headed_compute_controller_mul_31s_16ns_31_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (30 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        dout : OUT STD_LOGIC_VECTOR (30 downto 0) );
    end component;


    component headed_compute_controller_sparsemux_33_4_16_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (3 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (3 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (3 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (3 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (3 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (3 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (3 downto 0);
        din6_WIDTH : INTEGER;
        CASE7 : STD_LOGIC_VECTOR (3 downto 0);
        din7_WIDTH : INTEGER;
        CASE8 : STD_LOGIC_VECTOR (3 downto 0);
        din8_WIDTH : INTEGER;
        CASE9 : STD_LOGIC_VECTOR (3 downto 0);
        din9_WIDTH : INTEGER;
        CASE10 : STD_LOGIC_VECTOR (3 downto 0);
        din10_WIDTH : INTEGER;
        CASE11 : STD_LOGIC_VECTOR (3 downto 0);
        din11_WIDTH : INTEGER;
        CASE12 : STD_LOGIC_VECTOR (3 downto 0);
        din12_WIDTH : INTEGER;
        CASE13 : STD_LOGIC_VECTOR (3 downto 0);
        din13_WIDTH : INTEGER;
        CASE14 : STD_LOGIC_VECTOR (3 downto 0);
        din14_WIDTH : INTEGER;
        CASE15 : STD_LOGIC_VECTOR (3 downto 0);
        din15_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        din3 : IN STD_LOGIC_VECTOR (15 downto 0);
        din4 : IN STD_LOGIC_VECTOR (15 downto 0);
        din5 : IN STD_LOGIC_VECTOR (15 downto 0);
        din6 : IN STD_LOGIC_VECTOR (15 downto 0);
        din7 : IN STD_LOGIC_VECTOR (15 downto 0);
        din8 : IN STD_LOGIC_VECTOR (15 downto 0);
        din9 : IN STD_LOGIC_VECTOR (15 downto 0);
        din10 : IN STD_LOGIC_VECTOR (15 downto 0);
        din11 : IN STD_LOGIC_VECTOR (15 downto 0);
        din12 : IN STD_LOGIC_VECTOR (15 downto 0);
        din13 : IN STD_LOGIC_VECTOR (15 downto 0);
        din14 : IN STD_LOGIC_VECTOR (15 downto 0);
        din15 : IN STD_LOGIC_VECTOR (15 downto 0);
        def : IN STD_LOGIC_VECTOR (15 downto 0);
        sel : IN STD_LOGIC_VECTOR (3 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component headed_compute_controller_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_31s_16ns_31_1_1_U105 : component headed_compute_controller_mul_31s_16ns_31_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 31,
        din1_WIDTH => 16,
        dout_WIDTH => 31)
    port map (
        din0 => inv_sum_q15_1,
        din1 => mul_ln268_fu_231_p1,
        dout => mul_ln268_fu_231_p2);

    sparsemux_33_4_16_1_1_U106 : component headed_compute_controller_sparsemux_33_4_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "0000",
        din0_WIDTH => 16,
        CASE1 => "0001",
        din1_WIDTH => 16,
        CASE2 => "0010",
        din2_WIDTH => 16,
        CASE3 => "0011",
        din3_WIDTH => 16,
        CASE4 => "0100",
        din4_WIDTH => 16,
        CASE5 => "0101",
        din5_WIDTH => 16,
        CASE6 => "0110",
        din6_WIDTH => 16,
        CASE7 => "0111",
        din7_WIDTH => 16,
        CASE8 => "1000",
        din8_WIDTH => 16,
        CASE9 => "1001",
        din9_WIDTH => 16,
        CASE10 => "1010",
        din10_WIDTH => 16,
        CASE11 => "1011",
        din11_WIDTH => 16,
        CASE12 => "1100",
        din12_WIDTH => 16,
        CASE13 => "1101",
        din13_WIDTH => 16,
        CASE14 => "1110",
        din14_WIDTH => 16,
        CASE15 => "1111",
        din15_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 4,
        dout_WIDTH => 16)
    port map (
        din0 => exp_buf_reload,
        din1 => exp_buf_1_reload,
        din2 => exp_buf_2_reload,
        din3 => exp_buf_3_reload,
        din4 => exp_buf_4_reload,
        din5 => exp_buf_5_reload,
        din6 => exp_buf_6_reload,
        din7 => exp_buf_7_reload,
        din8 => exp_buf_8_reload,
        din9 => exp_buf_9_reload,
        din10 => exp_buf_10_reload,
        din11 => exp_buf_11_reload,
        din12 => exp_buf_12_reload,
        din13 => exp_buf_13_reload,
        din14 => exp_buf_14_reload,
        din15 => exp_buf_15_reload,
        def => tmp_fu_265_p33,
        sel => tmp_fu_265_p34,
        dout => tmp_fu_265_p35);

    flow_control_loop_pipe_sequential_init_U : component headed_compute_controller_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    i_fu_112_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                if ((icmp_ln266_fu_244_p2 = ap_const_lv1_0)) then 
                    i_fu_112 <= add_ln266_fu_250_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_112 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln266_fu_250_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_6) + unsigned(ap_const_lv5_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1_pp0_stage0_iter0)
    begin
        if ((ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start_int)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_start_int = ap_const_logic_0);
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln266_fu_244_p2)
    begin
        if (((icmp_ln266_fu_244_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_6_assign_proc : process(ap_CS_fsm_state1, i_fu_112, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_sig_allocacmp_i_6 <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_i_6 <= i_fu_112;
        end if; 
    end process;

    icmp_ln266_fu_244_p2 <= "1" when (ap_sig_allocacmp_i_6 = ap_const_lv5_10) else "0";
    mul_ln268_fu_231_p1 <= mul_ln268_fu_231_p10(16 - 1 downto 0);
    mul_ln268_fu_231_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_265_p35),31));
    prob_q15_fu_360_p3 <= 
        ap_const_lv15_7FFF when (tmp_5_fu_352_p3(0) = '1') else 
        trunc_ln269_1_fu_342_p4;
    soft_out_address0 <= zext_ln266_fu_256_p1(4 - 1 downto 0);
    soft_out_ce0 <= soft_out_ce0_local;

    soft_out_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            soft_out_ce0_local <= ap_const_logic_1;
        else 
            soft_out_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    soft_out_d0 <= prob_q15_fu_360_p3;
    soft_out_we0 <= soft_out_we0_local;

    soft_out_we0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln266_fu_244_p2)
    begin
        if (((icmp_ln266_fu_244_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            soft_out_we0_local <= ap_const_logic_1;
        else 
            soft_out_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    tmp_5_fu_352_p3 <= mul_ln268_fu_231_p2(30 downto 30);
    tmp_fu_265_p33 <= "XXXXXXXXXXXXXXXX";
    tmp_fu_265_p34 <= ap_sig_allocacmp_i_6(4 - 1 downto 0);
    trunc_ln269_1_fu_342_p4 <= mul_ln268_fu_231_p2(29 downto 15);
    zext_ln266_fu_256_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_i_6),64));
end behav;
