

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "13", "14", "15", "16", "17", "18", "19"],
		"CDFG" : "transformer_top",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "4", "EstimateLatencyMax" : "4",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "axis_in_valid", "Type" : "None", "Direction" : "I"},
			{"Name" : "axis_in_last", "Type" : "None", "Direction" : "I"},
			{"Name" : "axis_in_ready", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "dma_done", "Type" : "None", "Direction" : "I"},
			{"Name" : "dma_address", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "memory_request", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "compute_ready", "Type" : "None", "Direction" : "I"},
			{"Name" : "compute_done", "Type" : "None", "Direction" : "I"},
			{"Name" : "compute_start", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "compute_op", "Type" : "Vld", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_scheduler_hls_fu_23685", "Port" : "compute_op", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "head_ctx_ref_0", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "head_ctx_ref_1", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "head_ctx_ref_2", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "head_ctx_ref_3", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "stream_ready", "Type" : "None", "Direction" : "I"},
			{"Name" : "stream_start", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "stream_done", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctrl_addr", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctrl_data_in", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctrl_data_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "ctrl_read_en", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctrl_write_en", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctrl_chip_en", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctrl_resetn_in", "Type" : "None", "Direction" : "I"},
			{"Name" : "irq_ps", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "dbg_state", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "dbg_ctrl_mem", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "control_reg", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "irq_status_reg", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "irq_enable_reg", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "wq_base_addr", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "wk_base_addr", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "wv_base_addr", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "wo_base_addr", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "w1_base_addr", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "w2_base_addr", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "wq_head_stride", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "wk_head_stride", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "wv_head_stride", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "wo_tile_stride", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "w1_tile_stride", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "w2_tile_stride", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "dbg_wl_ready", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "dbg_wl_start", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "dbg_wl_addr_sel", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "dbg_wl_layer", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "dbg_wl_head", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "dbg_wl_tile", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "dbg_done", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "dbg_error", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "ctrl_mem_control", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ctrl_mem_irq_status", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ctrl_mem_irq_enable", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ctrl_mem_wq_base_addr", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ctrl_mem_wk_base_addr", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ctrl_mem_wv_base_addr", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ctrl_mem_wo_base_addr", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ctrl_mem_w1_base_addr", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ctrl_mem_w2_base_addr", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ctrl_mem_wq_head_stride", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ctrl_mem_wk_head_stride", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ctrl_mem_wv_head_stride", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ctrl_mem_wo_tile_stride", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ctrl_mem_w1_tile_stride", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ctrl_mem_w2_tile_stride", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ctrl_mem_layer_index", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ctrl_mem_status", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ctrl_mem_dma_layer_len", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ctrl_mem_dma_head_len", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ctrl_mem_dma_tile_len", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ctrl_mem_layer_stride", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ctrl_mem_k_cache_stride", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ctrl_mem_v_cache_stride", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ctrl_mem_k_cache_addr", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ctrl_mem_v_cache_addr", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ctrl_mem_logit_scale_qv", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ctrl_mem_scale_q", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ctrl_mem_zero_point_q", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ctrl_mem_scale_k", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ctrl_mem_zero_point_k", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ctrl_mem_scale_v", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ctrl_mem_zero_point_v", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ctrl_mem_reserved_debug", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "wl_start", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_scheduler_hls_fu_23685", "Port" : "wl_start", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "wl_addr_sel", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_scheduler_hls_fu_23685", "Port" : "wl_addr_sel", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "wl_layer", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_scheduler_hls_fu_23685", "Port" : "wl_layer", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "wl_head", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_scheduler_hls_fu_23685", "Port" : "wl_head", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "wl_tile", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_scheduler_hls_fu_23685", "Port" : "wl_tile", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "addr_latched", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "st", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_scheduler_hls_fu_23685", "Port" : "st", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "layer_idx", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_scheduler_hls_fu_23685", "Port" : "layer_idx", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "attn_started", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_scheduler_hls_fu_23685", "Port" : "attn_started", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "group_idx", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_scheduler_hls_fu_23685", "Port" : "group_idx", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "start_head_group", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_scheduler_hls_fu_23685", "Port" : "start_head_group", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "requant1_started", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_scheduler_hls_fu_23685", "Port" : "requant1_started", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "requant2_started", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_scheduler_hls_fu_23685", "Port" : "requant2_started", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "requant3_started", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_scheduler_hls_fu_23685", "Port" : "requant3_started", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "requant4_started", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_scheduler_hls_fu_23685", "Port" : "requant4_started", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "requant1_compute_done", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_scheduler_hls_fu_23685", "Port" : "requant1_compute_done", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "requant2_compute_done", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_scheduler_hls_fu_23685", "Port" : "requant2_compute_done", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "requant3_compute_done", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_scheduler_hls_fu_23685", "Port" : "requant3_compute_done", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "requant4_compute_done", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_scheduler_hls_fu_23685", "Port" : "requant4_compute_done", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "concat_compute_done", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_scheduler_hls_fu_23685", "Port" : "concat_compute_done", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "concat_started", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_scheduler_hls_fu_23685", "Port" : "concat_started", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "outproj_started", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_scheduler_hls_fu_23685", "Port" : "outproj_started", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "outproj_compute_done", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_scheduler_hls_fu_23685", "Port" : "outproj_compute_done", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "wo_dma_done", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_scheduler_hls_fu_23685", "Port" : "wo_dma_done", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "w1_dma_done", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_scheduler_hls_fu_23685", "Port" : "w1_dma_done", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "w2_dma_done", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_scheduler_hls_fu_23685", "Port" : "w2_dma_done", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "resid0_started", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_scheduler_hls_fu_23685", "Port" : "resid0_started", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "resid0_compute_done", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_scheduler_hls_fu_23685", "Port" : "resid0_compute_done", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "ln0_started", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_scheduler_hls_fu_23685", "Port" : "ln0_started", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "ln0_compute_done", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_scheduler_hls_fu_23685", "Port" : "ln0_compute_done", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "ln0_phase", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_scheduler_hls_fu_23685", "Port" : "ln0_phase", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "ffn_w1_compute_done", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_scheduler_hls_fu_23685", "Port" : "ffn_w1_compute_done", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "ffn_act_compute_done", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_scheduler_hls_fu_23685", "Port" : "ffn_act_compute_done", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "ffn_w2_compute_done", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_scheduler_hls_fu_23685", "Port" : "ffn_w2_compute_done", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "ffn_stage", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_scheduler_hls_fu_23685", "Port" : "ffn_stage", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "ffn_started", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_scheduler_hls_fu_23685", "Port" : "ffn_started", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "resid1_started", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_scheduler_hls_fu_23685", "Port" : "resid1_started", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "resid1_compute_done", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_scheduler_hls_fu_23685", "Port" : "resid1_compute_done", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "ln1_started", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_scheduler_hls_fu_23685", "Port" : "ln1_started", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "ln1_compute_done", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_scheduler_hls_fu_23685", "Port" : "ln1_compute_done", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "ln1_phase", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_scheduler_hls_fu_23685", "Port" : "ln1_phase", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "axis_last_seen", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_scheduler_hls_fu_23685", "Port" : "axis_last_seen", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "stream_done_seen", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_scheduler_hls_fu_23685", "Port" : "stream_done_seen", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "stream_started", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_scheduler_hls_fu_23685", "Port" : "stream_started", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "wo_tile", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_scheduler_hls_fu_23685", "Port" : "wo_tile", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "wo_dma_busy", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_scheduler_hls_fu_23685", "Port" : "wo_dma_busy", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "wo_comp_busy", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_scheduler_hls_fu_23685", "Port" : "wo_comp_busy", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "w1_tile", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_scheduler_hls_fu_23685", "Port" : "w1_tile", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "w1_dma_busy", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_scheduler_hls_fu_23685", "Port" : "w1_dma_busy", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "w1_comp_busy", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_scheduler_hls_fu_23685", "Port" : "w1_comp_busy", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "w2_tile", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_scheduler_hls_fu_23685", "Port" : "w2_tile", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "w2_dma_busy", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_scheduler_hls_fu_23685", "Port" : "w2_dma_busy", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "w2_comp_busy", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_scheduler_hls_fu_23685", "Port" : "w2_comp_busy", "Inst_start_state" : "2", "Inst_end_state" : "3"}]}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_scheduler_hls_fu_23685", "Parent" : "0", "Child" : ["2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"],
		"CDFG" : "scheduler_hls",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "1", "EstimateLatencyMax" : "1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "ctrl_mem_control", "Type" : "None", "Direction" : "I"},
			{"Name" : "axis_in_valid", "Type" : "None", "Direction" : "I"},
			{"Name" : "axis_in_last", "Type" : "None", "Direction" : "I"},
			{"Name" : "wl_ready", "Type" : "None", "Direction" : "I"},
			{"Name" : "dma_done", "Type" : "None", "Direction" : "I"},
			{"Name" : "compute_ready", "Type" : "None", "Direction" : "I"},
			{"Name" : "compute_done", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read1", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read2", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read3", "Type" : "None", "Direction" : "I"},
			{"Name" : "compute_start_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "compute_op", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "stream_ready", "Type" : "None", "Direction" : "I"},
			{"Name" : "stream_done", "Type" : "None", "Direction" : "I"},
			{"Name" : "st", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "layer_idx", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "attn_started", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "group_idx", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "start_head_group", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "requant1_started", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "requant2_started", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "requant3_started", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "requant4_started", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "requant1_compute_done", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "requant2_compute_done", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "requant3_compute_done", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "requant4_compute_done", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "concat_compute_done", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "concat_started", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "outproj_started", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "outproj_compute_done", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "wo_dma_done", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "w1_dma_done", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "w2_dma_done", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "resid0_started", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "resid0_compute_done", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ln0_started", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ln0_compute_done", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ln0_phase", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ffn_w1_compute_done", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ffn_act_compute_done", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ffn_w2_compute_done", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ffn_stage", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ffn_started", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "resid1_started", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "resid1_compute_done", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ln1_started", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ln1_compute_done", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ln1_phase", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "axis_last_seen", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "stream_done_seen", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "stream_started", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "wo_tile", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "wo_dma_busy", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "wo_comp_busy", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "w1_tile", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "w1_dma_busy", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "w1_comp_busy", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "w2_tile", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "w2_dma_busy", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "w2_comp_busy", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "wl_start", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "wl_layer", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "wl_tile", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "wl_head", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "wl_addr_sel", "Type" : "Vld", "Direction" : "O"}]},
	{"ID" : "2", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_scheduler_hls_fu_23685.call_ret8_drive_group_head_phase_fu_29424", "Parent" : "1",
		"CDFG" : "drive_group_head_phase",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "0", "ap_start" : "0", "ap_ready" : "1", "ap_done" : "0", "ap_continue" : "0", "ap_idle" : "0", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "1",
		"VariableLatency" : "0", "ExactLatency" : "0", "EstimateLatencyMin" : "0", "EstimateLatencyMax" : "0",
		"Combinational" : "1",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "p_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read1", "Type" : "None", "Direction" : "I"},
			{"Name" : "head_ctx_ref_head_idx_0_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "head_ctx_ref_head_idx_1_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "head_ctx_ref_phase_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "head_ctx_ref_phase_read_5", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read4", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read13", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read14", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read15", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read16", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read17", "Type" : "None", "Direction" : "I"},
			{"Name" : "head_ctx_ref_compute_op_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "head_ctx_ref_compute_op_read_5", "Type" : "None", "Direction" : "I"},
			{"Name" : "head_ctx_ref_last_compute_op_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "head_ctx_ref_last_compute_op_read_5", "Type" : "None", "Direction" : "I"},
			{"Name" : "head_ctx_ref_last_wl_addr_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "head_ctx_ref_last_wl_addr_read_5", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read24", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read25", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read26", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read27", "Type" : "None", "Direction" : "I"},
			{"Name" : "head_ctx_ref_wl_addr_sel_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "head_ctx_ref_wl_addr_sel_read_5", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read30", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read31", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read32", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read33", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read34", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read35", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read38", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read39", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read40", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read41", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read42", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read43", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read44", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read45", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read46", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read47", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read48", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read49", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read50", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read51", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read52", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read53", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read54", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read55", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read56", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read57", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read58", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read59", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read60", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read61", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read62", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read63", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read64", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read65", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read66", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read67", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read68", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read69", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read70", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read71", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read72", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read73", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read74", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read75", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read76", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read77", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read78", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read79", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read80", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read81", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read82", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read83", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read84", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read85", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read86", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read87", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read88", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read89", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read90", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read91", "Type" : "None", "Direction" : "I"},
			{"Name" : "layer_idx", "Type" : "None", "Direction" : "I"},
			{"Name" : "start_r", "Type" : "None", "Direction" : "I"}]},
	{"ID" : "3", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_scheduler_hls_fu_23685.sparsemux_7_2_1_1_1_U87", "Parent" : "1"},
	{"ID" : "4", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_scheduler_hls_fu_23685.sparsemux_7_2_1_1_1_U88", "Parent" : "1"},
	{"ID" : "5", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_scheduler_hls_fu_23685.sparsemux_7_2_1_1_1_U89", "Parent" : "1"},
	{"ID" : "6", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_scheduler_hls_fu_23685.sparsemux_7_2_1_1_1_U90", "Parent" : "1"},
	{"ID" : "7", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_scheduler_hls_fu_23685.sparsemux_7_2_1_1_1_U91", "Parent" : "1"},
	{"ID" : "8", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_scheduler_hls_fu_23685.sparsemux_7_2_1_1_1_U92", "Parent" : "1"},
	{"ID" : "9", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_scheduler_hls_fu_23685.sparsemux_7_2_202_1_1_U93", "Parent" : "1"},
	{"ID" : "10", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_scheduler_hls_fu_23685.sparsemux_7_2_202_1_1_U94", "Parent" : "1"},
	{"ID" : "11", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_scheduler_hls_fu_23685.sparsemux_7_2_202_1_1_U95", "Parent" : "1"},
	{"ID" : "12", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_scheduler_hls_fu_23685.sparsemux_7_2_202_1_1_U96", "Parent" : "1"},
	{"ID" : "13", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32s_32s_32_1_1_U120", "Parent" : "0"},
	{"ID" : "14", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32s_32s_32_1_1_U121", "Parent" : "0"},
	{"ID" : "15", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_2s_32s_32_1_1_U122", "Parent" : "0"},
	{"ID" : "16", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_2s_32s_32_1_1_U123", "Parent" : "0"},
	{"ID" : "17", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_2s_32s_32_1_1_U124", "Parent" : "0"},
	{"ID" : "18", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_2s_32s_32_1_1_U125", "Parent" : "0"},
	{"ID" : "19", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_2s_32s_32_1_1_U126", "Parent" : "0"}]}
