// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module transformer_top_compute_controller_Pipeline_VITIS_LOOP_245_217 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        acc_9,
        p_udiv337_i,
        matrixB_address0,
        matrixB_ce0,
        matrixB_q0,
        vectorA_address0,
        vectorA_ce0,
        vectorA_q0,
        matrixB_1_address0,
        matrixB_1_ce0,
        matrixB_1_q0,
        vectorA_1_address0,
        vectorA_1_ce0,
        vectorA_1_q0,
        matrixB_2_address0,
        matrixB_2_ce0,
        matrixB_2_q0,
        vectorA_2_address0,
        vectorA_2_ce0,
        vectorA_2_q0,
        matrixB_3_address0,
        matrixB_3_ce0,
        matrixB_3_q0,
        vectorA_3_address0,
        vectorA_3_ce0,
        vectorA_3_q0,
        matrixB_4_address0,
        matrixB_4_ce0,
        matrixB_4_q0,
        vectorA_4_address0,
        vectorA_4_ce0,
        vectorA_4_q0,
        matrixB_5_address0,
        matrixB_5_ce0,
        matrixB_5_q0,
        vectorA_5_address0,
        vectorA_5_ce0,
        vectorA_5_q0,
        matrixB_6_address0,
        matrixB_6_ce0,
        matrixB_6_q0,
        vectorA_6_address0,
        vectorA_6_ce0,
        vectorA_6_q0,
        matrixB_7_address0,
        matrixB_7_ce0,
        matrixB_7_q0,
        vectorA_7_address0,
        vectorA_7_ce0,
        vectorA_7_q0,
        acc_11_out,
        acc_11_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] acc_9;
input  [5:0] p_udiv337_i;
output  [5:0] matrixB_address0;
output   matrixB_ce0;
input  [7:0] matrixB_q0;
output  [1:0] vectorA_address0;
output   vectorA_ce0;
input  [31:0] vectorA_q0;
output  [5:0] matrixB_1_address0;
output   matrixB_1_ce0;
input  [7:0] matrixB_1_q0;
output  [1:0] vectorA_1_address0;
output   vectorA_1_ce0;
input  [31:0] vectorA_1_q0;
output  [5:0] matrixB_2_address0;
output   matrixB_2_ce0;
input  [7:0] matrixB_2_q0;
output  [1:0] vectorA_2_address0;
output   vectorA_2_ce0;
input  [31:0] vectorA_2_q0;
output  [5:0] matrixB_3_address0;
output   matrixB_3_ce0;
input  [7:0] matrixB_3_q0;
output  [1:0] vectorA_3_address0;
output   vectorA_3_ce0;
input  [31:0] vectorA_3_q0;
output  [5:0] matrixB_4_address0;
output   matrixB_4_ce0;
input  [7:0] matrixB_4_q0;
output  [1:0] vectorA_4_address0;
output   vectorA_4_ce0;
input  [31:0] vectorA_4_q0;
output  [5:0] matrixB_5_address0;
output   matrixB_5_ce0;
input  [7:0] matrixB_5_q0;
output  [1:0] vectorA_5_address0;
output   vectorA_5_ce0;
input  [31:0] vectorA_5_q0;
output  [5:0] matrixB_6_address0;
output   matrixB_6_ce0;
input  [7:0] matrixB_6_q0;
output  [1:0] vectorA_6_address0;
output   vectorA_6_ce0;
input  [31:0] vectorA_6_q0;
output  [5:0] matrixB_7_address0;
output   matrixB_7_ce0;
input  [7:0] matrixB_7_q0;
output  [1:0] vectorA_7_address0;
output   vectorA_7_ce0;
input  [31:0] vectorA_7_q0;
output  [31:0] acc_11_out;
output   acc_11_out_ap_vld;

reg ap_idle;
reg acc_11_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln245_fu_364_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln247_1_fu_402_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln244_1_fu_380_p1;
reg   [31:0] acc_fu_76;
wire   [31:0] acc_10_fu_510_p2;
wire    ap_loop_init;
reg   [4:0] i_fu_80;
wire   [4:0] add_ln245_fu_414_p2;
reg   [4:0] ap_sig_allocacmp_i_36;
wire    ap_block_pp0_stage0_01001;
reg    matrixB_ce0_local;
reg    vectorA_ce0_local;
reg    matrixB_1_ce0_local;
reg    vectorA_1_ce0_local;
reg    matrixB_2_ce0_local;
reg    vectorA_2_ce0_local;
reg    matrixB_3_ce0_local;
reg    vectorA_3_ce0_local;
reg    matrixB_4_ce0_local;
reg    vectorA_4_ce0_local;
reg    matrixB_5_ce0_local;
reg    vectorA_5_ce0_local;
reg    matrixB_6_ce0_local;
reg    vectorA_6_ce0_local;
reg    matrixB_7_ce0_local;
reg    vectorA_7_ce0_local;
wire   [1:0] lshr_ln244_1_fu_370_p4;
wire   [5:0] zext_ln244_2_fu_392_p1;
wire   [5:0] add_ln247_fu_396_p2;
wire   [31:0] mul_ln248_8_fu_311_p2;
wire   [31:0] mul_ln248_fu_346_p2;
wire   [31:0] mul_ln248_14_fu_341_p2;
wire   [31:0] mul_ln248_13_fu_336_p2;
wire   [31:0] add_ln248_9_fu_474_p2;
wire   [31:0] add_ln248_8_fu_468_p2;
wire   [31:0] mul_ln248_12_fu_331_p2;
wire   [31:0] mul_ln248_11_fu_326_p2;
wire   [31:0] mul_ln248_10_fu_321_p2;
wire   [31:0] mul_ln248_9_fu_316_p2;
wire   [31:0] add_ln248_12_fu_492_p2;
wire   [31:0] add_ln248_11_fu_486_p2;
wire   [31:0] add_ln248_13_fu_498_p2;
wire   [31:0] add_ln248_10_fu_480_p2;
wire   [31:0] add_ln248_14_fu_504_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 acc_fu_76 = 32'd0;
#0 i_fu_80 = 5'd0;
#0 ap_done_reg = 1'b0;
end

transformer_top_mul_32s_8s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 32 ))
mul_32s_8s_32_1_1_U1409(
    .din0(vectorA_q0),
    .din1(matrixB_q0),
    .dout(mul_ln248_8_fu_311_p2)
);

transformer_top_mul_32s_8s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 32 ))
mul_32s_8s_32_1_1_U1410(
    .din0(vectorA_7_q0),
    .din1(matrixB_7_q0),
    .dout(mul_ln248_9_fu_316_p2)
);

transformer_top_mul_32s_8s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 32 ))
mul_32s_8s_32_1_1_U1411(
    .din0(vectorA_6_q0),
    .din1(matrixB_6_q0),
    .dout(mul_ln248_10_fu_321_p2)
);

transformer_top_mul_32s_8s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 32 ))
mul_32s_8s_32_1_1_U1412(
    .din0(vectorA_5_q0),
    .din1(matrixB_5_q0),
    .dout(mul_ln248_11_fu_326_p2)
);

transformer_top_mul_32s_8s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 32 ))
mul_32s_8s_32_1_1_U1413(
    .din0(vectorA_4_q0),
    .din1(matrixB_4_q0),
    .dout(mul_ln248_12_fu_331_p2)
);

transformer_top_mul_32s_8s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 32 ))
mul_32s_8s_32_1_1_U1414(
    .din0(vectorA_3_q0),
    .din1(matrixB_3_q0),
    .dout(mul_ln248_13_fu_336_p2)
);

transformer_top_mul_32s_8s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 32 ))
mul_32s_8s_32_1_1_U1415(
    .din0(vectorA_2_q0),
    .din1(matrixB_2_q0),
    .dout(mul_ln248_14_fu_341_p2)
);

transformer_top_mul_32s_8s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 32 ))
mul_32s_8s_32_1_1_U1416(
    .din0(vectorA_1_q0),
    .din1(matrixB_1_q0),
    .dout(mul_ln248_fu_346_p2)
);

transformer_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            acc_fu_76 <= acc_9;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            acc_fu_76 <= acc_10_fu_510_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln245_fu_364_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_80 <= add_ln245_fu_414_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_80 <= 5'd0;
        end
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln245_fu_364_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_11_out_ap_vld = 1'b1;
    end else begin
        acc_11_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln245_fu_364_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_36 = 5'd0;
    end else begin
        ap_sig_allocacmp_i_36 = i_fu_80;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        matrixB_1_ce0_local = 1'b1;
    end else begin
        matrixB_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        matrixB_2_ce0_local = 1'b1;
    end else begin
        matrixB_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        matrixB_3_ce0_local = 1'b1;
    end else begin
        matrixB_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        matrixB_4_ce0_local = 1'b1;
    end else begin
        matrixB_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        matrixB_5_ce0_local = 1'b1;
    end else begin
        matrixB_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        matrixB_6_ce0_local = 1'b1;
    end else begin
        matrixB_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        matrixB_7_ce0_local = 1'b1;
    end else begin
        matrixB_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        matrixB_ce0_local = 1'b1;
    end else begin
        matrixB_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        vectorA_1_ce0_local = 1'b1;
    end else begin
        vectorA_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        vectorA_2_ce0_local = 1'b1;
    end else begin
        vectorA_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        vectorA_3_ce0_local = 1'b1;
    end else begin
        vectorA_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        vectorA_4_ce0_local = 1'b1;
    end else begin
        vectorA_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        vectorA_5_ce0_local = 1'b1;
    end else begin
        vectorA_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        vectorA_6_ce0_local = 1'b1;
    end else begin
        vectorA_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        vectorA_7_ce0_local = 1'b1;
    end else begin
        vectorA_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        vectorA_ce0_local = 1'b1;
    end else begin
        vectorA_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_10_fu_510_p2 = (acc_fu_76 + add_ln248_14_fu_504_p2);

assign acc_11_out = acc_fu_76;

assign add_ln245_fu_414_p2 = (ap_sig_allocacmp_i_36 + 5'd8);

assign add_ln247_fu_396_p2 = (zext_ln244_2_fu_392_p1 + p_udiv337_i);

assign add_ln248_10_fu_480_p2 = (add_ln248_9_fu_474_p2 + add_ln248_8_fu_468_p2);

assign add_ln248_11_fu_486_p2 = (mul_ln248_12_fu_331_p2 + mul_ln248_11_fu_326_p2);

assign add_ln248_12_fu_492_p2 = (mul_ln248_10_fu_321_p2 + mul_ln248_9_fu_316_p2);

assign add_ln248_13_fu_498_p2 = (add_ln248_12_fu_492_p2 + add_ln248_11_fu_486_p2);

assign add_ln248_14_fu_504_p2 = (add_ln248_13_fu_498_p2 + add_ln248_10_fu_480_p2);

assign add_ln248_8_fu_468_p2 = (mul_ln248_8_fu_311_p2 + mul_ln248_fu_346_p2);

assign add_ln248_9_fu_474_p2 = (mul_ln248_14_fu_341_p2 + mul_ln248_13_fu_336_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln245_fu_364_p2 = ((ap_sig_allocacmp_i_36 == 5'd24) ? 1'b1 : 1'b0);

assign lshr_ln244_1_fu_370_p4 = {{ap_sig_allocacmp_i_36[4:3]}};

assign matrixB_1_address0 = zext_ln247_1_fu_402_p1;

assign matrixB_1_ce0 = matrixB_1_ce0_local;

assign matrixB_2_address0 = zext_ln247_1_fu_402_p1;

assign matrixB_2_ce0 = matrixB_2_ce0_local;

assign matrixB_3_address0 = zext_ln247_1_fu_402_p1;

assign matrixB_3_ce0 = matrixB_3_ce0_local;

assign matrixB_4_address0 = zext_ln247_1_fu_402_p1;

assign matrixB_4_ce0 = matrixB_4_ce0_local;

assign matrixB_5_address0 = zext_ln247_1_fu_402_p1;

assign matrixB_5_ce0 = matrixB_5_ce0_local;

assign matrixB_6_address0 = zext_ln247_1_fu_402_p1;

assign matrixB_6_ce0 = matrixB_6_ce0_local;

assign matrixB_7_address0 = zext_ln247_1_fu_402_p1;

assign matrixB_7_ce0 = matrixB_7_ce0_local;

assign matrixB_address0 = zext_ln247_1_fu_402_p1;

assign matrixB_ce0 = matrixB_ce0_local;

assign vectorA_1_address0 = zext_ln244_1_fu_380_p1;

assign vectorA_1_ce0 = vectorA_1_ce0_local;

assign vectorA_2_address0 = zext_ln244_1_fu_380_p1;

assign vectorA_2_ce0 = vectorA_2_ce0_local;

assign vectorA_3_address0 = zext_ln244_1_fu_380_p1;

assign vectorA_3_ce0 = vectorA_3_ce0_local;

assign vectorA_4_address0 = zext_ln244_1_fu_380_p1;

assign vectorA_4_ce0 = vectorA_4_ce0_local;

assign vectorA_5_address0 = zext_ln244_1_fu_380_p1;

assign vectorA_5_ce0 = vectorA_5_ce0_local;

assign vectorA_6_address0 = zext_ln244_1_fu_380_p1;

assign vectorA_6_ce0 = vectorA_6_ce0_local;

assign vectorA_7_address0 = zext_ln244_1_fu_380_p1;

assign vectorA_7_ce0 = vectorA_7_ce0_local;

assign vectorA_address0 = zext_ln244_1_fu_380_p1;

assign vectorA_ce0 = vectorA_ce0_local;

assign zext_ln244_1_fu_380_p1 = lshr_ln244_1_fu_370_p4;

assign zext_ln244_2_fu_392_p1 = lshr_ln244_1_fu_370_p4;

assign zext_ln247_1_fu_402_p1 = add_ln247_fu_396_p2;

endmodule //transformer_top_compute_controller_Pipeline_VITIS_LOOP_245_217
