// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module transformer_top_drive_headed_compute_controller_Pipeline_VITIS_LOOP_532_25 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        head_out_buf_0_address0,
        head_out_buf_0_ce0,
        head_out_buf_0_we0,
        head_out_buf_0_d0,
        head_out_buf_0_address1,
        head_out_buf_0_ce1,
        head_out_buf_0_we1,
        head_out_buf_0_d1,
        p_ZZ31drive_headed_compute_controllerRA2_14ComputeHeadCtxbPA80_KhPA64_hPA16_aPA16_348,
        p_ZZ31drive_headed_compute_controllerRA2_14ComputeHeadCtxbPA80_KhPA64_hPA16_aPA16_349,
        p_ZZ31drive_headed_compute_controllerRA2_14ComputeHeadCtxbPA80_KhPA64_hPA16_aPA16_350,
        p_ZZ31drive_headed_compute_controllerRA2_14ComputeHeadCtxbPA80_KhPA64_hPA16_aPA16_351,
        p_ZZ31drive_headed_compute_controllerRA2_14ComputeHeadCtxbPA80_KhPA64_hPA16_aPA16_352,
        p_ZZ31drive_headed_compute_controllerRA2_14ComputeHeadCtxbPA80_KhPA64_hPA16_aPA16_353,
        p_ZZ31drive_headed_compute_controllerRA2_14ComputeHeadCtxbPA80_KhPA64_hPA16_aPA16_354,
        p_ZZ31drive_headed_compute_controllerRA2_14ComputeHeadCtxbPA80_KhPA64_hPA16_aPA16_355,
        p_ZZ31drive_headed_compute_controllerRA2_14ComputeHeadCtxbPA80_KhPA64_hPA16_aPA16_356,
        p_ZZ31drive_headed_compute_controllerRA2_14ComputeHeadCtxbPA80_KhPA64_hPA16_aPA16_357,
        p_ZZ31drive_headed_compute_controllerRA2_14ComputeHeadCtxbPA80_KhPA64_hPA16_aPA16_358,
        p_ZZ31drive_headed_compute_controllerRA2_14ComputeHeadCtxbPA80_KhPA64_hPA16_aPA16_359,
        p_ZZ31drive_headed_compute_controllerRA2_14ComputeHeadCtxbPA80_KhPA64_hPA16_aPA16_360,
        p_ZZ31drive_headed_compute_controllerRA2_14ComputeHeadCtxbPA80_KhPA64_hPA16_aPA16_361,
        p_ZZ31drive_headed_compute_controllerRA2_14ComputeHeadCtxbPA80_KhPA64_hPA16_aPA16_362,
        p_ZZ31drive_headed_compute_controllerRA2_14ComputeHeadCtxbPA80_KhPA64_hPA16_aPA16_363
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [5:0] head_out_buf_0_address0;
output   head_out_buf_0_ce0;
output   head_out_buf_0_we0;
output  [7:0] head_out_buf_0_d0;
output  [5:0] head_out_buf_0_address1;
output   head_out_buf_0_ce1;
output   head_out_buf_0_we1;
output  [7:0] head_out_buf_0_d1;
input  [15:0] p_ZZ31drive_headed_compute_controllerRA2_14ComputeHeadCtxbPA80_KhPA64_hPA16_aPA16_348;
input  [15:0] p_ZZ31drive_headed_compute_controllerRA2_14ComputeHeadCtxbPA80_KhPA64_hPA16_aPA16_349;
input  [15:0] p_ZZ31drive_headed_compute_controllerRA2_14ComputeHeadCtxbPA80_KhPA64_hPA16_aPA16_350;
input  [15:0] p_ZZ31drive_headed_compute_controllerRA2_14ComputeHeadCtxbPA80_KhPA64_hPA16_aPA16_351;
input  [15:0] p_ZZ31drive_headed_compute_controllerRA2_14ComputeHeadCtxbPA80_KhPA64_hPA16_aPA16_352;
input  [15:0] p_ZZ31drive_headed_compute_controllerRA2_14ComputeHeadCtxbPA80_KhPA64_hPA16_aPA16_353;
input  [15:0] p_ZZ31drive_headed_compute_controllerRA2_14ComputeHeadCtxbPA80_KhPA64_hPA16_aPA16_354;
input  [15:0] p_ZZ31drive_headed_compute_controllerRA2_14ComputeHeadCtxbPA80_KhPA64_hPA16_aPA16_355;
input  [15:0] p_ZZ31drive_headed_compute_controllerRA2_14ComputeHeadCtxbPA80_KhPA64_hPA16_aPA16_356;
input  [15:0] p_ZZ31drive_headed_compute_controllerRA2_14ComputeHeadCtxbPA80_KhPA64_hPA16_aPA16_357;
input  [15:0] p_ZZ31drive_headed_compute_controllerRA2_14ComputeHeadCtxbPA80_KhPA64_hPA16_aPA16_358;
input  [15:0] p_ZZ31drive_headed_compute_controllerRA2_14ComputeHeadCtxbPA80_KhPA64_hPA16_aPA16_359;
input  [15:0] p_ZZ31drive_headed_compute_controllerRA2_14ComputeHeadCtxbPA80_KhPA64_hPA16_aPA16_360;
input  [15:0] p_ZZ31drive_headed_compute_controllerRA2_14ComputeHeadCtxbPA80_KhPA64_hPA16_aPA16_361;
input  [15:0] p_ZZ31drive_headed_compute_controllerRA2_14ComputeHeadCtxbPA80_KhPA64_hPA16_aPA16_362;
input  [15:0] p_ZZ31drive_headed_compute_controllerRA2_14ComputeHeadCtxbPA80_KhPA64_hPA16_aPA16_363;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln532_fu_245_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [63:0] zext_ln766_fu_344_p1;
wire   [63:0] zext_ln767_fu_368_p1;
reg   [4:0] t_3_fu_112;
wire   [4:0] add_ln532_fu_251_p2;
wire    ap_loop_init;
reg   [4:0] ap_sig_allocacmp_t;
reg    head_out_buf_0_we1_local;
wire   [7:0] trunc_ln766_fu_339_p1;
reg    head_out_buf_0_ce1_local;
reg    head_out_buf_0_we0_local;
reg    head_out_buf_0_ce0_local;
wire   [15:0] v_fu_261_p33;
wire   [3:0] trunc_ln532_fu_257_p1;
wire   [15:0] v_fu_261_p35;
wire   [4:0] shl_ln534_fu_333_p2;
wire   [4:0] or_ln_fu_360_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [3:0] v_fu_261_p1;
wire   [3:0] v_fu_261_p3;
wire   [3:0] v_fu_261_p5;
wire   [3:0] v_fu_261_p7;
wire   [3:0] v_fu_261_p9;
wire   [3:0] v_fu_261_p11;
wire   [3:0] v_fu_261_p13;
wire   [3:0] v_fu_261_p15;
wire  signed [3:0] v_fu_261_p17;
wire  signed [3:0] v_fu_261_p19;
wire  signed [3:0] v_fu_261_p21;
wire  signed [3:0] v_fu_261_p23;
wire  signed [3:0] v_fu_261_p25;
wire  signed [3:0] v_fu_261_p27;
wire  signed [3:0] v_fu_261_p29;
wire  signed [3:0] v_fu_261_p31;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 t_3_fu_112 = 5'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) transformer_top_sparsemux_33_4_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 4'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 4'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 4'h3 ),
    .din3_WIDTH( 16 ),
    .CASE4( 4'h4 ),
    .din4_WIDTH( 16 ),
    .CASE5( 4'h5 ),
    .din5_WIDTH( 16 ),
    .CASE6( 4'h6 ),
    .din6_WIDTH( 16 ),
    .CASE7( 4'h7 ),
    .din7_WIDTH( 16 ),
    .CASE8( 4'h8 ),
    .din8_WIDTH( 16 ),
    .CASE9( 4'h9 ),
    .din9_WIDTH( 16 ),
    .CASE10( 4'hA ),
    .din10_WIDTH( 16 ),
    .CASE11( 4'hB ),
    .din11_WIDTH( 16 ),
    .CASE12( 4'hC ),
    .din12_WIDTH( 16 ),
    .CASE13( 4'hD ),
    .din13_WIDTH( 16 ),
    .CASE14( 4'hE ),
    .din14_WIDTH( 16 ),
    .CASE15( 4'hF ),
    .din15_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 16 ))
sparsemux_33_4_16_1_1_U1358(
    .din0(p_ZZ31drive_headed_compute_controllerRA2_14ComputeHeadCtxbPA80_KhPA64_hPA16_aPA16_348),
    .din1(p_ZZ31drive_headed_compute_controllerRA2_14ComputeHeadCtxbPA80_KhPA64_hPA16_aPA16_349),
    .din2(p_ZZ31drive_headed_compute_controllerRA2_14ComputeHeadCtxbPA80_KhPA64_hPA16_aPA16_350),
    .din3(p_ZZ31drive_headed_compute_controllerRA2_14ComputeHeadCtxbPA80_KhPA64_hPA16_aPA16_351),
    .din4(p_ZZ31drive_headed_compute_controllerRA2_14ComputeHeadCtxbPA80_KhPA64_hPA16_aPA16_352),
    .din5(p_ZZ31drive_headed_compute_controllerRA2_14ComputeHeadCtxbPA80_KhPA64_hPA16_aPA16_353),
    .din6(p_ZZ31drive_headed_compute_controllerRA2_14ComputeHeadCtxbPA80_KhPA64_hPA16_aPA16_354),
    .din7(p_ZZ31drive_headed_compute_controllerRA2_14ComputeHeadCtxbPA80_KhPA64_hPA16_aPA16_355),
    .din8(p_ZZ31drive_headed_compute_controllerRA2_14ComputeHeadCtxbPA80_KhPA64_hPA16_aPA16_356),
    .din9(p_ZZ31drive_headed_compute_controllerRA2_14ComputeHeadCtxbPA80_KhPA64_hPA16_aPA16_357),
    .din10(p_ZZ31drive_headed_compute_controllerRA2_14ComputeHeadCtxbPA80_KhPA64_hPA16_aPA16_358),
    .din11(p_ZZ31drive_headed_compute_controllerRA2_14ComputeHeadCtxbPA80_KhPA64_hPA16_aPA16_359),
    .din12(p_ZZ31drive_headed_compute_controllerRA2_14ComputeHeadCtxbPA80_KhPA64_hPA16_aPA16_360),
    .din13(p_ZZ31drive_headed_compute_controllerRA2_14ComputeHeadCtxbPA80_KhPA64_hPA16_aPA16_361),
    .din14(p_ZZ31drive_headed_compute_controllerRA2_14ComputeHeadCtxbPA80_KhPA64_hPA16_aPA16_362),
    .din15(p_ZZ31drive_headed_compute_controllerRA2_14ComputeHeadCtxbPA80_KhPA64_hPA16_aPA16_363),
    .def(v_fu_261_p33),
    .sel(trunc_ln532_fu_257_p1),
    .dout(v_fu_261_p35)
);

transformer_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln532_fu_245_p2 == 1'd0)) begin
            t_3_fu_112 <= add_ln532_fu_251_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            t_3_fu_112 <= 5'd0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln532_fu_245_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_t = 5'd0;
    end else begin
        ap_sig_allocacmp_t = t_3_fu_112;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        head_out_buf_0_ce0_local = 1'b1;
    end else begin
        head_out_buf_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        head_out_buf_0_ce1_local = 1'b1;
    end else begin
        head_out_buf_0_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln532_fu_245_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        head_out_buf_0_we0_local = 1'b1;
    end else begin
        head_out_buf_0_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln532_fu_245_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        head_out_buf_0_we1_local = 1'b1;
    end else begin
        head_out_buf_0_we1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln532_fu_251_p2 = (ap_sig_allocacmp_t + 5'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign head_out_buf_0_address0 = zext_ln767_fu_368_p1;

assign head_out_buf_0_address1 = zext_ln766_fu_344_p1;

assign head_out_buf_0_ce0 = head_out_buf_0_ce0_local;

assign head_out_buf_0_ce1 = head_out_buf_0_ce1_local;

assign head_out_buf_0_d0 = {{v_fu_261_p35[15:8]}};

assign head_out_buf_0_d1 = trunc_ln766_fu_339_p1;

assign head_out_buf_0_we0 = head_out_buf_0_we0_local;

assign head_out_buf_0_we1 = head_out_buf_0_we1_local;

assign icmp_ln532_fu_245_p2 = ((ap_sig_allocacmp_t == 5'd16) ? 1'b1 : 1'b0);

assign or_ln_fu_360_p3 = {{trunc_ln532_fu_257_p1}, {1'd1}};

assign shl_ln534_fu_333_p2 = ap_sig_allocacmp_t << 5'd1;

assign trunc_ln532_fu_257_p1 = ap_sig_allocacmp_t[3:0];

assign trunc_ln766_fu_339_p1 = v_fu_261_p35[7:0];

assign v_fu_261_p33 = 'bx;

assign zext_ln766_fu_344_p1 = shl_ln534_fu_333_p2;

assign zext_ln767_fu_368_p1 = or_ln_fu_360_p3;

endmodule //transformer_top_drive_headed_compute_controller_Pipeline_VITIS_LOOP_532_25
