set SynModuleInfo {
  {SRCNAME headed_compute_controller_Pipeline_VITIS_LOOP_636_28 MODELNAME headed_compute_controller_Pipeline_VITIS_LOOP_636_28 RTLNAME headed_compute_controller_headed_compute_controller_Pipeline_VITIS_LOOP_636_28
    SUBMODULES {
      {MODELNAME headed_compute_controller_flow_control_loop_pipe_sequential_init RTLNAME headed_compute_controller_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME headed_compute_controller_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME headed_compute_controller_Pipeline_VITIS_LOOP_640_29 MODELNAME headed_compute_controller_Pipeline_VITIS_LOOP_640_29 RTLNAME headed_compute_controller_headed_compute_controller_Pipeline_VITIS_LOOP_640_29}
  {SRCNAME headed_compute_controller_Pipeline_VITIS_LOOP_646_30 MODELNAME headed_compute_controller_Pipeline_VITIS_LOOP_646_30 RTLNAME headed_compute_controller_headed_compute_controller_Pipeline_VITIS_LOOP_646_30}
  {SRCNAME headed_compute_controller_Pipeline_VITIS_LOOP_650_31 MODELNAME headed_compute_controller_Pipeline_VITIS_LOOP_650_31 RTLNAME headed_compute_controller_headed_compute_controller_Pipeline_VITIS_LOOP_650_31}
  {SRCNAME headed_compute_controller_Pipeline_VITIS_LOOP_661_33 MODELNAME headed_compute_controller_Pipeline_VITIS_LOOP_661_33 RTLNAME headed_compute_controller_headed_compute_controller_Pipeline_VITIS_LOOP_661_33}
  {SRCNAME headed_compute_controller_Pipeline_VITIS_LOOP_672_34 MODELNAME headed_compute_controller_Pipeline_VITIS_LOOP_672_34 RTLNAME headed_compute_controller_headed_compute_controller_Pipeline_VITIS_LOOP_672_34
    SUBMODULES {
      {MODELNAME headed_compute_controller_sparsemux_9_2_20_1_1 RTLNAME headed_compute_controller_sparsemux_9_2_20_1_1 BINDTYPE op TYPE sparsemux IMPL compactencoding_dontcare}
    }
  }
  {SRCNAME headed_compute_controller_Pipeline_VITIS_LOOP_622_26 MODELNAME headed_compute_controller_Pipeline_VITIS_LOOP_622_26 RTLNAME headed_compute_controller_headed_compute_controller_Pipeline_VITIS_LOOP_622_26}
  {SRCNAME SOFTMAX_Pipeline_VITIS_LOOP_232_1 MODELNAME SOFTMAX_Pipeline_VITIS_LOOP_232_1 RTLNAME headed_compute_controller_SOFTMAX_Pipeline_VITIS_LOOP_232_1}
  {SRCNAME SOFTMAX_Pipeline_VITIS_LOOP_245_2 MODELNAME SOFTMAX_Pipeline_VITIS_LOOP_245_2 RTLNAME headed_compute_controller_SOFTMAX_Pipeline_VITIS_LOOP_245_2
    SUBMODULES {
      {MODELNAME headed_compute_controller_sparsemux_7_2_15_1_1 RTLNAME headed_compute_controller_sparsemux_7_2_15_1_1 BINDTYPE op TYPE sparsemux IMPL onehotencoding_realdef}
      {MODELNAME headed_compute_controller_SOFTMAX_Pipeline_VITIS_LOOP_245_2_exp_lut_q15_ROM_AUTO_1R RTLNAME headed_compute_controller_SOFTMAX_Pipeline_VITIS_LOOP_245_2_exp_lut_q15_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME SOFTMAX_Pipeline_VITIS_LOOP_266_3 MODELNAME SOFTMAX_Pipeline_VITIS_LOOP_266_3 RTLNAME headed_compute_controller_SOFTMAX_Pipeline_VITIS_LOOP_266_3
    SUBMODULES {
      {MODELNAME headed_compute_controller_mul_31s_16ns_31_1_1 RTLNAME headed_compute_controller_mul_31s_16ns_31_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME headed_compute_controller_sparsemux_33_4_16_1_1 RTLNAME headed_compute_controller_sparsemux_33_4_16_1_1 BINDTYPE op TYPE sparsemux IMPL compactencoding_dontcare}
    }
  }
  {SRCNAME SOFTMAX MODELNAME SOFTMAX RTLNAME headed_compute_controller_SOFTMAX
    SUBMODULES {
      {MODELNAME headed_compute_controller_udiv_31ns_19ns_31_35_seq_1 RTLNAME headed_compute_controller_udiv_31ns_19ns_31_35_seq_1 BINDTYPE op TYPE udiv IMPL auto_seq LATENCY 34 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME headed_compute_controller_Pipeline_VITIS_LOOP_627_27 MODELNAME headed_compute_controller_Pipeline_VITIS_LOOP_627_27 RTLNAME headed_compute_controller_headed_compute_controller_Pipeline_VITIS_LOOP_627_27}
  {SRCNAME headed_compute_controller_Pipeline_VITIS_LOOP_610_24 MODELNAME headed_compute_controller_Pipeline_VITIS_LOOP_610_24 RTLNAME headed_compute_controller_headed_compute_controller_Pipeline_VITIS_LOOP_610_24}
  {SRCNAME headed_compute_controller_Pipeline_VITIS_LOOP_160_1 MODELNAME headed_compute_controller_Pipeline_VITIS_LOOP_160_1 RTLNAME headed_compute_controller_headed_compute_controller_Pipeline_VITIS_LOOP_160_1}
  {SRCNAME headed_compute_controller_Pipeline_VITIS_LOOP_615_25 MODELNAME headed_compute_controller_Pipeline_VITIS_LOOP_615_25 RTLNAME headed_compute_controller_headed_compute_controller_Pipeline_VITIS_LOOP_615_25}
  {SRCNAME headed_compute_controller_Pipeline_VITIS_LOOP_564_17 MODELNAME headed_compute_controller_Pipeline_VITIS_LOOP_564_17 RTLNAME headed_compute_controller_headed_compute_controller_Pipeline_VITIS_LOOP_564_17}
  {SRCNAME headed_compute_controller_Pipeline_VITIS_LOOP_568_18 MODELNAME headed_compute_controller_Pipeline_VITIS_LOOP_568_18 RTLNAME headed_compute_controller_headed_compute_controller_Pipeline_VITIS_LOOP_568_18}
  {SRCNAME headed_compute_controller_Pipeline_VITIS_LOOP_574_19 MODELNAME headed_compute_controller_Pipeline_VITIS_LOOP_574_19 RTLNAME headed_compute_controller_headed_compute_controller_Pipeline_VITIS_LOOP_574_19}
  {SRCNAME headed_compute_controller_Pipeline_VITIS_LOOP_578_20 MODELNAME headed_compute_controller_Pipeline_VITIS_LOOP_578_20 RTLNAME headed_compute_controller_headed_compute_controller_Pipeline_VITIS_LOOP_578_20}
  {SRCNAME headed_compute_controller_Pipeline_VITIS_LOOP_589_22 MODELNAME headed_compute_controller_Pipeline_VITIS_LOOP_589_22 RTLNAME headed_compute_controller_headed_compute_controller_Pipeline_VITIS_LOOP_589_22}
  {SRCNAME headed_compute_controller_Pipeline_VITIS_LOOP_599_23 MODELNAME headed_compute_controller_Pipeline_VITIS_LOOP_599_23 RTLNAME headed_compute_controller_headed_compute_controller_Pipeline_VITIS_LOOP_599_23
    SUBMODULES {
      {MODELNAME headed_compute_controller_sparsemux_33_4_20_1_1 RTLNAME headed_compute_controller_sparsemux_33_4_20_1_1 BINDTYPE op TYPE sparsemux IMPL compactencoding_dontcare}
    }
  }
  {SRCNAME headed_compute_controller_Pipeline_VITIS_LOOP_548_15 MODELNAME headed_compute_controller_Pipeline_VITIS_LOOP_548_15 RTLNAME headed_compute_controller_headed_compute_controller_Pipeline_VITIS_LOOP_548_15}
  {SRCNAME headed_compute_controller_Pipeline_VITIS_LOOP_555_16 MODELNAME headed_compute_controller_Pipeline_VITIS_LOOP_555_16 RTLNAME headed_compute_controller_headed_compute_controller_Pipeline_VITIS_LOOP_555_16
    SUBMODULES {
      {MODELNAME headed_compute_controller_sparsemux_9_2_8_1_1 RTLNAME headed_compute_controller_sparsemux_9_2_8_1_1 BINDTYPE op TYPE sparsemux IMPL compactencoding_dontcare}
    }
  }
  {SRCNAME headed_compute_controller_Pipeline_VITIS_LOOP_496_7 MODELNAME headed_compute_controller_Pipeline_VITIS_LOOP_496_7 RTLNAME headed_compute_controller_headed_compute_controller_Pipeline_VITIS_LOOP_496_7}
  {SRCNAME headed_compute_controller_Pipeline_VITIS_LOOP_500_8 MODELNAME headed_compute_controller_Pipeline_VITIS_LOOP_500_8 RTLNAME headed_compute_controller_headed_compute_controller_Pipeline_VITIS_LOOP_500_8}
  {SRCNAME headed_compute_controller_Pipeline_VITIS_LOOP_506_9 MODELNAME headed_compute_controller_Pipeline_VITIS_LOOP_506_9 RTLNAME headed_compute_controller_headed_compute_controller_Pipeline_VITIS_LOOP_506_9}
  {SRCNAME headed_compute_controller_Pipeline_VITIS_LOOP_510_10 MODELNAME headed_compute_controller_Pipeline_VITIS_LOOP_510_10 RTLNAME headed_compute_controller_headed_compute_controller_Pipeline_VITIS_LOOP_510_10}
  {SRCNAME headed_compute_controller_Pipeline_VITIS_LOOP_520_12 MODELNAME headed_compute_controller_Pipeline_VITIS_LOOP_520_12 RTLNAME headed_compute_controller_headed_compute_controller_Pipeline_VITIS_LOOP_520_12}
  {SRCNAME headed_compute_controller_Pipeline_VITIS_LOOP_534_14 MODELNAME headed_compute_controller_Pipeline_VITIS_LOOP_534_14 RTLNAME headed_compute_controller_headed_compute_controller_Pipeline_VITIS_LOOP_534_14}
  {SRCNAME headed_compute_controller_Pipeline_VITIS_LOOP_139_1 MODELNAME headed_compute_controller_Pipeline_VITIS_LOOP_139_1 RTLNAME headed_compute_controller_headed_compute_controller_Pipeline_VITIS_LOOP_139_1
    SUBMODULES {
      {MODELNAME headed_compute_controller_sparsemux_33_4_4_1_1 RTLNAME headed_compute_controller_sparsemux_33_4_4_1_1 BINDTYPE op TYPE sparsemux IMPL compactencoding_dontcare}
      {MODELNAME headed_compute_controller_mul_8s_8s_16_1_1 RTLNAME headed_compute_controller_mul_8s_8s_16_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME headed_compute_controller_mac_muladd_8s_8s_4s_16_4_1 RTLNAME headed_compute_controller_mac_muladd_8s_8s_4s_16_4_1 BINDTYPE op TYPE all IMPL dsp_slice LATENCY 3}
      {MODELNAME headed_compute_controller_mac_muladd_8s_8s_16s_17_4_1 RTLNAME headed_compute_controller_mac_muladd_8s_8s_16s_17_4_1 BINDTYPE op TYPE all IMPL dsp_slice LATENCY 3}
    }
  }
  {SRCNAME headed_compute_controller_Pipeline_VITIS_LOOP_440_6 MODELNAME headed_compute_controller_Pipeline_VITIS_LOOP_440_6 RTLNAME headed_compute_controller_headed_compute_controller_Pipeline_VITIS_LOOP_440_6}
  {SRCNAME headed_compute_controller MODELNAME headed_compute_controller RTLNAME headed_compute_controller IS_TOP 1
    SUBMODULES {
      {MODELNAME headed_compute_controller_mul_32s_32s_64_1_1 RTLNAME headed_compute_controller_mul_32s_32s_64_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME headed_compute_controller_headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_33_RAMbkb RTLNAME headed_compute_controller_headed_compute_controller_bool_bool_unsigned_int_bool_bool_bool_bool_b_33_RAMbkb BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME headed_compute_controller_val_in_RAM_AUTO_1R1W RTLNAME headed_compute_controller_val_in_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME headed_compute_controller_val_scaled_RAM_AUTO_1R1W RTLNAME headed_compute_controller_val_scaled_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME headed_compute_controller_soft_out_RAM_AUTO_1R1W RTLNAME headed_compute_controller_soft_out_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
}
